export const cartesiaVoices = [
  {
    id: "f91ab3e6-5071-4e15-b016-cde6f2bcd222",
    name: "Aadhya",
    languages: ["hi-IN"],
    description: "Slow female voice for casual conversation",
    gender: "female",
    tags: ["soother", "standard hindi"],
  },
  {
    id: "9cebb910-d4b7-4a4a-85a4-12c79137724c",
    name: "Aarti",
    languages: ["hi-IN"],
    description: "Indian accented female for relatable dialogue",
    gender: "female",
    tags: ["conversationalist", "standard hindi"],
  },
  {
    id: "e2d48e7b-cd73-4c4c-bc1e-f232580e8709",
    name: "Adrian",
    languages: ["en-US"],
    description:
      "Deep American adult male voice with a curious and engaging tone for explorations, documentaries, and storytelling",
    gender: "male",
    tags: ["explorer", "general american"],
  },
  {
    id: "2695b6b5-5543-4be1-96d9-3967fb5e7fec",
    name: "Agustin",
    languages: ["es-MX"],
    description: "Intentional, clear adult for concise reports or storytelling",
    gender: "male",
    tags: ["clear", "storyteller", "mexican"],
  },
  {
    id: "83604597-55fa-4ccc-8357-730b313f353f",
    name: "Aisyah",
    languages: ["ms-MY"],
    description:
      "Friendly and upbeat adult female voice for casual conversations and engaging everyday dialogue",
    gender: "female",
    tags: ["chat", "partner", "malay"],
  },
  {
    id: "87748186-23bb-4158-a1eb-332911b0b708",
    name: "Alaric",
    languages: ["en-GB"],
    description:
      "Wistful, wise, elderly male for entertainment and fun characters",
    gender: "male",
    tags: ["wizard", "british"],
  },
  {
    id: "9a0894a9-28f0-436e-9a1d-e92bccbce4dd",
    name: "Albert",
    languages: ["en-US"],
    description:
      "English male adult voice with a firm and authoritative tone for providing clear instructions and guidance",
    gender: "male",
    tags: ["firm", "guide", "general american"],
  },
  {
    id: "0e21713a-5e9a-428a-bed4-90d410b87f13",
    name: "Alessandra",
    languages: ["it-IT"],
    description: "Graceful female for providing instructions and guidance",
    gender: "female",
    tags: ["melodic", "guide", "standard italian"],
  },
  {
    id: "38aabb6a-f52b-4fb0-a3d1-988518f4dc06",
    name: "Alina",
    languages: ["de-DE"],
    description:
      "Warm female for phone systems, virtual assistants, and customer service",
    gender: "female",
    tags: ["engaging", "assistant", "standard german"],
  },
  {
    id: "9287676d-f0cc-423f-ac03-3b3c7242f091",
    name: "Allen",
    languages: ["en-US"],
    description:
      "Confident young adult male voice with a neutral American accent for presentations, ads, and engaging everyday conversations",
    gender: "male",
    tags: ["modern", "voice", "general american"],
  },
  {
    id: "a7a59115-2425-4192-844c-1e98ec7d6877",
    name: "Amber",
    languages: ["en-US"],
    description:
      "English female adult voice with a cheerful yet deeper tone, striking a balance of warmth and authority for customer service use",
    gender: "female",
    tags: ["warm", "support", "agent", "general american"],
  },
  {
    id: "043cfc81-d69f-4bee-ae1e-7862cb358650",
    name: "Amelia",
    languages: ["en-AU"],
    description:
      "Strong, composed female voice suited for giving instructions with clarity and authority",
    gender: "female",
    tags: ["instructor", "australian"],
  },
  {
    id: "6304c635-6681-4f9e-85b6-a97f4d26461a",
    name: "Amira",
    languages: ["ar-SA"],
    description:
      "Calm, soft-spoken adult female for narrations and storytelling",
    gender: "female",
    tags: ["dreamy", "whisperer", "modern standard arabic"],
  },
  {
    id: "1cf751f6-8749-43ab-98bd-230dd633abdb",
    name: "Ana Paula",
    languages: ["pt-BR"],
    description: "Warm, friendly female for natural, informal dialogue",
    gender: "female",
    tags: ["marketer", "brazilian portuguese"],
  },
  {
    id: "a053f6bc-7df4-40de-96d4-de026bc47ce8",
    name: "Andi",
    languages: ["id-ID", "en-US"],
    description:
      "Expressive adult male voice with an upbeat tone for advertisements, promotions, and lively announcements",
    gender: "male",
    tags: ["dynamic", "presenter", "standard indonesian"],
  },
  {
    id: "34acfaee-c556-41ee-a5f6-c687fb20357c",
    name: "Andrada",
    languages: ["ro-MD"],
    description:
      "Clear and monotone adult female voice for instructions formal announcements, and straightforward communication",
    gender: "female",
    tags: ["steady", "speaker", "moldovan"],
  },
  {
    id: "db229dfe-f5de-4be4-91fd-7b077c158578",
    name: "Andreas",
    languages: ["de-DE"],
    description: "Smooth male for story narration",
    gender: "male",
    tags: ["recorder", "standard german"],
  },
  {
    id: "3f64ef99-d87b-4b51-b217-df7351f7886a",
    name: "Andrei",
    languages: ["ro-MD"],
    description:
      "Casual yet firm middle-aged male voice for everyday conversations, guidance, and professional dialogue",
    gender: "male",
    tags: ["conversationalist", "guy", "moldovan"],
  },
  {
    id: "887149a8-4616-42ad-b2ce-c3819176f45d",
    name: "Andrzej",
    languages: ["pl-PL"],
    description:
      "Wise-sounding elderly male voice with a calm and casual tone for storytelling, guidance, and everyday conversations",
    gender: "male",
    tags: ["elder", "voice", "polish"],
  },
  {
    id: "c4cbcb7d-d9fa-4eac-b547-46831718ef58",
    name: "Angelo",
    languages: ["tl-PH"],
    description:
      "Gentle young adult male voice with a calm and approachable tone for casual conversations, support, and narrations",
    gender: "male",
    tags: ["calm", "narrator", "manila"],
  },
  {
    id: "5c32dce6-936a-4892-b131-bafe474afe5f",
    name: "Anika",
    languages: ["mr-IN", "de-DE", "fr-FR", "it-IT", "pt-BR", "zh-CN"],
    description:
      "Energetic and approachable adult female voice for sales conversations, casual chat, and customer support",
    gender: "female",
    tags: ["enthusiastic", "seller", "konkani"],
  },
  {
    id: "209d9a43-03eb-40d8-a7b7-51a6d54c052f",
    name: "Anita",
    languages: ["hi-IN"],
    description:
      "Soft-spoken adult female voice for casual conversations, meditation, and calming dialogue",
    gender: "female",
    tags: ["meditation", "guide", "bagheli"],
  },
  {
    id: "ac317dac-1b8f-434f-b198-a490e2a4914d",
    name: "Anneke",
    languages: ["nl-NL"],
    description:
      "Soft-spoken adult female voice with a warm and caring tone for supportive conversations and gentle guidance",
    gender: "female",
    tags: ["trusted", "guide", "randstad"],
  },
  {
    id: "ef191366-f52f-447a-a398-ed8c0f2943a1",
    name: "Archie",
    languages: [
      "en-GB",
      "hi-IN",
      "es-ES",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description:
      "Warm, conversational British male for casual and engaging dialogue.",
    gender: "male",
    tags: ["approachable", "mate", "british"],
  },
  {
    id: "d2870b91-1b4c-47ab-81a8-3718d8e9c222",
    name: "Arun",
    languages: ["ta-IN"],
    description:
      "Expressive adult voice with a lively tone for storytelling, narrations, and engaging cultural content",
    gender: "male",
    tags: ["lively", "voice", "central tamil"],
  },
  {
    id: "95d51f79-c397-46f9-b49a-23763d3eaa2d",
    name: "Arushi",
    languages: ["hi-IN"],
    description: "Hinglish female for bilingual content",
    gender: "female",
    tags: ["hinglish", "speaker", "standard hindi"],
  },
  {
    id: "00967b2f-88a6-4a31-8153-110a92134b9f",
    name: "Asher",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description: "Firm adult male for audiobooks and clear communication",
    gender: "male",
    tags: ["podcaster", "general american"],
  },
  {
    id: "8f091740-3df1-4795-8bd9-dc62d88e5131",
    name: "Aurora",
    languages: ["en-US"],
    description: "Fairy like female for character use cases in entertainment",
    gender: "female",
    tags: ["fairy", "princess", "general american"],
  },
  {
    id: "cccc21e8-5bcf-4ff0-bc7f-be4e40afc544",
    name: "Avery",
    languages: ["en-US"],
    description:
      "High pitched, energetic young female for animated characters and gaming and entertainment use cases",
    gender: "female",
    tags: ["gaming", "girl", "general american"],
  },
  {
    id: "91e91d74-8eb4-43cd-97d3-7466c21db00d",
    name: "Aykut",
    languages: ["tr-TR"],
    description:
      "Relaxed adult male voice with a natural and approachable tone for casual chats and everyday conversations",
    gender: "male",
    tags: ["friendly", "companion", "istanbul"],
  },
  {
    id: "bb2347fe-69e9-4810-873f-ffd759fe8420",
    name: "Aylin",
    languages: ["tr-TR"],
    description: "Friendly female for narrations and explainer videos",
    gender: "female",
    tags: ["warm", "guide", "istanbul"],
  },
  {
    id: "31c55968-a9f4-4115-8831-3a16952179c8",
    name: "Ayumi",
    languages: ["ja-JP"],
    description:
      "Upbeat and enthusiastic adult female voice for sales, promotions, and engaging customer interactions",
    gender: "female",
    tags: ["sales", "guide", "standard japanese"],
  },
  {
    id: "0f95596c-09c4-4418-99fe-5c107e0713c0",
    name: "Azra",
    languages: ["tr-TR"],
    description:
      "Firm and clear adult voice with a professional tone for instructions, customer service, and formal communication",
    gender: "female",
    tags: ["service", "specialist", "istanbul"],
  },
  {
    id: "13524ffb-a918-499a-ae97-c98c7c4408c4",
    name: "Barry",
    languages: ["en-AU"],
    description:
      "Inviting, friendly male for customer support and product videos",
    gender: "male",
    tags: ["helper", "australian"],
  },
  {
    id: "d4b44b9a-82bc-4b65-b456-763fce4c52f9",
    name: "Beatriz",
    languages: ["pt-PT"],
    description: "Friendly, natural female for engaging conversation",
    gender: "female",
    tags: ["support", "guide", "european portuguese"],
  },
  {
    id: "7cf0e2b1-8daf-4fe4-89ad-f6039398f359",
    name: "Benedict",
    languages: ["en-GB"],
    description: "Confident, firm male for narrations",
    gender: "male",
    tags: ["royal", "narrator", "british"],
  },
  {
    id: "a167e0f3-df7e-4d52-a9c3-f949145efdab",
    name: "Blake",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "te-IN",
      "zh-CN",
    ],
    description: "Energetic adult male for engaging customer support",
    gender: "male",
    tags: ["helpful", "agent", "general american"],
  },
  {
    id: "607167f6-9bf2-473c-accc-ac7b3b66b30b",
    name: "Brenda",
    languages: ["en-US"],
    description:
      "Cheerful, friendly female voice that creates a positive, helpful experience for customer interactions",
    gender: "female",
    tags: ["host", "african american"],
  },
  {
    id: "46788d8e-cdf9-4d5c-9125-094eb2e4d44c",
    name: "Brittany",
    languages: ["en-US"],
    description:
      "Strong and aggressive American-accented female voice for intense dialogue, dramatic roles, or high-energy commercials",
    gender: "female",
    tags: ["intense", "performer", "general american"],
  },
  {
    id: "e07c00bc-4134-4eae-9ea4-1a55fb45746b",
    name: "Brooke",
    languages: [
      "en-US",
      "es-MX",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "te-IN",
    ],
    description: "Confident adult female for conversational use cases",
    gender: "female",
    tags: ["big", "sister", "general american"],
  },
  {
    id: "00a77add-48d5-4ef6-8157-71e5437b282d",
    name: "Callie",
    languages: ["en-US"],
    description: "Smooth, young adult female for empathetic conversation",
    gender: "female",
    tags: ["encourager", "general american"],
  },
  {
    id: "da4a4eff-3b7e-4846-8f70-f075ff61222c",
    name: "Callum",
    languages: ["en-AU"],
    description:
      "Neutral, confident young adult male fit for voiceovers and customer interactions",
    gender: "male",
    tags: ["brand", "spokesperson", "australian"],
  },
  {
    id: "03496517-369a-4db1-8236-3d3ae459ddf7",
    name: "Calypso",
    languages: ["en-US"],
    description: "Soothing female for meditations and other calming use cases",
    gender: "female",
    tags: ["asmr", "lady", "general american"],
  },
  {
    id: "55deba52-bc73-4481-ab69-9c8831c8a7c3",
    name: "Camille",
    languages: ["en-US"],
    description:
      "Calm, neutral female for customer support and instructional videos",
    gender: "female",
    tags: ["friendly", "expert", "general american"],
  },
  {
    id: "1fc31370-81b1-4588-9c1a-f93793c6e01d",
    name: "Carlo",
    languages: ["it-IT"],
    description: "Inviting, young accented male for tourism use cases",
    gender: "male",
    tags: ["roman", "guide", "standard italian"],
  },
  {
    id: "727f663b-0e90-4031-90f2-558b7334425b",
    name: "Carmen",
    languages: [
      "es-BO",
      "hi-IN",
      "de-DE",
      "fr-FR",
      "he-IL",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description:
      "Natural adult female voice for casual conversations and everyday interactions",
    gender: "female",
    tags: ["friendly", "neighbor", "camba"],
  },
  {
    id: "bf991597-6c13-47e4-8411-91ec2de5c466",
    name: "Carol",
    languages: ["en-US"],
    description: "Authortative, mature female for giving instructions",
    gender: "female",
    tags: ["task", "coach", "general american"],
  },
  {
    id: "f9836c6e-a0bd-460e-9d3c-f7299fa60f94",
    name: "Caroline",
    languages: ["en-US"],
    description:
      "Friendly, inviting, slow young adult female for conversation support",
    gender: "female",
    tags: ["southern", "guide", "southern us"],
  },
  {
    id: "86e30c1d-714b-4074-a1f2-1cb6b552fb49",
    name: "Carson",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description: "Friendly young adult male for customer support conversations",
    gender: "male",
    tags: ["curious", "conversationalist", "general american"],
  },
  {
    id: "4df027cb-2920-4a1f-8c34-f21529d5c3fe",
    name: "Carson",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "ar-SA",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
    ],
    description:
      "Friendly, young adult male for customer support conversations",
    gender: "male",
    tags: ["friendly", "support", "general american"],
  },
  {
    id: "3246e36c-ac8c-418d-83cd-4eaad5a3b887",
    name: "Carson",
    languages: ["en-US"],
    description: "Friendly young adult male for customer support conversations",
    gender: "male",
    tags: ["sad", "friendly", "support", "general american"],
  },
  {
    id: "96c64eb5-a945-448f-9710-980abe7a514c",
    name: "Carson",
    languages: ["en-US"],
    description:
      "Friendly, young adult male for customer support conversations",
    gender: "male",
    tags: ["friendly", "support", "general american"],
  },
  {
    id: "0b32066b-2bcc-44b9-89ab-0223a09d1606",
    name: "Carson",
    languages: ["en-US"],
    description: "Friendly young adult male for customer support conversations",
    gender: "male",
    tags: ["angry", "friendly", "support", "general american"],
  },
  {
    id: "5c43e078-5ba4-4e1f-9639-8d85a403f76a",
    name: "Carson",
    languages: ["en-US"],
    description: "Friendly young adult male for customer support conversations",
    gender: "male",
    tags: ["scared", "friendly", "support", "general american"],
  },
  {
    id: "66f5935b-af2e-4ec9-bb3e-59112e9ddc93",
    name: "Carson",
    languages: ["en-US"],
    description: "Friendly young adult male for customer support conversations",
    gender: "male",
    tags: ["surprised", "friendly", "support", "general american"],
  },
  {
    id: "ee8b13e7-98af-4b15-89d1-8d402be10c94",
    name: "Carson",
    languages: ["en-US"],
    description: "Friendly young adult male for customer support conversations",
    gender: "male",
    tags: ["disgusted", "friendly", "support", "general american"],
  },
  {
    id: "4f7f1324-1853-48a6-b294-4e78e8036a83",
    name: "Casper",
    languages: ["en-GB"],
    description: "Wistful, young male for emotional narrations",
    gender: "male",
    tags: ["gentle", "narrator", "british"],
  },
  {
    id: "d7862948-75c3-4c7c-ae28-2959fe166f49",
    name: "Caspian",
    languages: ["en-GB"],
    description: "Echo-y, mystical male for characters with gravitas",
    gender: "male",
    tags: ["oracle", "british"],
  },
  {
    id: "e8e5fffb-252c-436d-b842-8879b84445b6",
    name: "Cathy",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "ar-SA",
      "de-DE",
      "fr-CA",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description: "Nice, young adult female for casual conversations",
    gender: "female",
    tags: ["coworker", "general american"],
  },
  {
    id: "0caedb75-417f-4e36-9b64-c21354cb94c8",
    name: "Cees",
    languages: ["sv-SE"],
    description: "Enunciating male for smooth conversations",
    gender: "male",
    tags: ["nordic", "narrator", "stockholm"],
  },
  {
    id: "71a7ad14-091c-4e8e-a314-022ece01c121",
    name: "Charlotte",
    languages: ["en-GB"],
    description: "Elegant, young adult female for narrations",
    gender: "female",
    tags: ["heiress", "british"],
  },
  {
    id: "f762e181-ddc7-486e-9a48-636bd7e229d4",
    name: "Chloe",
    languages: ["en-US"],
    description:
      "English female adult voice with a confident and persuasive tone, able to influence and engage listeners with clarity and conviction",
    gender: "female",
    tags: ["persuasive", "lady", "general american"],
  },
  {
    id: "01eaafa9-308a-4276-a017-6ab0cf061b1f",
    name: "Clara",
    languages: ["en-US"],
    description:
      "Middle-aged American female voice with a clear tone and precise enunciation for instructions, customer support, and professional presentations",
    gender: "female",
    tags: ["instructor", "general american"],
  },
  {
    id: "41534e16-2966-4c6b-9670-111411def906",
    name: "Clarence",
    languages: ["en-US"],
    description:
      "Firm, deep male with old time radio like acoustics for 20th century historical reenactments",
    gender: "male",
    tags: ["newsman", "general american"],
  },
  {
    id: "98a34ef2-2140-4c28-9c71-663dc4dd7022",
    name: "Clyde",
    languages: ["en-US"],
    description:
      "Gentle, measured male voice with warmth and clarity for storytelling and informative reads",
    gender: "male",
    tags: ["calm", "narrator", "southern us"],
  },
  {
    id: "8d8ce8c9-44a4-46c4-b10f-9a927b99a853",
    name: "Connie",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description:
      "Natural, cheery young adult female for authentic conversations",
    gender: "female",
    tags: ["candid", "conversationalist", "general american"],
  },
  {
    id: "92c41dd4-04aa-45de-8504-a92b40cb8818",
    name: "Connor",
    languages: ["en-US"],
    description:
      "Expressive American adult male voice with a grateful yet firm tone for speeches, storytelling, and professional communication",
    gender: "male",
    tags: ["grateful", "person", "general american"],
  },
  {
    id: "630ed21c-2c5c-41cf-9d82-10a7fd668370",
    name: "Corey",
    languages: ["en-US"],
    description: "Inviting, cheerful young adult male for casual conversation.",
    gender: "male",
    tags: ["supportive", "buddy", "general american"],
  },
  {
    id: "e8a863c6-22c7-4671-86ca-91cacffc038d",
    name: "Daisuke",
    languages: ["ja-JP"],
    description: "Business-like, clear male for professional use cases",
    gender: "male",
    tags: ["businessman", "standard japanese"],
  },
  {
    id: "32b3f3c5-7171-46aa-abe7-b598964aa793",
    name: "Daisy",
    languages: ["en-US"],
    description:
      "Very young female for children's book narrations and young animated personas",
    gender: "female",
    tags: ["reading", "girl", "general american"],
  },
  {
    id: "23e9e50a-4ea2-447b-b589-df90dbb848a2",
    name: "Dallas",
    languages: ["en-US"],
    description: "Kind male for inviting and authentic conversations",
    gender: "male",
    tags: ["fireside", "friend", "southern us"],
  },
  {
    id: "5c5ad5e7-1020-476b-8b91-fdcbe9cc313c",
    name: "Daniela",
    languages: ["es-MX"],
    description:
      "Calm and trusting Mexican accented female for natural conversations and efficient assistance",
    gender: "female",
    tags: ["relaxed", "woman", "mexican"],
  },
  {
    id: "09ed0318-2f4a-41b1-abe5-d11da7537c31",
    name: "Daphne",
    languages: ["en-US"],
    description:
      "Expressive and upbeat American-accented female voice with an exciting tone for ads, presentations, and lively storytelling",
    gender: "female",
    tags: ["excited", "woman", "general american"],
  },
  {
    id: "996a8b96-4804-46f0-8e05-3fd4ef1a87cd",
    name: "Darla",
    languages: ["en-CA"],
    description:
      "Firm and confident female voice with a calm, supportive tone - ideal for customer support roles",
    gender: "female",
    tags: ["resolution", "agent", "canadian english"],
  },
  {
    id: "da69d796-4603-4419-8a95-293bfc5679eb",
    name: "David",
    languages: ["en-US"],
    description: "Engaging adult male for advertising and upbeat conversations",
    gender: "male",
    tags: ["greeter", "general american"],
  },
  {
    id: "50849023-76e9-46c7-af52-9ec39888a165",
    name: "Despina",
    languages: ["el-GR"],
    description:
      "Warm yet authoritative middle-aged female voice, with a motherly tone for guidance, reassurance, and clear instruction",
    gender: "female",
    tags: ["motherly", "woman", "thessaloniki"],
  },
  {
    id: "1259b7e3-cb8a-43df-9446-30971a46b8b0",
    name: "Devansh",
    languages: ["en-IN"],
    description:
      "Warm, conversational Indian male adult voice for casual chats, everyday interactions, and friendly user engagement",
    gender: "male",
    tags: ["warm", "support", "agent", "indian english"],
  },
  {
    id: "2be00b67-d53f-4eb5-89e7-96c224d56fbc",
    name: "Dieter",
    languages: ["de-DE"],
    description:
      "Loud and expressive adult male voice for storytelling, commercials, and energetic announcements",
    gender: "male",
    tags: ["commercial", "man", "standard german"],
  },
  {
    id: "7c6219d2-e8d2-462c-89d8-7ecba7c75d65",
    name: "Divya",
    languages: [
      "kn-IN",
      "es-MX",
      "ar-SA",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description:
      "Lively and cheerful adult female voice for product advertisements, upbeat promotions, and happy storytelling",
    gender: "female",
    tags: ["joyful", "narrator", "southern karnataka"],
  },
  {
    id: "0c8ed86e-6c64-40f0-b252-b773911de6bb",
    name: "Doris",
    languages: ["en-US"],
    description:
      "Warm and relatable female voice suited for casual, natural conversations",
    gender: "female",
    tags: ["friend", "general american"],
  },
  {
    id: "e3827ec5-697a-4b7c-9704-1a23041bbc51",
    name: "Dottie",
    languages: ["en-US"],
    description:
      "High pitched, earnest, very young female for character narrations for children",
    gender: "female",
    tags: ["sweet", "gal", "general american"],
  },
  {
    id: "c8605446-247c-4d39-acd4-8f4c28aa363c",
    name: "Edith",
    languages: ["en-US"],
    description: "Elderly, confident female for narrations and wise characters",
    gender: "female",
    tags: ["matriarch", "general american"],
  },
  {
    id: "cefcb124-080b-4655-b31f-932f3ee743de",
    name: "Elena",
    languages: ["es-ES"],
    description:
      "Smooth and grounded female with a soft Castilian accent for podcasts and meditation",
    gender: "female",
    tags: ["narrator", "castilian"],
  },
  {
    id: "6a176356-ada1-4b48-b2ae-3a3fdd485680",
    name: "Elias",
    languages: ["en-US"],
    description: "Deep male for entertainment and gaming characters",
    gender: "male",
    tags: ["night", "warden", "general american"],
  },
  {
    id: "00510a15-4216-4fdc-a0ab-05d74cd9f795",
    name: "Elina",
    languages: ["sv-SE"],
    description:
      "Firm and professional adult female voice for news delivery, announcements, and formal presentations",
    gender: "female",
    tags: ["clear", "presenter", "woman", "stockholm"],
  },
  {
    id: "248be419-c632-4f23-adf1-5324ed7dbf1d",
    name: "Elizabeth",
    languages: ["en-US"],
    description:
      "Enunicating young female for providing guidance and instructions",
    gender: "female",
    tags: ["manager", "general american"],
  },
  {
    id: "2a12b36c-7f9b-4c3a-9f7a-72731b15323a",
    name: "Ella",
    languages: ["en-AU"],
    description:
      "Approachable presence for bright, lightweight and everyday customer conversations.",
    gender: "female",
    tags: ["caring", "scout", "australian"],
  },
  {
    id: "a151affa-feaa-439e-8df8-c1d3f91dc6b9",
    name: "Ellen",
    languages: ["en-US"],
    description:
      "Authentic female voice with balanced warmth and clarity for both casual and support-driven contexts",
    gender: "female",
    tags: ["welcome", "agent", "general american"],
  },
  {
    id: "7edf9efb-58fc-46ba-a648-3a00a86b111b",
    name: "Elliott",
    languages: ["en-US"],
    description:
      "English male adult voice with a soft, melancholic tone and a questioning inflection for storytelling and emotional dialogue",
    gender: "male",
    tags: ["reflective", "storyteller", "general american"],
  },
  {
    id: "6c64b57a-bc65-48e4-bff4-12dbe85606cd",
    name: "Eloise",
    languages: ["fr-FR"],
    description:
      "Clear and well-paced adult female voice with a warm tone for customer service and professional communication",
    gender: "female",
    tags: ["dialogue", "anchor", "parisian"],
  },
  {
    id: "c7eafe22-8b71-40cd-850b-c5a3bbd8f8d2",
    name: "Emi",
    languages: ["ja-JP"],
    description:
      "Soft and delicate female with a gentle, timid tone for female game characters and children's book narrations",
    gender: "female",
    tags: ["soft-spoken", "friend", "standard japanese"],
  },
  {
    id: "f6ff7c0c-e396-40a9-a70b-f7607edb6937",
    name: "Emma",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "zh-CN",
    ],
    description:
      "Casual adult female for natural conversations and customer support",
    gender: "female",
    tags: ["customer", "care", "line", "general american"],
  },
  {
    id: "39f753ef-b0eb-41cd-aa53-2f3c284f948f",
    name: "Emre",
    languages: ["tr-TR"],
    description: "Soothing male for calming dialogue",
    gender: "male",
    tags: ["calming", "speaker", "istanbul"],
  },
  {
    id: "32a806e8-894e-41ad-a4d5-6d9154d7b1e6",
    name: "Erik",
    languages: ["sv-SE"],
    description:
      "Relaxed and approachable adult male voice for casual conversations and natural everyday dialogue",
    gender: "male",
    tags: ["social", "speaker", "stockholm"],
  },
  {
    id: "8918ddfe-2ad4-4cc8-a573-e020ca13f3f5",
    name: "Erin",
    languages: ["en-US"],
    description:
      "Cheerful and optimistic adult female voice for upbeat conversations, advertisements, and positive customer interactions",
    gender: "female",
    tags: ["joyful", "guide", "general american"],
  },
  {
    id: "e97c3b37-1aa5-46af-afb7-9545086aaa92",
    name: "Eszter",
    languages: ["hu-HU"],
    description:
      "Clear and cheerful adult female voice for customer support and friendly interactions",
    gender: "female",
    tags: ["customer", "companion", "budapest"],
  },
  {
    id: "8281db18-6ac5-47bb-91a8-ce23a1f1d951",
    name: "Faiz",
    languages: ["ms-MY"],
    description:
      "Warm and fatherly adult male voice for casual conversations and comforting dialogue",
    gender: "male",
    tags: ["family", "guide", "malay"],
  },
  {
    id: "a01c369f-6d2d-4185-bc20-b32c225eab70",
    name: "Fiona",
    languages: ["en-GB"],
    description:
      "Chirpy and energetic British female voice with a bright tone, great for lively and engaging conversations",
    gender: "female",
    tags: ["witty", "woman", "british"],
  },
  {
    id: "d609f27f-f1a4-410f-85bb-10037b4fba99",
    name: "Francesca",
    languages: ["it-IT"],
    description: "Enunciating female for natural conversations",
    gender: "female",
    tags: ["elegant", "partner", "standard italian"],
  },
  {
    id: "6c6b05bf-ae5f-4013-82ab-7348e99ffdb2",
    name: "Freja",
    languages: ["sv-SE"],
    description: "Expressive female for clear communication",
    gender: "female",
    tags: ["nordic", "reader", "stockholm"],
  },
  {
    id: "62ae83ad-4f6a-430b-af41-a9bede9286ca",
    name: "Gemma",
    languages: ["en-GB", "hi-IN", "es-MX", "de-DE", "it-IT", "pt-BR"],
    description:
      "Confident, emotive British female for professional assistance",
    gender: "female",
    tags: ["decisive", "agent", "british"],
  },
  {
    id: "029c3c7a-b6d9-44f0-814b-200d849830ff",
    name: "Giancarlo",
    languages: ["it-IT"],
    description: "Deep male for conversational support",
    gender: "male",
    tags: ["support", "leader", "standard italian"],
  },
  {
    id: "88b329db-85d7-47cc-a5c5-98225a756721",
    name: "Giuseppe",
    languages: ["it-IT"],
    description:
      "Vintage-style adult male voice with a nostalgic old-radio tone for historical reenactments, period storytelling, and retro-style media",
    gender: "male",
    tags: ["retro", "man", "abruzzo italian"],
  },
  {
    id: "d46abd1d-2d02-43e8-819f-51fb652c1c61",
    name: "Grant",
    languages: ["en-US"],
    description:
      "Reliable, clear male voice with neutral American accent for customer support interactions",
    gender: "male",
    tags: ["friendly", "support", "general american"],
  },
  {
    id: "a0e99841-438c-4a64-b679-ae501e7d6091",
    name: "Greg",
    languages: ["en-US"],
    description: "Neutral, deep male for conversational support",
    gender: "male",
    tags: ["supporter", "general american"],
  },
  {
    id: "c99d36f3-5ffd-4253-803a-535c1bc9c306",
    name: "Griffin",
    languages: ["en-GB"],
    description: "Elderly male for narrations",
    gender: "male",
    tags: ["narrator", "british"],
  },
  {
    id: "34d923aa-c3b5-4f21-aac7-2c1f12730d4b",
    name: "Griffin",
    languages: ["en-GB"],
    description: "Elderly male for narrations",
    gender: "male",
    tags: ["excited", "narrator", "british"],
  },
  {
    id: "8bacd442-a107-4ec1-b6f1-2fcb3f6f4d56",
    name: "Gurpreet",
    languages: ["pa-IN"],
    description:
      "Soft and caring adult male voice for empathetic conversations, support, and reassuring dialogue",
    gender: "male",
    tags: ["companion", "powadhi"],
  },
  {
    id: "16212f18-4955-4be9-a6cd-2196ce2c11d1",
    name: "Hao",
    languages: ["zh-CN"],
    description:
      "Warm and friendly adult male voice for approachable conversations, customer support, and casual dialogue",
    gender: "male",
    tags: ["friendly", "guy", "mandarin"],
  },
  {
    id: "b042270c-d46f-4d4f-8fb0-7dd7c5fe5615",
    name: "Hector",
    languages: ["es-ES"],
    description:
      "Energetic and captivating male with a bright Castilian accent for providing instructions",
    gender: "male",
    tags: ["tour", "leader", "castilian"],
  },
  {
    id: "65c34eec-42c9-4a75-a8bd-b676fb847b72",
    name: "Helmi",
    languages: ["fi-FI"],
    description:
      "Friendly adult female voice for casual conversations and everyday chat",
    gender: "female",
    tags: ["warm", "friend", "finnish"],
  },
  {
    id: "87286a8d-7ea7-4235-a41a-dd9fa6630feb",
    name: "Henry",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "ar-SA",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
    ],
    description:
      "A relaxed, youthful male voice with a monotone, matter-of-fact attitude - ideal for casual, straightforward conversations.",
    gender: "male",
    tags: ["plainspoken", "guy", "general american"],
  },
  {
    id: "0d42f0f6-c019-4082-b250-1c16133d1c82",
    name: "Howard",
    languages: ["en-US"],
    description:
      "Male adult voice with a clear, approachable tone and steady delivery",
    gender: "male",
    tags: ["approachable", "man", "general american"],
  },
  {
    id: "7a5d4663-88ae-47b7-808e-8f9b9ee4127b",
    name: "Hua",
    languages: ["zh-CN"],
    description:
      "Upbeat, happy young adult woman for engaging conversations and conversational support",
    gender: "female",
    tags: ["sunny", "support", "mandarin"],
  },
  {
    id: "1463a4e1-56a1-4b41-b257-728d56e93605",
    name: "Hugo",
    languages: ["en-GB"],
    description:
      "Expressive, young adult male for characters and natural conversation",
    gender: "male",
    tags: ["teatime", "friend", "british"],
  },
  {
    id: "bdab08ad-4137-4548-b9db-6142854c7525",
    name: "Imran",
    languages: ["hi-IN"],
    description: "Bollywood male artist for serious roles",
    gender: "male",
    tags: ["hindi", "film", "actor", "standard hindi"],
  },
  {
    id: "f852eb8d-a177-48cd-bf63-7e4dcab61a36",
    name: "Ingrid",
    languages: ["sv-SE"],
    description: "Serene female for relaxing narrations",
    gender: "female",
    tags: ["peaceful", "guide", "stockholm"],
  },
  {
    id: "642014de-c0e3-4133-adc0-36b5309c23e6",
    name: "Irina",
    languages: ["ru-RU"],
    description: "Graceful female for narrations and audiobooks",
    gender: "female",
    tags: ["poetic", "voice", "russian"],
  },
  {
    id: "c0c374aa-09be-42d9-9828-4d2d7df86962",
    name: "Isabel",
    languages: [
      "es-ES",
      "hi-IN",
      "ar-SA",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description:
      "Smooth and approachable female with a gentle Castilian accent for guidance and teaching",
    gender: "female",
    tags: ["teacher", "castilian"],
  },
  {
    id: "f39bf583-3b3d-402f-9ffb-6179d9ec3e35",
    name: "Isabel",
    languages: ["pt-PT"],
    description:
      "Confident, clear, and firm adult female voice for giving instructions, guidance, and professional communication",
    gender: "female",
    tags: ["confident", "woman", "european portuguese"],
  },
  {
    id: "fd2ada67-c2d9-4afe-b474-6386b87d8fc3",
    name: "Ishan",
    languages: ["hi-IN"],
    description: "Conversational male for Hinglish sales and customer support",
    gender: "male",
    tags: ["ally", "standard hindi"],
  },
  {
    id: "fcbecbcc-0cef-4615-8b5a-712fe1b39dd0",
    name: "Ivana",
    languages: ["bg-BG"],
    description:
      "Clear and authoritative adult female voice for giving instructions and professional communication",
    gender: "female",
    tags: ["instruction", "provider", "bulgarian"],
  },
  {
    id: "9626c31c-bec5-4cca-baa8-f8ba9e84c8bc",
    name: "Jacqueline",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description: "Confident, young adult female for empathic customer support",
    gender: "female",
    tags: ["reassuring", "agent", "general american"],
  },
  {
    id: "729651dc-c6c3-4ee5-97fa-350da1f88600",
    name: "Jake",
    languages: ["en-US"],
    description:
      "Friendly, young adult male for welcoming and engaging conversations",
    gender: "male",
    tags: ["sidekick", "general american"],
  },
  {
    id: "2a3503b2-b6b6-4534-a224-e8c0679cec4a",
    name: "Jakub",
    languages: ["pl-PL"],
    description: "Clear male for narrations",
    gender: "male",
    tags: ["gentle", "guide", "polish"],
  },
  {
    id: "42b39f37-515f-4eee-8546-73e841679c1d",
    name: "James",
    languages: ["en-US"],
    description:
      "Very deep, authoritative male for providing guidance and instruction",
    gender: "male",
    tags: ["navigator", "general american"],
  },
  {
    id: "a5136bf9-224c-4d76-b823-52bd5efcffcc",
    name: "Jameson",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "ar-SA",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description:
      "Friendly, laid-back male voice for customer support and onboarding",
    gender: "male",
    tags: ["easygoing", "support", "general american"],
  },
  {
    id: "bdc4a3ce-2e22-4398-8cd6-76b7160d2298",
    name: "Jana",
    languages: ["cs-CZ"],
    description:
      "Clear and crisp female voice with a casual yet commanding tone for customer support and guidance",
    gender: "female",
    tags: ["crisp", "conversationalist", "czech"],
  },
  {
    id: "58fbaf73-d7de-4e82-a6b3-118180e7057c",
    name: "Janet",
    languages: ["en-US"],
    description:
      "Bright, warm female voice for guidance, narration, and supportive interactions",
    gender: "female",
    tags: ["sunny", "speaker", "general american"],
  },
  {
    id: "7ea5e9c2-b719-4dc3-b870-5ba5f14d31d8",
    name: "Janvi",
    languages: ["en-IN"],
    description:
      "Calm and neutral female voice with a slow, steady delivery, ideal for customer support scenarios",
    gender: "female",
    tags: ["steady", "agent", "indian english"],
  },
  {
    id: "3faa81ae-d3d8-4ab1-9e44-e50e46d33c30",
    name: "Jasper",
    languages: ["en-GB"],
    description:
      "Warm, expressive voice for customer support and sales conversations",
    gender: "male",
    tags: ["service", "specialist", "british"],
  },
  {
    id: "991c62ce-631f-48b0-8060-2a0ebecbd15b",
    name: "Jaspreet",
    languages: ["pa-IN"],
    description:
      "Expressive adult female voice with an engaging tone for commercials, promotions, and lively announcements",
    gender: "female",
    tags: ["commercial", "woman", "powadhi"],
  },
  {
    id: "e9f0368b-3662-4a01-b037-e13ca5203c74",
    name: "Javier",
    languages: ["es-BO"],
    description:
      "Approachable adult male voice for casual conversations and natural dialogue",
    gender: "male",
    tags: ["gentle", "advisor", "camba"],
  },
  {
    id: "f39d8500-0d9b-4b8b-a080-38f5188f5892",
    name: "Jewel",
    languages: ["en-US"],
    description:
      "Smooth, confident, and engaging female voice for advertising, promos, and high-impact brand messaging",
    gender: "female",
    tags: ["commercial", "announcer", "general american"],
  },
  {
    id: "304fdbd8-65e6-40d6-ab78-f9d18b9efdf9",
    name: "Jihyun",
    languages: ["ko-KR"],
    description: "Relaxing female for narrations and announcements",
    gender: "female",
    tags: ["anchorwoman", "korean"],
  },
  {
    id: "15628352-2ede-4f1b-89e6-ceda0c983fbc",
    name: "Jiwoo",
    languages: ["ko-KR"],
    description:
      "Professional and polite adult female voice for customer service, support, and clear communication",
    gender: "female",
    tags: ["service", "specialist", "korean"],
  },
  {
    id: "5abd2130-146a-41b1-bcdb-974ea8e19f56",
    name: "Jo",
    languages: ["en-US"],
    description: "Young adult female for casual conversations",
    gender: "female",
    tags: ["gal", "general american"],
  },
  {
    id: "c9440d34-5641-427b-bbb7-80ef7462576d",
    name: "Joan",
    languages: ["en-US"],
    description: "Young adult female for casual conversations",
    gender: "female",
    tags: ["messenger", "general american"],
  },
  {
    id: "34575e71-908f-4ab6-ab54-b08c95d6597d",
    name: "Joey",
    languages: ["en-US"],
    description: "Casual, friendly male for natural conversations",
    gender: "male",
    tags: ["neighborhood", "guy", "new york"],
  },
  {
    id: "87bc56aa-ab01-4baa-9071-77d497064686",
    name: "Jordan",
    languages: ["en-US"],
    description: "Welcoming adult male for engaging conversations",
    gender: "male",
    tags: ["chill", "pal", "general american"],
  },
  {
    id: "eda5bbff-1ff1-4886-8ef1-4e69a77640a0",
    name: "Kai",
    languages: ["zh-CN"],
    description: "Deep, friendly adult male for commercials and advertising",
    gender: "male",
    tags: ["commercial", "man", "mandarin"],
  },
  {
    id: "3f4ade23-6eb4-4279-ab05-6a144947c4d5",
    name: "Karin",
    languages: ["de-DE"],
    description: "Friendly female for casual conversations",
    gender: "female",
    tags: ["companion", "standard german"],
  },
  {
    id: "ea7b5eee-39d9-40b0-b241-1910cbca9c62",
    name: "Kasia",
    languages: ["pl-PL"],
    description:
      "Approachable adult female voice with a natural and casual tone for everyday conversations and friendly dialogue",
    gender: "female",
    tags: ["natural", "conversationalist", "polish"],
  },
  {
    id: "abf68668-6549-462c-8426-1fa7b466b91d",
    name: "Katarina",
    languages: ["sk-SK"],
    description:
      "Warm and approachable adult female voice for customer service, support, and friendly communication",
    gender: "female",
    tags: ["friendly", "sales", "slovak"],
  },
  {
    id: "575a5d29-1fdc-4d4e-9afa-5a9a71759864",
    name: "Katarzyna",
    languages: ["pl-PL"],
    description: "Melodic female for storytelling",
    gender: "female",
    tags: ["melodic", "storyteller", "polish"],
  },
  {
    id: "f786b574-daa5-4673-aa0c-cbe3e8534c02",
    name: "Katie",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "zh-CN",
    ],
    description:
      "Enunciating young adult female for conversational support use cases",
    gender: "female",
    tags: ["friendly", "fixer", "general american"],
  },
  {
    id: "c323c793-41f9-47b8-99dc-9b44b0440b84",
    name: "Katrine",
    languages: ["da-DK"],
    description:
      "Soft and calm adult female voice for meditation, relaxation, and gentle conversations",
    gender: "female",
    tags: ["calm", "caregiver", "danish"],
  },
  {
    id: "9fa83ce3-c3a8-4523-accc-173904582ced",
    name: "Keith",
    languages: ["en-US"],
    description: "Chill, young adult male for casual conversations",
    gender: "male",
    tags: ["easygoing", "friend", "general american"],
  },
  {
    id: "6b92f628-be90-497c-8f4c-3b035002df71",
    name: "Kenji",
    languages: ["ja-JP"],
    description:
      "Calm, deep male for news narration and formal customer service",
    gender: "male",
    tags: ["calm", "man", "standard japanese"],
  },
  {
    id: "f8f5f1b2-f02d-4d8e-a40d-fd850a487b3d",
    name: "Kiara",
    languages: ["en-IN"],
    description:
      "Upbeat, enunciating Indian accented mature adult female for happy conversations",
    gender: "female",
    tags: ["joyful", "woman", "indian english"],
  },
  {
    id: "57dcab65-68ac-45a6-8480-6c4c52ec1cd1",
    name: "Kira",
    languages: ["en-US"],
    description: "Emotive, young adult female for empathetic conversations",
    gender: "female",
    tags: ["trusted", "confidant", "general american"],
  },
  {
    id: "c63361f8-d142-4c62-8da7-8f8149d973d6",
    name: "Krishna",
    languages: ["en-IN"],
    description:
      "Easygoing adult male voice with a slight Indian accent for casual conversations, approachable dialogue, and friendly interactions",
    gender: "male",
    tags: ["friendly", "pal", "indian english"],
  },
  {
    id: "bf32f849-7bc9-4b91-8c62-954588efcc30",
    name: "Lan",
    languages: ["zh-CN"],
    description:
      "Firm, neutral adult woman for providing guidance and instruction",
    gender: "female",
    tags: ["instructor", "mandarin"],
  },
  {
    id: "b426013c-002b-4e89-8874-8cd20b68373a",
    name: "Latha",
    languages: ["ml-IN"],
    description:
      "Bright and clear adult female voice for customer support, greetings, and welcoming guests",
    gender: "female",
    tags: ["friendly", "host", "north kerala"],
  },
  {
    id: "1ade29fc-6b82-4607-9e70-361720139b12",
    name: "Lea",
    languages: ["de-DE"],
    description: "Smooth female for casual conversations",
    gender: "female",
    tags: ["breezy", "voice", "standard german"],
  },
  {
    id: "4ab1ff51-476d-42bb-8019-4d315f7c0c05",
    name: "Lena",
    languages: ["de-DE"],
    description: "Cool German female for clear communication and audiobooks",
    gender: "female",
    tags: ["muse", "standard german"],
  },
  {
    id: "dbebd077-80cb-4bcf-b43b-4552f96341bb",
    name: "Levan",
    languages: ["ka-GE"],
    description:
      "Casual and approachable adult male voice for customer support and everyday conversations",
    gender: "male",
    tags: ["support", "guide", "tbilisi"],
  },
  {
    id: "56b87df1-594d-4135-992c-1112bb504c59",
    name: "Lexi",
    languages: ["en-US"],
    description:
      "Cheery, young female for entertainment, media, and gaming use cases",
    gender: "female",
    tags: ["fun", "friend", "general american"],
  },
  {
    id: "fa7bfcdc-603c-4bf1-a600-a371400d2f8c",
    name: "Leyla",
    languages: ["tr-TR"],
    description: "Expressive female for conversational support",
    gender: "female",
    tags: ["story", "companion", "istanbul"],
  },
  {
    id: "41f3c367-e0a8-4a85-89e0-c27bae9c9b6d",
    name: "Liam",
    languages: ["en-AU"],
    description:
      "Casual, friendly young male for authentic and engaging conversations",
    gender: "male",
    tags: ["guy", "next", "door", "australian"],
  },
  {
    id: "4af7c703-f2a9-45dd-a7fd-724cf7efc371",
    name: "Lila",
    languages: ["en-US"],
    description: "Melodic female for gentle and empathetic conversations",
    gender: "female",
    tags: ["meditation", "guide", "general american"],
  },
  {
    id: "829ccd10-f8b3-43cd-b8a0-4aeaa81f3b30",
    name: "Linda",
    languages: ["en-US"],
    description: "Clear, confident mature female for conversational use cases",
    gender: "female",
    tags: ["conversational", "guide", "general american"],
  },
  {
    id: "a38e4e85-e815-43ab-acf1-907c4688dd6c",
    name: "Lindsey",
    languages: ["en-US"],
    description:
      "Happy adult female with a laidback affect for casual conversations and customer support",
    gender: "female",
    tags: ["relaxed", "rep", "general american"],
  },
  {
    id: "653b9445-ae0c-4312-a3ce-375504cff31e",
    name: "Liu",
    languages: ["zh-CN"],
    description:
      "Casual, neutral adult man for conversational support use cases",
    gender: "male",
    tags: ["plain", "talker", "mandarin"],
  },
  {
    id: "d718e944-b313-4998-b011-d1cc078d4ef3",
    name: "Liv",
    languages: ["it-IT"],
    description: "Casual female for natural conversations",
    gender: "female",
    tags: ["casual", "friend", "standard italian"],
  },
  {
    id: "57c63422-d911-4666-815b-0c332e4d7d6a",
    name: "Lori",
    languages: ["en-AU"],
    description:
      "Female with clear enunciation for upbeat, emotive conversations",
    gender: "female",
    tags: ["cheerleader", "australian"],
  },
  {
    id: "700d1ee3-a641-4018-ba6e-899dcadc9e2b",
    name: "Luana",
    languages: ["pt-BR"],
    description: "Pleasant, clear female for casual conversation",
    gender: "female",
    tags: ["public", "speaker", "brazilian portuguese"],
  },
  {
    id: "e019ed7e-6079-4467-bc7f-b599a5dccf6f",
    name: "Luca",
    languages: ["it-IT"],
    description: "Casual male for natural conversations",
    gender: "male",
    tags: ["everyday", "friend", "standard italian"],
  },
  {
    id: "af482421-80f4-4379-b00c-a118def29cde",
    name: "Lucas",
    languages: ["nl-NL"],
    description: "Enunciating male for storytelling",
    gender: "male",
    tags: ["storyteller", "randstad"],
  },
  {
    id: "b5aa8098-49ef-475d-89b0-c9262ecf33fd",
    name: "Luis",
    languages: ["es-ES"],
    description:
      "Clear and distinctive male with a refined Castilian accent for clear communication",
    gender: "male",
    tags: ["news", "caster", "castilian"],
  },
  {
    id: "e00dd3df-19e7-4cd4-827a-7ff6687b6954",
    name: "Lukas",
    languages: ["de-DE"],
    description: "Confident male for phone systems and customer support",
    gender: "male",
    tags: ["professional", "standard german"],
  },
  {
    id: "7b2c0a2e-3dd3-4a44-b16b-26ecd8134279",
    name: "Luke",
    languages: ["en-US"],
    description: "Seasoned male voice for casual, authentic conversations",
    gender: "male",
    tags: ["broadway", "voice", "new york"],
  },
  {
    id: "e13cae5c-ec59-4f71-b0a6-266df3c9bb8e",
    name: "Lulu",
    languages: ["en-US"],
    description: "Squeaky, young female for media and entertainment for kids",
    gender: "female",
    tags: ["madame", "mischief", "general american"],
  },
  {
    id: "02fe5732-a072-4767-83e3-a91d41d274ca",
    name: "Madison",
    languages: ["en-US"],
    description: "Enthusiastic, young adult female for emotive discussions",
    gender: "female",
    tags: ["best", "friend", "general american"],
  },
  {
    id: "79693aee-1207-4771-a01e-20c393c89e6f",
    name: "Marco",
    languages: ["it-IT"],
    description: "Friendly and professional male for conversational support",
    gender: "male",
    tags: ["friendly", "conversationalist", "standard italian"],
  },
  {
    id: "5619d38c-cf51-4d8e-9575-48f61a280413",
    name: "Mark",
    languages: ["en-US"],
    description:
      "Deep, confident male voice with strong presence - ideal for commercials, promos, and broadcast narration",
    gender: "male",
    tags: ["promotion", "lead", "general american"],
  },
  {
    id: "5c42302c-194b-4d0c-ba1a-8cb485c84ab9",
    name: "Mary",
    languages: ["en-US"],
    description:
      "Mature adult female for instructional videos and empathetic conversations",
    gender: "female",
    tags: ["nurse", "general american"],
  },
  {
    id: "bfd3644b-d561-4b1c-a01f-d9af98cb67c0",
    name: "Matt",
    languages: ["en-US"],
    description:
      "High pitched, silly male for fun characters and entertainment use cases",
    gender: "male",
    tags: ["goofy", "friend", "general american"],
  },
  {
    id: "408daed0-c597-4c27-aae8-fa0497d644bf",
    name: "Matteo",
    languages: ["it-IT"],
    description: "Reassuring male for soothing dialogue",
    gender: "male",
    tags: ["gentle", "narrator", "standard italian"],
  },
  {
    id: "a53c3509-ec3f-425c-a223-977f5f7424dd",
    name: "Mei",
    languages: ["zh-CN"],
    description:
      "Expressive adult female voice with a lively and engaging tone for storytelling, advertisements, and animated dialogue",
    gender: "female",
    tags: ["expressive", "assistant", "mandarin"],
  },
  {
    id: "ae1a833b-0d95-4b7f-8d05-d6418c6f8049",
    name: "Mikko",
    languages: ["fi-FI"],
    description:
      "Firm and strong adult male voice for narration, audiobooks, and authoritative communication",
    gender: "male",
    tags: ["narration", "expert", "finnish"],
  },
  {
    id: "f114a467-c40a-4db8-964d-aaba89cd08fa",
    name: "Miles",
    languages: ["en-GB"],
    description: "Deep, soothing mature male for providing guidance",
    gender: "male",
    tags: ["yogi", "british"],
  },
  {
    id: "0e58d60a-2f1a-4252-81bd-3db6af45fb41",
    name: "Minh",
    languages: ["vi-VN"],
    description:
      "Easygoing adult male voice with a friendly tone for light conversation, casual dialogue, and everyday chat",
    gender: "male",
    tags: ["conversational", "partner", "central vietnamese"],
  },
  {
    id: "03b1c65d-4b7f-4c09-91a8-e2f6f78cb2c9",
    name: "Molly",
    languages: ["en-US"],
    description:
      "Bright and cheerful American-accented female voice for upbeat conversations, advertisements, and lively interactions",
    gender: "female",
    tags: ["upbeat", "conversationalist", "general american"],
  },
  {
    id: "1b4ea5fb-b1c0-43ee-a7be-4e315878c2b1",
    name: "Monica",
    languages: ["en-US"],
    description:
      "English female adult voice with rich emotional range and expressive delivery",
    gender: "female",
    tags: ["emotive", "voice", "general american"],
  },
  {
    id: "5a31e4fb-f823-4359-aa91-82c0ae9a991c",
    name: "Murat",
    languages: ["tr-TR"],
    description: "Deep male for narrations and audiobooks",
    gender: "male",
    tags: ["anatolian", "storyteller", "istanbul"],
  },
  {
    id: "779673f3-895f-4935-b6b5-b031dc78b319",
    name: "Natalya",
    languages: ["ru-RU"],
    description: "Serene female for relaxing audio",
    gender: "female",
    tags: ["soothing", "guide", "russian"],
  },
  {
    id: "e2d08065-b658-466b-ad52-cef8ee21d307",
    name: "Natasha",
    languages: ["en-US"],
    description:
      "English female adult voice with a lively, upbeat tone for energetic conversations",
    gender: "female",
    tags: ["upbeat", "guide", "general american"],
  },
  {
    id: "9b953e7b-86a8-42f0-b625-1434fb15392b",
    name: "Neeraj",
    languages: ["hi-IN"],
    description:
      "Deep male for excellent storytelling and providing instructions",
    gender: "male",
    tags: ["tour", "guide", "standard hindi"],
  },
  {
    id: "afa425cf-5489-4a09-8a3f-d3cb1f82150d",
    name: "Nico",
    languages: ["de-DE"],
    description: "Casual male for phone calls and conversational agents",
    gender: "male",
    tags: ["friendly", "agent", "standard german"],
  },
  {
    id: "b45eba5b-2215-4da7-9c7c-121c95ed7b81",
    name: "Nikos",
    languages: ["el-GR"],
    description:
      "Nostalgic, middle-aged male voice with an old-radio tone for historical reenactments, vintage ads, or period storytelling",
    gender: "male",
    tags: ["radio", "storyteller", "thessaloniki"],
  },
  {
    id: "3e32f3c5-9ac0-4192-9994-87fdb277120f",
    name: "Noam",
    languages: ["he-IL"],
    description:
      "Clear and authoritative adult male voice for announcements, broadcasts, and formal presentations",
    gender: "male",
    tags: ["broadcaster", "israeli"],
  },
  {
    id: "05ffab9c-d380-4909-8375-cd12f59238c3",
    name: "Oleh",
    languages: ["uk-UA"],
    description:
      "Approachable adult male voice with a professional tone for casual conversations and everyday interactions",
    gender: "male",
    tags: ["professional", "guy", "kyiv"],
  },
  {
    id: "ee7ea9f8-c0c1-498c-9279-764d6b56d189",
    name: "Oliver",
    languages: ["en-GB"],
    description: "Polite, young adult male for customer facing use cases",
    gender: "male",
    tags: ["customer", "chap", "british"],
  },
  {
    id: "f31cc6a7-c1e8-4764-980c-60a361443dd1",
    name: "Olivia",
    languages: ["en-AU"],
    description: "Friendly, happy adult female for engaging conversations",
    gender: "female",
    tags: ["sunny", "woman", "australian"],
  },
  {
    id: "e3087ad8-7018-4154-9a87-11577f916cd4",
    name: "Omar",
    languages: ["ar-SA"],
    description:
      "Lively, energetic adult male for engaging conversations and dynamic narration",
    gender: "male",
    tags: ["high-energy", "presenter", "modern standard arabic"],
  },
  {
    id: "28ca2041-5dda-42df-8123-f58ea9c3da00",
    name: "Palak",
    languages: ["hi-IN"],
    description:
      "Friendly female with a slight English accent for teaching use cases",
    gender: "female",
    tags: ["presenter", "standard hindi"],
  },
  {
    id: "d4db5fb9-f44b-4bd1-85fa-192e0f0d75f9",
    name: "Paloma",
    languages: [
      "es-ES",
      "en-GB",
      "de-DE",
      "fr-CA",
      "he-IL",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description:
      "Clear and professional adult woman for reports, public speaking and customer assistance",
    gender: "female",
    tags: ["clear", "presenter", "woman", "castilian"],
  },
  {
    id: "bec003e2-3cb3-429c-8468-206a393c67ad",
    name: "Parvati",
    languages: ["hi-IN"],
    description: "Friendly female for customer support use cases",
    gender: "female",
    tags: ["friendly", "supporter", "standard hindi"],
  },
  {
    id: "3e1ed423-17e5-4773-b87c-25b031106e41",
    name: "Paul",
    languages: ["en-AU"],
    description:
      "Deep and firm male voice with a relaxed, conversational delivery",
    gender: "male",
    tags: ["straight", "talker", "australian"],
  },
  {
    id: "15d0c2e2-8d29-44c3-be23-d585d5f154a1",
    name: "Pedro",
    languages: ["es-MX"],
    description:
      "Formal and steady Mexican adult for clear and concise exchanges of information",
    gender: "male",
    tags: ["formal", "speaker", "mexican"],
  },
  {
    id: "ca590fdc-df56-4d2e-94a4-ef5b423c7ddf",
    name: "Peter",
    languages: ["sk-SK"],
    description:
      "Steady and articulate adult male voice for narrations, audiobooks, and professional storytelling",
    gender: "male",
    tags: ["narrator", "man", "slovak"],
  },
  {
    id: "89266bab-6e15-455d-8654-e18c440b0656",
    name: "Petr",
    languages: ["cs-CZ"],
    description:
      "Resonant adult male voice, reminiscent of a priest delivering a sermon for narrations and formal reading",
    gender: "male",
    tags: ["pastor", "czech"],
  },
  {
    id: "3d335974-4c4a-400a-84dc-ebf4b73aada6",
    name: "Piotr",
    languages: ["pl-PL"],
    description: "Confident male for providing instructions",
    gender: "male",
    tags: ["corporate", "lead", "polish"],
  },
  {
    id: "59ba7dee-8f9a-432f-a6c0-ffb33666b654",
    name: "Pooja",
    languages: ["bn-BD"],
    description:
      "Soft-spoken adult female voice for casual conversations and natural dialogue",
    gender: "female",
    tags: ["everyday", "assistant", "jessore"],
  },
  {
    id: "f6141af3-5f94-418c-80ed-a45d450e7e2e",
    name: "Priya",
    languages: ["en-IN"],
    description: "Authoritative, adult female for customer support",
    gender: "female",
    tags: ["trusted", "operator", "indian english"],
  },
  {
    id: "393dd459-f8d8-4c3e-a86b-ec43a1113d0b",
    name: "Rahul",
    languages: [
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "it-IT",
      "pt-BR",
      "te-IN",
      "zh-CN",
    ],
    description:
      "Approachable adult male voice for casual conversations and everyday interactions",
    gender: "male",
    tags: ["calm", "office", "guy", "bagheli"],
  },
  {
    id: "565510e8-6b45-45de-8758-13588fbaec73",
    name: "Ray",
    languages: ["en-US"],
    description:
      "Approachable male voice with a laid-back, natural delivery for everyday conversations",
    gender: "male",
    tags: ["conversationalist", "midwestern american"],
  },
  {
    id: "57b6bf63-c7a1-4ffc-8e10-23bf45152dd6",
    name: "Rebecca",
    languages: ["en-US"],
    description:
      "Soft-spoken, empathetic female voice suited for thoughtful, calming dialogue",
    gender: "female",
    tags: ["counselor", "general american"],
  },
  {
    id: "c2ac25f9-ecc4-4f56-9095-651354df60c0",
    name: "Renee",
    languages: ["en-US"],
    description: "Firm adult female fit for broadcasts and narrations",
    gender: "female",
    tags: ["commander", "general american"],
  },
  {
    id: "21b81c14-f85b-436d-aff5-43f2e788ecf8",
    name: "Riley",
    languages: ["en-US"],
    description:
      "Casual, young female for authentic and everyday conversations",
    gender: "female",
    tags: ["chill", "friend", "california"],
  },
  {
    id: "faf0731e-dfb9-4cfc-8119-259a79b27e12",
    name: "Riya",
    languages: ["hi-IN"],
    description: "Friendly woman for playful conversations",
    gender: "female",
    tags: ["college", "roommate", "standard hindi"],
  },
  {
    id: "8985388c-1332-4ce7-8d55-789628aa3df4",
    name: "Robyn",
    languages: ["en-AU"],
    description: "Neutral, mature female for narrations",
    gender: "female",
    tags: ["storycrafter", "australian"],
  },
  {
    id: "5ee9feff-1265-424a-9d7f-8e4d431a12c7",
    name: "Ronald",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "zh-CN",
    ],
    description: "Intense, deep young adult male for casual conversations",
    gender: "male",
    tags: ["thinker", "general american"],
  },
  {
    id: "701a96e1-7fdd-4a6c-a81e-a4a450403599",
    name: "Rowan",
    languages: ["en-US"],
    description: "Confident male for narrations",
    gender: "male",
    tags: ["team", "leader", "general american"],
  },
  {
    id: "11af83e2-23eb-452f-956e-7fee218ccb5c",
    name: "Ruth",
    languages: ["en-US"],
    description: "Firm, authoritative female for providing guidance",
    gender: "female",
    tags: ["manager", "midwestern american"],
  },
  {
    id: "6d4b1416-8d54-4d94-a788-8a802c086544",
    name: "Sabine",
    languages: ["de-DE"],
    description:
      "Soft yet commanding adult female voice for customer support, clear communication, and giving instructions",
    gender: "female",
    tags: ["firm", "newscaster", "standard german"],
  },
  {
    id: "f4e8781b-a420-4080-81cf-576331238efa",
    name: "Samantha",
    languages: ["en-US"],
    description: "Firm, confident adult female for conversational support",
    gender: "female",
    tags: ["support", "leader", "general american"],
  },
  {
    id: "5e10a334-7fa5-46d4-a64b-5ae6185da3fd",
    name: "Samantha",
    languages: ["en-US"],
    description: "Firm, confident adult female for conversational support",
    gender: "female",
    tags: ["sad", "support", "leader", "general american"],
  },
  {
    id: "761afc95-bef5-44dd-aa07-d3c678912e43",
    name: "Samantha",
    languages: ["en-US"],
    description: "Firm, confident adult female for conversational support",
    gender: "female",
    tags: ["happy", "support", "leader", "general american"],
  },
  {
    id: "d3e03deb-5439-4203-add1-ca9a7501eaa7",
    name: "Samantha",
    languages: ["en-US"],
    description: "Firm, confident adult female for conversational support",
    gender: "female",
    tags: ["yelling", "support", "leader", "general american"],
  },
  {
    id: "04bfd756-4fd4-42c2-9ccf-37f647c5bf54",
    name: "Samantha",
    languages: ["en-US"],
    description: "Firm, confident adult female for conversational support",
    gender: "female",
    tags: ["angry", "support", "leader", "general american"],
  },
  {
    id: "638efaaa-4d0c-442e-b701-3fae16aad012",
    name: "Sameer",
    languages: ["en-IN"],
    description: "Friendly male for customer support use cases",
    gender: "male",
    tags: ["problem", "solver", "indian english"],
  },
  {
    id: "0eb213fe-4658-45bc-9442-33a48b24b133",
    name: "Sanne",
    languages: ["nl-NL"],
    description: "Cheerful female for engaging conversations",
    gender: "female",
    tags: ["clear", "companion", "randstad"],
  },
  {
    id: "694f9389-aac1-45b6-b726-9d9369183238",
    name: "Sarah",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "te-IN",
      "zh-CN",
    ],
    description: "Soothing female for meditations and calming conversations",
    gender: "female",
    tags: ["mindful", "woman", "general american"],
  },
  {
    id: "78ab82d5-25be-4f7d-82b3-7ad64e5b85b2",
    name: "Savannah",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "ar-SA",
      "de-DE",
      "he-IL",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
    ],
    description: "Adult female for casual, authentic conservations",
    gender: "female",
    tags: ["magnolia", "belle", "southern us"],
  },
  {
    id: "2f22b9bc-b0eb-4cb6-b5ae-0c099a0fdfad",
    name: "Scott",
    languages: ["en-US"],
    description:
      "Energetic American adult male voice with the excitement of a sportscaster for live commentary, sports content, and high-energy announcements",
    gender: "male",
    tags: ["sportscaster", "general american"],
  },
  {
    id: "b7187e84-fe22-4344-ba4a-bc013fcb533e",
    name: "Sebastian",
    languages: [
      "de-DE",
      "hi-IN",
      "es-MX",
      "ar-SA",
      "fr-CA",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description: "Warm male for audiobooks and clear communication",
    gender: "male",
    tags: ["orator", "standard german"],
  },
  {
    id: "3ef78ba6-9aaa-46a2-b5b5-f9ded76a2370",
    name: "Serena",
    languages: ["en-US"],
    description:
      "Female adult voice with a relaxed, easygoing tone and laid-back delivery",
    gender: "female",
    tags: ["laidback", "girl", "general american"],
  },
  {
    id: "39b376fc-488e-4d0c-8b37-e00b72059fdd",
    name: "Sheldon",
    languages: ["en-US"],
    description: "Enunciating male for customer support use cases",
    gender: "male",
    tags: ["help", "desk", "man", "general american"],
  },
  {
    id: "f9a4b3a6-b44b-469f-90e3-c8e19bd30e99",
    name: "Shuwen",
    languages: ["zh-CN"],
    description: "Neutral, firm female for providing guidance and instruction",
    gender: "female",
    tags: ["precision", "guide", "mandarin"],
  },
  {
    id: "4e41a434-85fc-4614-b203-af79ba44d473",
    name: "Sienna",
    languages: ["en-US"],
    description:
      "Soft-spoken American-accented female voice with a motivating and reassuring tone for guidance, support, and uplifting conversations",
    gender: "female",
    tags: ["encourager", "general american"],
  },
  {
    id: "b7d50908-b17c-442d-ad8d-810c63997ed9",
    name: "Sierra",
    languages: ["en-US"],
    description: "Slow, chill young adult female for casual conversations",
    gender: "female",
    tags: ["california", "girl"],
  },
  {
    id: "7e19344f-9f17-47d7-a13a-4366ad06ebf3",
    name: "Silas",
    languages: ["en-US"],
    description:
      "Gentle and steady male voice with a nurturing tone for calm conversations and serene narration",
    gender: "male",
    tags: ["nighttime", "narrator", "general american"],
  },
  {
    id: "3b554273-4299-48b9-9aaf-eefd438e3941",
    name: "Simi",
    languages: ["en-IN"],
    description: "Firm, young accented female for customer support use cases",
    gender: "female",
    tags: ["support", "specialist", "indian english"],
  },
  {
    id: "07bc462a-c644-49f1-baf7-82d5599131be",
    name: "Sindhu",
    languages: [
      "te-IN",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "he-IL",
      "it-IT",
      "pt-BR",
      "ta-IN",
      "th-TH",
      "zh-CN",
    ],
    description:
      "Clear and natural adult female voice for casual conversations and everyday interactions",
    gender: "female",
    tags: ["conversational", "partner", "telangana"],
  },
  {
    id: "b441c4fd-4910-4c55-ae56-f0291057e2cc",
    name: "Siti",
    languages: ["id-ID", "en-US"],
    description:
      "Cheerful and optimistic adult female voice for brand placements, advertisements, and engaging storytelling",
    gender: "female",
    tags: ["narrator", "standard indonesian"],
  },
  {
    id: "db6b0ed5-d5d3-463d-ae85-518a07d3c2b4",
    name: "Skylar",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "he-IL",
      "it-IT",
      "pt-BR",
      "ta-IN",
    ],
    description:
      "Approachable American female ideal for customer care and support.",
    gender: "female",
    tags: ["friendly", "guide", "general american"],
  },
  {
    id: "5de076e9-7b28-4442-b279-e7d80d573505",
    name: "Somchai",
    languages: ["th-TH"],
    description:
      "Upbeat and confident adult male voice for commercials, brand promotions, and lively presentations",
    gender: "male",
    tags: ["star", "central thai"],
  },
  {
    id: "bf0a246a-8642-498a-9950-80c35e9276b5",
    name: "Sophie",
    languages: ["en-US"],
    description: "Mature female for natural conversations",
    gender: "female",
    tags: ["teacher", "general american"],
  },
  {
    id: "9fb269e7-70fe-4cbe-aa3f-28bdb67e3e84",
    name: "Steve",
    languages: ["en-US"],
    description: "Deep, firm adult male for narrations and voiceovers",
    gender: "male",
    tags: ["baritone", "african american"],
  },
  {
    id: "ccc7bb22-dcd0-42e4-822e-0731b950972f",
    name: "Suda",
    languages: ["th-TH"],
    description:
      "Expressive adult female voice with lively pronunciation for storytelling, advertisements, and engaging dialogue",
    gender: "female",
    tags: ["fortune", "teller", "central thai"],
  },
  {
    id: "be79f378-47fe-4f9c-b92b-f02cefa62ccf",
    name: "Sunil",
    languages: ["hi-IN"],
    description: "Deep male for serious conversations",
    gender: "male",
    tags: ["official", "announcer", "standard hindi"],
  },
  {
    id: "156fb8d2-335b-4950-9cb3-a2d33befec77",
    name: "Sunny",
    languages: ["en-US"],
    description: "Upbeat female for engaging conversations",
    gender: "female",
    tags: ["pep", "talker", "general american"],
  },
  {
    id: "f227bc18-3704-47fe-b759-8c78a450fdfa",
    name: "Suresh",
    languages: ["mr-IN"],
    description:
      "Clear and well-enunciated adult male voice for instructions, narrations, and professional communication",
    gender: "male",
    tags: ["instruction", "voice", "konkani"],
  },
  {
    id: "b8e1169c-f16a-4064-a6e0-95054169e553",
    name: "Takashi",
    languages: ["ja-JP"],
    description:
      "Serious adult male voice with a steady but approachable tone for casual conversations and professional dialogue",
    gender: "male",
    tags: ["professional", "conversationalist", "standard japanese"],
  },
  {
    id: "710feaa3-b550-42f3-b3eb-6f37f2a7cc0a",
    name: "Tanner",
    languages: ["en-US"],
    description: "English male adult voice with an upbeat and energetic tone",
    gender: "male",
    tags: ["upbeat", "assistant", "general american"],
  },
  {
    id: "c59c247b-6aa9-4ab6-91f9-9eabea7dc69e",
    name: "Tao",
    languages: ["zh-CN"],
    description:
      "Friendly young adult male for presentations and educational content",
    gender: "male",
    tags: ["lecturer", "mandarin"],
  },
  {
    id: "064b17af-d36b-4bfb-b003-be07dba1b649",
    name: "Tatiana",
    languages: ["ru-RU"],
    description: "Friendly female for audiobooks and clear communication",
    gender: "female",
    tags: ["friendly", "storyteller", "russian"],
  },
  {
    id: "c1cfee3d-532d-47f8-8dd2-8e5b2b66bf1d",
    name: "Taylan",
    languages: [
      "tr-TR",
      "hi-IN",
      "es-MX",
      "ar-SA",
      "de-DE",
      "fr-FR",
      "he-IL",
      "it-IT",
      "ja-JP",
      "pt-BR",
      "ta-IN",
      "te-IN",
      "th-TH",
      "zh-CN",
    ],
    description: "Versatile articulate male for storytelling",
    gender: "male",
    tags: ["expressive", "voice", "istanbul"],
  },
  {
    id: "79f8b5fb-2cc8-479a-80df-29f7a7cf1a3e",
    name: "Theo",
    languages: [
      "en-US",
      "hi-IN",
      "es-MX",
      "de-DE",
      "fr-CA",
      "it-IT",
      "pt-BR",
      "zh-CN",
    ],
    description: "Steady, enunciating, confident young male for narrations",
    gender: "male",
    tags: ["modern", "narrator", "general american"],
  },
  {
    id: "384b625b-da5d-49e8-a76d-a2855d4f31eb",
    name: "Thomas",
    languages: ["de-DE"],
    description: "Earnest male for conversations and customer support",
    gender: "male",
    tags: ["anchor", "standard german"],
  },
  {
    id: "6a360542-a117-4ed5-9e09-e8bf9b05eabb",
    name: "Tiago",
    languages: ["pt-PT"],
    description: "Calm, clear male for narrations",
    gender: "male",
    tags: ["narration", "expert", "european portuguese"],
  },
  {
    id: "146485fd-8736-41c7-88a8-7cdd0da34d84",
    name: "Tim",
    languages: ["en-US"],
    description: "Nasal-y male for casual conversations",
    gender: "male",
    tags: ["pal", "general american"],
  },
  {
    id: "91b4cf29-5166-44eb-8054-30d40ecc8081",
    name: "Tina",
    languages: ["en-US"],
    description:
      "Natural, firm adult female for authentic conversation and customer support",
    gender: "female",
    tags: ["customer", "ally", "general american"],
  },
  {
    id: "efd255c7-f030-43d3-b5d8-c7b72063be70",
    name: "Todd",
    languages: ["en-US"],
    description:
      "English male adult voice with a direct, matter-of-fact delivery",
    gender: "male",
    tags: ["matter", "fact", "salesman", "general american"],
  },
  {
    id: "40104aff-a015-4da1-9912-af950fbec99e",
    name: "Travis",
    languages: ["en-US"],
    description:
      "Firm, young male for instructional videos and customer support",
    gender: "male",
    tags: ["how", "guide", "southern us"],
  },
  {
    id: "c45bc5ec-dc68-4feb-8829-6e6b2748095d",
    name: "Trevor",
    languages: ["en-GB"],
    description:
      "Deep, elderly male for narrations and entertainment use cases",
    gender: "male",
    tags: ["movieman", "british"],
  },
  {
    id: "726d5ae5-055f-4c3d-8355-d9677de68937",
    name: "Troy",
    languages: ["en-US"],
    description:
      "Strong, dependable male voice designed for trust-building in customer-facing interactions",
    gender: "male",
    tags: ["fix", "man", "southern us"],
  },
  {
    id: "820a3788-2b37-4d21-847a-b65d8a68c99a",
    name: "Tyler",
    languages: ["en-US"],
    description:
      "Direct and confidence inspiring adult male for sales and friendly interpersonal conversations",
    gender: "male",
    tags: ["friendly", "salesman", "general american"],
  },
  {
    id: "af346552-54bf-4c2b-a4d4-9d2820f51b6c",
    name: "Valerie",
    languages: ["en-US"],
    description:
      "Authoritative mature female for frontline customer support use cases",
    gender: "female",
    tags: ["support", "authority", "african american"],
  },
  {
    id: "38bded0a-3ab4-42d1-8e47-2e0b6b10ced9",
    name: "Vikram",
    languages: ["te-IN"],
    description:
      "Expressive adult male voice with a colorful tone for storytelling, narrations, and engaging cultural content",
    gender: "male",
    tags: ["folk", "narrator", "telangana"],
  },
  {
    id: "b9de4a89-2257-424b-94c2-db18ba68c81a",
    name: "Viktoria",
    languages: ["de-DE"],
    description: "Clear and smooth female for phone conversations",
    gender: "female",
    tags: ["phone", "conversationalist", "standard german"],
  },
  {
    id: "79bfcec0-720c-41f2-a33a-f12383e9627f",
    name: "Wang",
    languages: ["en-US"],
    description:
      "Clear and firm adult male voice with an authoritative tone for customer support, giving instructions and professional communication",
    gender: "male",
    tags: ["guide", "general american"],
  },
  {
    id: "2a4d065a-ac91-4203-a015-eb3fc3ee3365",
    name: "Wes",
    languages: ["en-US"],
    description: "Kind male for engaging with customers",
    gender: "male",
    tags: ["customer", "companion", "general american"],
  },
  {
    id: "b8cd71e3-bc14-4538-a530-d6314731c036",
    name: "Xia",
    languages: ["vi-VN", "hi-IN", "de-DE", "fr-CA", "it-IT", "ta-IN", "te-IN"],
    description:
      "Soft-spoken adult female voice for calm conversations and customer support",
    gender: "female",
    tags: ["calm", "companion", "southern vietnamese"],
  },
  {
    id: "daf747c6-6bc2-4083-bd59-aa94dce23f5d",
    name: "Yasmin",
    languages: ["en-US"],
    description: "Firm adult female for conversational use cases",
    gender: "female",
    tags: ["dialogue", "anchor", "arabic english"],
  },
  {
    id: "59d4fd2f-f5eb-4410-8105-58db7661144f",
    name: "Yuki",
    languages: ["ja-JP"],
    description:
      "Calm, more serious female for news narration and formal customer service",
    gender: "female",
    tags: ["calm", "woman", "standard japanese"],
  },
  {
    id: "2b568345-1d48-4047-b25f-7baccf842eb0",
    name: "Yumiko",
    languages: ["ja-JP"],
    description:
      "Friendly, professional and upbeat woman for casual conversations",
    gender: "female",
    tags: ["friendly", "agent", "standard japanese"],
  },
  {
    id: "ed81fd13-2016-4a49-8fe3-c0d2761695fc",
    name: "Zack",
    languages: ["en-US"],
    description: "Firm, energetic male for lively announcing",
    gender: "male",
    tags: ["sportsman", "general american"],
  },
  {
    id: "e00d0e4c-a5c8-443f-a8a3-473eb9a62355",
    name: "Zeke",
    languages: ["en-US"],
    description:
      "High pitched, friendly, young adult male for gaming and entertainment characters",
    gender: "male",
    tags: ["friendly", "sidekick", "general american"],
  },
  {
    id: "dcf62f33-7cff-4f20-85b2-2efaa68cbc32",
    name: "Zofia",
    languages: ["pl-PL"],
    description: "Expressive female for clear communication",
    gender: "female",
    tags: ["audiobook", "muse", "polish"],
  },
]
