export const INITIAL_ORGANIZATION_CREDIT_AMOUNT = 10

export const MIN_CREDIT_PURCHASE_AMOUNT = 10

export const DEFAULT_CREDIT_PURCHASE_AMOUNT = 20

export const DEFAULT_CREDIT_AUTO_RELOAD_AMOUNT = 20

export const DEFAULT_CREDIT_AUTO_RELOAD_THRESHOLD = 10
