export const elevenlabsVoices = [
  {
    id: "pNInz6obpgDQGcFmaJgB",
    name: "Adam - Dominant, Firm",
    languages: ["en"],
    description:
      "A bright tenor pitch that immediately cuts through. The delivery is brash and openly confident, speaking with unwavering certainty and a slightly aggressive self-assurance.",
    gender: "male",
    tags: ["american", "middle_aged", "social_media", "premade"],
  },
  {
    id: "Xb7hH8MSUJpSbSDYk0k2",
    name: "Alice - Clear, Engaging Educator",
    languages: ["ar", "en-GB", "fr-FR", "hi-IN", "it-IT", "ja-JP", "pl-PL"],
    description:
      "Clear and engaging, friendly woman with a British accent suitable for e-learning.",
    gender: "female",
    tags: [
      "british",
      "middle_aged",
      "informative_educational",
      "professional",
      "premade",
    ],
  },
  {
    id: "hpp4J3VqNfWAUOO0d1Us",
    name: "Bella - Professional, Bright, Warm",
    languages: ["en-US"],
    description:
      "This voice is warm, bright, and professional, characterized by a Standard American accent and a polished, narrative quality. It features a medium-high pitch with crisp diction and a deliberate, rhythmic pace that makes it highly intelligible and engaging for long-form listening.",
    gender: "female",
    tags: [
      "american",
      "middle_aged",
      "informative_educational",
      "professional",
      "premade",
    ],
  },
  {
    id: "pqHfZKP75CvOlQylNhV4",
    name: "Bill - Wise, Mature, Balanced",
    languages: ["ar", "cmn-CN", "cs-CZ", "de-DE", "en-US", "fr-FR"],
    description: "Friendly and comforting voice ready to narrate your stories.",
    gender: "male",
    tags: ["american", "old", "advertisement", "crisp", "premade"],
  },
  {
    id: "nPczCjzI2devNBz1zQrb",
    name: "Brian - Deep, Resonant and Comforting",
    languages: [
      "ar",
      "cmn-CN",
      "de-DE",
      "en-US",
      "hi-IN",
      "nl-NL",
      "pt-BR",
      "ro-RO",
      "sk-SK",
    ],
    description:
      "Middle-aged man with a resonant and comforting tone. Great for narrations and advertisements.",
    gender: "male",
    tags: ["american", "middle_aged", "social_media", "classy", "premade"],
  },
  {
    id: "N2lVS1w4EtoT3dr4eOWO",
    name: "Callum - Husky Trickster",
    languages: ["en-US", "fr-FR", "hi-IN"],
    description: "Deceptively gravelly, yet unsettling edge.",
    gender: "male",
    tags: ["american", "middle_aged", "characters_animation", "premade"],
  },
  {
    id: "IKne3meq5aSn9XLyUdCD",
    name: "Charlie - Deep, Confident, Energetic",
    languages: ["cmn-CN", "en-AU", "es-ES", "fil-PH", "pt-BR"],
    description:
      "A young Australian male with a confident and energetic voice.",
    gender: "male",
    tags: ["australian", "young", "conversational", "hyped", "premade"],
  },
  {
    id: "iP95p4xoKVk53GoZ742B",
    name: "Chris - Charming, Down-to-Earth",
    languages: ["ar", "en-US", "fr-FR", "hi-IN", "pt-BR", "sv-SE"],
    description:
      "Natural and real, this down-to-earth voice is great across many use-cases.",
    gender: "male",
    tags: ["american", "middle_aged", "conversational", "casual", "premade"],
  },
  {
    id: "onwK4e9ZLuTAKqWW03F9",
    name: "Daniel - Steady Broadcaster",
    languages: ["de-DE", "en-GB", "tr-TR"],
    description:
      "A strong voice perfect for delivering a professional broadcast or news story.",
    gender: "male",
    tags: [
      "british",
      "middle_aged",
      "informative_educational",
      "formal",
      "premade",
    ],
  },
  {
    id: "cjVigY5qzO86Huf0OWal",
    name: "Eric - Smooth, Trustworthy",
    languages: ["de-DE", "en-US", "es-ES", "fr-FR", "pt-BR", "sk-SK"],
    description:
      "A smooth tenor pitch from a man in his 40s - perfect for agentic use cases.",
    gender: "male",
    tags: ["american", "middle_aged", "conversational", "classy", "premade"],
  },
  {
    id: "JBFqnCBsd6RMkjVDRZzb",
    name: "George - Warm, Captivating Storyteller",
    languages: [
      "ar",
      "cs-CZ",
      "en-GB",
      "es-ES",
      "fil-PH",
      "fr-FR",
      "hi-IN",
      "ja-JP",
    ],
    description: "Warm resonance that instantly captivates listeners.",
    gender: "male",
    tags: ["british", "middle_aged", "narrative_story", "mature", "premade"],
  },
  {
    id: "SOYHLrjzK2X1ezoPC6cr",
    name: "Harry - Fierce Warrior",
    languages: ["en-US"],
    description: "An animated warrior ready to charge forward.",
    gender: "male",
    tags: ["american", "young", "characters_animation", "rough", "premade"],
  },
  {
    id: "cgSgspJ2msm6clMCkdW9",
    name: "Jessica - Playful, Bright, Warm",
    languages: [
      "ar",
      "cmn-CN",
      "cs-CZ",
      "de-DE",
      "en-US",
      "fr-FR",
      "hi-IN",
      "ja-JP",
    ],
    description:
      "Young and popular, this playful American female voice is perfect for trendy content.",
    gender: "female",
    tags: ["american", "young", "conversational", "cute", "premade"],
  },
  {
    id: "FGY2WhTYpPnrIDTdsKH5",
    name: "Laura - Enthusiast, Quirky Attitude",
    languages: ["ar", "cmn-CN", "de-DE", "en-US", "fr-FR"],
    description:
      "This young adult female voice delivers sunny enthusiasm with a quirky attitude.",
    gender: "female",
    tags: ["american", "young", "social_media", "sassy", "premade"],
  },
  {
    id: "TX3LPaxmHKxFdv7VOQHJ",
    name: "Liam - Energetic, Social Media Creator",
    languages: ["cs-CZ", "de-DE", "en-US", "hi-IN", "pl-PL", "pt-BR", "tr-TR"],
    description:
      "A young adult with energy and warmth - suitable for reels and shorts.",
    gender: "male",
    tags: ["american", "young", "social_media", "confident", "premade"],
  },
  {
    id: "pFZP5JQG7iQjIQuC4Bku",
    name: "Lily - Velvety Actress",
    languages: ["cmn-CN", "cs-CZ", "de-DE", "en-GB", "it-IT", "nl-NL", "pl-PL"],
    description:
      "Velvety British female voice delivers news and narrations with warmth and clarity.",
    gender: "female",
    tags: [
      "british",
      "middle_aged",
      "informative_educational",
      "confident",
      "premade",
    ],
  },
  {
    id: "XrExE9yKIg1WjnnlVkGX",
    name: "Matilda - Knowledgable, Professional",
    languages: ["ar", "de-DE", "en-US", "es-ES", "fr-FR", "it-IT"],
    description:
      "A professional woman with a pleasing alto pitch. Suitable for many use cases.",
    gender: "female",
    tags: [
      "american",
      "middle_aged",
      "informative_educational",
      "upbeat",
      "premade",
    ],
  },
  {
    id: "CwhRBWXzGAHq8TQ4Fs17",
    name: "Roger - Laid-Back, Casual, Resonant",
    languages: ["de-DE", "en-US", "es-ES", "fr-FR", "nl-NL"],
    description: "Easy going and perfect for casual conversations.",
    gender: "male",
    tags: ["american", "middle_aged", "conversational", "classy", "premade"],
  },
  {
    id: "EXAVITQu4vr4xnSDxMaL",
    name: "Sarah - Mature, Reassuring, Confident",
    languages: ["ar", "cmn-CN", "en-US", "es-ES", "fr-FR", "hi-IN"],
    description:
      "Young adult woman with a confident and warm, mature quality and a reassuring, professional tone.",
    gender: "female",
    tags: ["american", "young", "entertainment_tv", "professional", "premade"],
  },
  {
    id: "bIHbv24MWmeRgasZH58o",
    name: "Will - Relaxed Optimist",
    languages: [
      "cmn-CN",
      "cs-CZ",
      "de-DE",
      "en-US",
      "es-ES",
      "fil-PH",
      "fr-FR",
      "pt-BR",
      "sk-SK",
      "sv-SE",
    ],
    description: "Conversational and laid back.",
    gender: "male",
    tags: ["american", "young", "conversational", "chill", "premade"],
  },
]
