export const inworldVoices = [
  {
    id: "Aanya",
    name: "Aanya",
    languages: ["hi-IN"],
    description:
      "A professional adult female with a clear, formal, and authoritative voice, speaking Hindi in a studio environment.",
    gender: "female",
    tags: ["news", "informative"],
  },
  {
    id: "Aarav",
    name: "Aarav",
    languages: ["hi-IN"],
    description:
      "A thoughtful adult male with an Indian accent speaking earnestly in a room with some background hum.",
    gender: "male",
    tags: ["motivational", "professional"],
  },
  {
    id: "Abby",
    name: "Abby",
    languages: ["en-US"],
    description:
      "Bright, eager American female child voice, ideal for animated characters, upbeat educational content, and lively kids' commercials.",
    gender: "female",
    tags: [
      "bright",
      "eager",
      "youthful",
      "education & training",
      "language learning",
      "companion",
      "social",
      "children",
    ],
  },
  {
    id: "Aditya",
    name: "Aditya",
    languages: ["en-IN"],
    description:
      "Confident, natural Indian male voice, ideal for customer support, corporate, and education.",
    gender: "male",
    tags: [
      "confident",
      "natural",
      "approachable",
      "indian",
      "customer support",
      "corporate",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Alain",
    name: "Alain",
    languages: ["fr-FR"],
    description:
      "Deep, smooth middle-aged male French voice. Composed and calm",
    gender: "male",
    tags: ["deep", "warm"],
  },
  {
    id: "Alaric",
    name: "Alaric",
    languages: ["en-US"],
    description:
      "Wise, gravelly male voice, ideal for RPG narration, audiobooks, and gaming.",
    gender: "male",
    tags: [
      "wise",
      "gravelly",
      "theatrical",
      "gaming",
      "rpg",
      "narration",
      "interactive media",
      "companion",
    ],
  },
  {
    id: "Alex",
    name: "Alex",
    languages: ["en-US"],
    description:
      "Energetic and expressive mid-range male voice, with a mildly nasal quality",
    gender: "male",
    tags: [
      "friendly",
      "expressive",
      "companion",
      "general purpose assistant",
      "education & training",
      "tutoring",
      "professional training",
    ],
  },
  {
    id: "Alistair",
    name: "Alistair",
    languages: ["en-GB"],
    description:
      "Clear, articulate British male voice ideal for educational content and healthcare narration.",
    gender: "male",
    tags: ["articulate", "clear", "engaging", "polished", "professional"],
  },
  {
    id: "Alvaro",
    name: "Alvaro",
    languages: ["es-ES"],
    description:
      "Warm, articulate Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "warm",
      "articulate",
      "engaging",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Alyona",
    name: "Alyona",
    languages: ["ru-RU"],
    description:
      "Soft, clear Russian female voice, ideal for narration, education, and customer service.",
    gender: "female",
    tags: [
      "soft",
      "clear",
      "reassuring",
      "russian",
      "narration",
      "education & training",
      "customer support",
      "interactive media",
    ],
  },
  {
    id: "Amara",
    name: "Amara",
    languages: ["en-NG"],
    description:
      "Warm, professional Nigerian female voice, ideal for customer service, narration, and support.",
    gender: "female",
    tags: [
      "warm",
      "professional",
      "engaging",
      "nigerian",
      "customer support",
      "narration",
      "enterprise",
      "interactive media",
    ],
  },
  {
    id: "Amina",
    name: "Amina",
    languages: ["en-US"],
    description:
      "Warm, inviting West African female voice, ideal for community outreach, cultural storytelling, and educational workshops.",
    gender: "female",
    tags: [
      "warm",
      "inviting",
      "articulate",
      "measured",
      "confident",
      "west african",
    ],
  },
  {
    id: "Andoy",
    name: "Andoy",
    languages: ["en-PH"],
    description:
      "Friendly, easygoing Filipino male voice, ideal for customer service, e-learning, and support.",
    gender: "male",
    tags: [
      "friendly",
      "easygoing",
      "warm",
      "filipino",
      "customer support",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Anjali",
    name: "Anjali",
    languages: ["en-IN"],
    description:
      "A confident and articulate Indian female voice, ideal for professional training materials.",
    gender: "female",
    tags: [
      "professional",
      "confident",
      "articulate",
      "indian",
      "education & training",
      "tutoring",
      "professional training",
    ],
  },
  {
    id: "Annika",
    name: "Annika",
    languages: ["de-DE"],
    description:
      "Warm, engaging German female voice, ideal for business, e-learning, and narration.",
    gender: "female",
    tags: [
      "warm",
      "engaging",
      "clear",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Arjun",
    name: "Arjun",
    languages: ["en-IN"],
    description:
      "Clear, composed Indian male voice, well-suited for instructional webinars and technology explainers.",
    gender: "male",
    tags: [
      "smooth",
      "informative",
      "indian",
      "education & training",
      "tutoring",
    ],
  },
  {
    id: "Arkady",
    name: "Arkady",
    languages: ["ru-RU"],
    description:
      "Natural, conversational Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "natural",
      "conversational",
      "warm",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Arthur",
    name: "Arthur",
    languages: ["en-US"],
    description:
      "A warm and mature male voice with clear articulation and an encouraging, knowledgeable demeanor.",
    gender: "male",
    tags: [
      "mature",
      "knowledgeable",
      "warm",
      "articulate",
      "informative",
      "healthcare",
    ],
  },
  {
    id: "Ashley",
    name: "Ashley",
    languages: ["en-US"],
    description: "A warm, natural female voice",
    gender: "female",
    tags: [
      "warm",
      "mellow",
      "customer support",
      "companion",
      "general purpose assistant",
      "education & training",
      "tutoring",
      "healthcare",
      "patient support",
    ],
  },
  {
    id: "Asuka",
    name: "Asuka",
    languages: ["ja-JP"],
    description: "Friendly, young adult Japanese female voice",
    gender: "female",
    tags: ["energetic", "clear"],
  },
  {
    id: "Avery",
    name: "Avery",
    languages: ["en-US"],
    description:
      "Youthful, performative male voice, suited for gameshow-style hosting, energetic presenter reads, and expressive young character parts.",
    gender: "male",
    tags: [
      "youthful",
      "performative",
      "upbeat",
      "character",
      "ads",
      "social companion",
    ],
  },
  {
    id: "Banjo",
    name: "Banjo",
    languages: ["en-AU"],
    description:
      "Laid-back, genial Australian male voice, ideal for lifestyle content, travel, and casual narration.",
    gender: "male",
    tags: [
      "laid-back",
      "genial",
      "natural",
      "australian",
      "lifestyle",
      "travel",
      "narration",
      "interactive media",
    ],
  },
  {
    id: "Bastian",
    name: "Bastian",
    languages: ["de-DE"],
    description:
      "Warm, natural German male voice, ideal for business, e-learning, and narration.",
    gender: "male",
    tags: [
      "warm",
      "natural",
      "engaging",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Beatrice",
    name: "Beatrice",
    languages: ["en-GB"],
    description:
      "Rich, authoritative British female voice, ideal for audiobooks, documentary, and narration.",
    gender: "female",
    tags: [
      "rich",
      "authoritative",
      "graceful",
      "british",
      "audiobook",
      "narration",
      "documentary",
      "interactive media",
    ],
  },
  {
    id: "Beatriz",
    name: "Beatriz",
    languages: ["pt-BR"],
    description:
      "A clear, mid-pitched adult female voice with a Brazilian accent, speaking fluently in a quiet indoor environment.",
    gender: "female",
    tags: ["casual", "conversational"],
  },
  {
    id: "Bianca",
    name: "Bianca",
    languages: ["en-US"],
    description:
      "Deep, controlled female voice, ideal for serious corporate reads, composed documentary segments, and measured authority-led explainers.",
    gender: "female",
    tags: [
      "deep",
      "controlled",
      "understated",
      "customer support",
      "professional training",
      "narrative",
    ],
  },
  {
    id: "Birgit",
    name: "Birgit",
    languages: ["de-DE"],
    description:
      "Composed, professional German female voice, ideal for business, e-learning, and narration.",
    gender: "female",
    tags: [
      "composed",
      "professional",
      "measured",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Blake",
    name: "Blake",
    languages: ["en-US"],
    description:
      "Rich, intimate male voice, perfect for audiobooks, romantic content, and reassuring narration",
    gender: "male",
    tags: [
      "intimate",
      "romantic",
      "healthcare",
      "spiritual support",
      "companion app",
      "social",
      "interactive media",
      "narrative",
    ],
  },
  {
    id: "Boonleng",
    name: "Boonleng",
    languages: ["en-SG"],
    description:
      "Confident, conversational Singaporean male voice, ideal for e-learning, customer service, and support.",
    gender: "male",
    tags: [
      "confident",
      "conversational",
      "clear",
      "singaporean",
      "education & training",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Borja",
    name: "Borja",
    languages: ["es-ES"],
    description:
      "Natural, poised Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "natural",
      "poised",
      "approachable",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Brandon",
    name: "Brandon",
    languages: ["en-US"],
    description:
      "Bold, strident male voice, ideal for structured announcements, news-style reads, and direct promotional messaging.",
    gender: "male",
    tags: ["bold", "energetic", "strident", "news", "ads", "announcements"],
  },
  {
    id: "Brian",
    name: "Brian",
    languages: ["en-US"],
    description:
      "Friendly, encouraging American male voice, ideal for educational tutorials, motivational content, and instructional videos.",
    gender: "male",
    tags: [
      "friendly",
      "encouraging",
      "clear",
      "education & training",
      "tutorials",
      "enterprise",
      "customer support",
    ],
  },
  {
    id: "Brick",
    name: "Brick",
    languages: ["en-US"],
    description:
      "Playful, bombastic male voice, ideal for game shows, interactive entertainment, and hosting.",
    gender: "male",
    tags: [
      "playful",
      "bombastic",
      "charismatic",
      "game show",
      "hosting",
      "entertainment",
      "interactive media",
    ],
  },
  {
    id: "Brooke",
    name: "Brooke",
    languages: ["en-US"],
    description:
      "A clear, professional young female voice with a polite and helpful delivery.",
    gender: "female",
    tags: [
      "clear",
      "polite",
      "professional",
      "helpful",
      "conversational",
      "customer support",
    ],
  },
  {
    id: "Bruna",
    name: "Bruna",
    languages: ["pt-BR"],
    description:
      "Warm, conversational Brazilian Portuguese female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "warm",
      "conversational",
      "engaging",
      "brazilian",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Bruno",
    name: "Bruno",
    languages: ["es-MX"],
    description:
      "Clear, approachable Mexican Spanish male voice, ideal for education, narration, and customer service.",
    gender: "male",
    tags: [
      "clear",
      "approachable",
      "relaxed",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Bryce",
    name: "Bryce",
    languages: ["en-US"],
    description:
      "Confident, energetic young male voice with a dynamic social feel",
    gender: "male",
    tags: [
      "confident",
      "energetic",
      "social media",
      "sports commentary",
      "interactive media",
      "gaming",
    ],
  },
  {
    id: "Callum",
    name: "Callum",
    languages: ["en-AU"],
    description:
      "Casual and friendly Australian male voice, ideal for informal instructional content.",
    gender: "male",
    tags: [
      "casual",
      "friendly",
      "informal",
      "australian",
      "education & training",
      "tutoring",
      "interactive media",
    ],
  },
  {
    id: "Camila",
    name: "Camila",
    languages: ["es-MX"],
    description:
      "A young female with a smooth, clear voice speaking at a moderate pace in a quiet environment.",
    gender: "female",
    tags: ["clear", "informative"],
  },
  {
    id: "Camille",
    name: "Camille",
    languages: ["en-US"],
    description:
      "Clear, professional young female voice with a composed delivery",
    gender: "female",
    tags: [
      "professional",
      "composed",
      "clear",
      "customer support",
      "general purpose assistant",
      "media & entertainment",
    ],
  },
  {
    id: "Carina",
    name: "Carina",
    languages: ["de-DE"],
    description:
      "Friendly, expressive German female voice, ideal for business, e-learning, and narration.",
    gender: "female",
    tags: [
      "friendly",
      "expressive",
      "approachable",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Carter",
    name: "Carter",
    languages: ["en-US"],
    description:
      "Energetic, mature radio announcer-style male voice, great for storytelling, pep talks, and voiceovers.",
    gender: "male",
    tags: [
      "intense",
      "motivational",
      "interactive media",
      "ads",
      "news",
      "sports",
    ],
  },
  {
    id: "Casey",
    name: "Casey",
    languages: ["en-US"],
    description: "Laid-back young male voice with a chill, friendly vibe",
    gender: "male",
    tags: [
      "chill",
      "laid-back",
      "friendly",
      "conversational",
      "companion",
      "social companion",
    ],
  },
  {
    id: "Cedric",
    name: "Cedric",
    languages: ["en-US"],
    description:
      "Crisp, measured male voice, ideal for formal announcements, premium trailer narration, and command-forward presentation scripts.",
    gender: "male",
    tags: ["crisp", "measured", "authoritative", "news", "narrative", "ads"],
  },
  {
    id: "Celeste",
    name: "Celeste",
    languages: ["en-US"],
    description:
      "Soft, whispery female voice, ideal for ASMR videos, soothing lullabies, and gentle mindfulness sessions.",
    gender: "female",
    tags: [
      "soft",
      "whispery",
      "tranquil",
      "healthcare",
      "spiritual support",
      "companion app",
      "social",
    ],
  },
  {
    id: "Chioma",
    name: "Chioma",
    languages: ["en-NG"],
    description:
      "Bright, friendly Nigerian female voice, ideal for customer service, narration, and support.",
    gender: "female",
    tags: [
      "bright",
      "friendly",
      "confident",
      "nigerian",
      "customer support",
      "narration",
      "enterprise",
      "interactive media",
    ],
  },
  {
    id: "Chip",
    name: "Chip",
    languages: ["en-US"],
    description:
      "Cheerful, witty male voice, ideal for game shows, interactive entertainment, and hosting.",
    gender: "male",
    tags: [
      "cheerful",
      "witty",
      "energetic",
      "game show",
      "hosting",
      "entertainment",
      "interactive media",
    ],
  },
  {
    id: "Chloe",
    name: "Chloe",
    languages: ["en-US"],
    description:
      "Thoughtful, introspective youthful female voice, perfect for coming-of-age narratives, personal growth stories, and emotional teen dramas.",
    gender: "female",
    tags: [
      "thoughtful",
      "introspective",
      "youthful",
      "interactive media",
      "narrative",
      "companion",
      "social",
    ],
  },
  {
    id: "Citlali",
    name: "Citlali",
    languages: ["es-MX"],
    description:
      "Calm, engaging Mexican Spanish female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "calm",
      "engaging",
      "poised",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Claire",
    name: "Claire",
    languages: ["en-US"],
    description:
      "Warm, gentle Eastern European female voice, ideal for bedtime stories, relaxation podcasts",
    gender: "female",
    tags: [
      "warm",
      "gentle",
      "soothing",
      "interactive media",
      "narrative",
      "healthcare",
      "spiritual support",
      "east European",
    ],
  },
  {
    id: "Clive",
    name: "Clive",
    languages: ["en-GB"],
    description:
      "British-accented English-language male voice with a calm, cordial quality",
    gender: "male",
    tags: [
      "calm",
      "friendly",
      "british",
      "customer support",
      "enterprise",
      "healthcare",
      "patient support",
      "companion",
      "general purpose assistant",
    ],
  },
  {
    id: "Conrad",
    name: "Conrad",
    languages: ["en-US"],
    description:
      "Gruff, weathered male voice, perfect for detective archetypes, hard-edged audiobook roles, and serious investigative narration.",
    gender: "male",
    tags: ["gruff", "weathered", "somber", "character", "narrative"],
  },
  {
    id: "Cooper",
    name: "Cooper",
    languages: ["en-AU"],
    description:
      "Casual, warm Australian male voice, ideal for lifestyle content, travel, and casual narration.",
    gender: "male",
    tags: [
      "casual",
      "warm",
      "conversational",
      "australian",
      "lifestyle",
      "travel",
      "narration",
      "interactive media",
    ],
  },
  {
    id: "Cordelia",
    name: "Cordelia",
    languages: ["en-GB"],
    description:
      "Refined, composed British female voice, ideal for audiobooks, documentary, and narration.",
    gender: "female",
    tags: [
      "refined",
      "composed",
      "literary",
      "british",
      "audiobook",
      "narration",
      "documentary",
      "interactive media",
    ],
  },
  {
    id: "Craig",
    name: "Craig",
    languages: ["en-GB"],
    description: "Older British male with a refined and articulate voice",
    gender: "male",
    tags: [
      "posh",
      "raspy",
      "british",
      "companion",
      "social companion",
      "interactive media",
      "narrative",
      "healthcare",
      "mental health",
    ],
  },
  {
    id: "Cuauhtemoc",
    name: "Cuauhtemoc",
    languages: ["es-MX"],
    description:
      "Warm, conversational Mexican Spanish male voice, ideal for education, narration, and customer service.",
    gender: "male",
    tags: [
      "warm",
      "conversational",
      "friendly",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Curro",
    name: "Curro",
    languages: ["es-ES"],
    description:
      "Clear, composed Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "clear",
      "composed",
      "professional",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Dalisay",
    name: "Dalisay",
    languages: ["en-PH"],
    description:
      "Bright, approachable Filipino female voice, ideal for customer service, e-learning, and support.",
    gender: "female",
    tags: [
      "bright",
      "approachable",
      "cheerful",
      "filipino",
      "customer support",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Damon",
    name: "Damon",
    languages: ["en-US"],
    description:
      "Calm, raspy male voice, suited for moody narration, atmospheric roleplay characters, and grounded meditative reads with subtle tension.",
    gender: "male",
    tags: [
      "calm",
      "mysterious",
      "raspy",
      "meditation",
      "narrative",
      "customer support",
    ],
  },
  {
    id: "Daniel",
    name: "Daniel",
    languages: ["en-US"],
    description:
      "A polite and helpful mid-range male voice with a friendly and reassuring tone, perfect for customer service.",
    gender: "male",
    tags: ["friendly", "polite", "helpful", "empathetic", "customer support"],
  },
  {
    id: "Darlene",
    name: "Darlene",
    languages: ["en-US"],
    description:
      "Soothing, comforting Southern female voice, ideal for bedtime stories, family-centered commercials, and nostalgic narrations.",
    gender: "female",
    tags: [
      "soothing",
      "comforting",
      "gentle",
      "southern",
      "interactive media",
      "character",
      "narrative",
    ],
  },
  {
    id: "Deborah",
    name: "Deborah",
    languages: ["en-US"],
    description: "Warm, peaceful female voice with a calm tone",
    gender: "female",
    tags: ["gentle", "companion", "personal growth"],
  },
  {
    id: "Dennis",
    name: "Dennis",
    languages: ["en-US"],
    description: "Middle-aged man with a smooth, calm and friendly voice",
    gender: "male",
    tags: [
      "outgoing",
      "upbeat",
      "customer support",
      "education & training",
      "tutoring",
      "companion",
      "general purpose assistant",
    ],
  },
  {
    id: "Derek",
    name: "Derek",
    languages: ["en-US"],
    description:
      "Steady, professional, composed American male voice, ideal for banking support, account inquiries, and service escalation calls.",
    gender: "male",
    tags: [
      "steady",
      "professional",
      "composed",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Dhruv",
    name: "Dhruv",
    languages: ["en-IN"],
    description:
      "Professional, measured Indian male voice, ideal for customer support, corporate, and education.",
    gender: "male",
    tags: [
      "professional",
      "measured",
      "clear",
      "indian",
      "customer support",
      "corporate",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Diego",
    name: "Diego",
    languages: ["es-ES"],
    description: "Spanish-speaking male voice with a soothing, gentle quality",
    gender: "male",
    tags: ["soft", "nervous"],
  },
  {
    id: "Dmitry",
    name: "Dmitry",
    languages: ["ru-RU"],
    description:
      "Deep, gravelly male voice, delivered at a moderate pace with a commanding and narrative tone.",
    gender: "male",
    tags: ["gravelly", "authoritative"],
  },
  {
    id: "Dominus",
    name: "Dominus",
    languages: ["en-US"],
    description:
      "Robotic, deep male voice with a menacing quality. Perfect for villains",
    gender: "male",
    tags: ["robotic", "monotone", "interactive media", "character"],
  },
  {
    id: "Duncan",
    name: "Duncan",
    languages: ["en-GB"],
    description:
      "Warm, articulate British male voice for customer support and education.",
    gender: "male",
    tags: [
      "warm",
      "articulate",
      "customer support",
      "education & training",
      "knowledge sharing",
    ],
  },
  {
    id: "Edward",
    name: "Edward",
    languages: ["en-US"],
    description: "American male with a emphatic, confident and streetwise tone",
    gender: "male",
    tags: [
      "emphatic",
      "shouty",
      "interactive media",
      "character",
      "companion",
      "fitness coach",
    ],
  },
  {
    id: "Eldrin",
    name: "Eldrin",
    languages: ["en-US"],
    description:
      "Sage, resonant male voice, ideal for RPG narration, audiobooks, and gaming.",
    gender: "male",
    tags: [
      "sage",
      "resonant",
      "weathered",
      "gaming",
      "rpg",
      "narration",
      "interactive media",
      "companion",
    ],
  },
  {
    id: "Eleanor",
    name: "Eleanor",
    languages: ["en-GB"],
    description:
      "Polished, approachable British female voice for support and learning.",
    gender: "female",
    tags: [
      "polished",
      "approachable",
      "customer support",
      "education & training",
      "tutoring",
      "knowledge sharing",
    ],
  },
  {
    id: "Elena",
    name: "Elena",
    languages: ["ru-RU"],
    description:
      "Clear, mid-range female voice, with a smooth texture and a neutral, informational tone.",
    gender: "female",
    tags: ["clear", "moderately-paced"],
  },
  {
    id: "Elizabeth",
    name: "Elizabeth",
    languages: ["en-US"],
    description:
      "Professional middle-aged woman, perfect for narrations and voiceovers",
    gender: "female",
    tags: ["informative", "calm"],
  },
  {
    id: "Elliot",
    name: "Elliot",
    languages: ["en-US"],
    description:
      "A calm, steady male voice, suitable for nature documentaries, general informational content, and relaxed narrations.",
    gender: "male",
    tags: ["calm", "neutral", "steady", "interactive media", "narrative"],
  },
  {
    id: "Emeka",
    name: "Emeka",
    languages: ["en-NG"],
    description:
      "Warm, conversational Nigerian male voice, ideal for customer service, narration, and support.",
    gender: "male",
    tags: [
      "warm",
      "conversational",
      "engaging",
      "nigerian",
      "customer support",
      "narration",
      "enterprise",
      "interactive media",
    ],
  },
  {
    id: "Emil",
    name: "Emil",
    languages: ["en-PH"],
    description:
      "Bright, upbeat Filipino male voice, ideal for customer service, e-learning, and support.",
    gender: "male",
    tags: [
      "bright",
      "upbeat",
      "helpful",
      "filipino",
      "customer support",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Erik",
    name: "Erik",
    languages: ["nl-NL"],
    description: "Older Dutch male voice with a weathered edge",
    gender: "male",
    tags: ["smooth", "strong"],
  },
  {
    id: "Ethan",
    name: "Ethan",
    languages: ["en-US"],
    description:
      "Assured, precise male voice, perfect for tech tutorials, detailed gadget overviews, and captivating product demonstrations.",
    gender: "male",
    tags: [
      "assured",
      "precise",
      "captivating",
      "companion",
      "general purpose assistant",
      "enterprise",
    ],
  },
  {
    id: "Evan",
    name: "Evan",
    languages: ["en-US"],
    description:
      "Friendly, approachable, easygoing male voice, ideal for onboarding calls, retail assistance, and customer check-ins.",
    gender: "male",
    tags: [
      "friendly",
      "approachable",
      "easygoing",
      "customer support",
      "companion",
      "general purpose assistant",
      "enterprise",
    ],
  },
  {
    id: "Evelyn",
    name: "Evelyn",
    languages: ["en-US"],
    description:
      "A gentle and intimate female voice, ideal for personal ASMR content, affirmations, and close, calming conversations.",
    gender: "female",
    tags: [
      "gentle",
      "intimate",
      "warm",
      "soothing",
      "soft-spoken",
      "healthcare",
      "spiritual support",
    ],
  },
  {
    id: "Fabian",
    name: "Fabian",
    languages: ["de-DE"],
    description:
      "Clear, composed German male voice, ideal for business, e-learning, and narration.",
    gender: "male",
    tags: [
      "clear",
      "composed",
      "professional",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Felix",
    name: "Felix",
    languages: ["en-GB"],
    description:
      "Calm, friendly British male voice, ideal for help and tutorials.",
    gender: "male",
    tags: [
      "calm",
      "friendly",
      "customer support",
      "education & training",
      "professional training",
      "general purpose assistant",
    ],
  },
  {
    id: "Folake",
    name: "Folake",
    languages: ["en-NG"],
    description:
      "Clear, approachable Nigerian female voice, ideal for customer service, narration, and support.",
    gender: "female",
    tags: [
      "clear",
      "approachable",
      "poised",
      "nigerian",
      "customer support",
      "narration",
      "enterprise",
      "interactive media",
    ],
  },
  {
    id: "Franziska",
    name: "Franziska",
    languages: ["de-DE"],
    description:
      "Confident, grounded German female voice, ideal for business, e-learning, and narration.",
    gender: "female",
    tags: [
      "confident",
      "grounded",
      "articulate",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Freddie",
    name: "Freddie",
    languages: ["en-GB"],
    description:
      "Young, casual British male voice, ideal for conversational assistants, podcasts, and narration.",
    gender: "male",
    tags: [
      "young",
      "casual",
      "conversational",
      "british",
      "podcast",
      "narration",
      "companion",
      "interactive media",
    ],
  },
  {
    id: "Galina",
    name: "Galina",
    languages: ["ru-RU"],
    description:
      "Soft, clear Russian female voice, ideal for narration, education, and customer service.",
    gender: "female",
    tags: [
      "soft",
      "clear",
      "reassuring",
      "russian",
      "narration",
      "education & training",
      "customer support",
      "interactive media",
    ],
  },
  {
    id: "Gareth",
    name: "Gareth",
    languages: ["en-US"],
    description:
      "Soothing, gentle male voice, ideal for guided meditations, mindfulness exercises, and relaxation-focused wellness content.",
    gender: "male",
    tags: [
      "soothing",
      "gentle",
      "steady",
      "healthcare",
      "mental health",
      "spiritual",
    ],
  },
  {
    id: "Gianni",
    name: "Gianni",
    languages: ["it-IT"],
    description: "Deep, smooth Italian male voice that speaks rapidly",
    gender: "male",
    tags: ["warm", "deep"],
  },
  {
    id: "Gleb",
    name: "Gleb",
    languages: ["ru-RU"],
    description:
      "Bright, engaging Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "bright",
      "engaging",
      "relaxed",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Gonzalo",
    name: "Gonzalo",
    languages: ["es-ES"],
    description:
      "Bright, expressive Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "bright",
      "expressive",
      "friendly",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Graham",
    name: "Graham",
    languages: ["en-GB"],
    description:
      "Profound, authoritative British male voice, perfect for historical documentaries, luxury brand advertisements, and educational content.",
    gender: "male",
    tags: [
      "profound",
      "authoritative",
      "sophisticated",
      "british",
      "interactive media",
      "narrative",
      "character",
    ],
  },
  {
    id: "Grant",
    name: "Grant",
    languages: ["en-US"],
    description:
      "Calm, attentive, helpful male voice, ideal for insurance claims, troubleshooting walkthroughs, and helpdesk interactions.",
    gender: "male",
    tags: ["calm", "attentive", "helpful", "customer support"],
  },
  {
    id: "Grigory",
    name: "Grigory",
    languages: ["ru-RU"],
    description:
      "Clear, grounded Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "clear",
      "grounded",
      "measured",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Guadalupe",
    name: "Guadalupe",
    languages: ["es-MX"],
    description:
      "Clear, approachable Mexican Spanish female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "clear",
      "approachable",
      "cheerful",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Hades",
    name: "Hades",
    languages: ["en-US"],
    description:
      "Commanding and gruff male voice, think an omniscient narrator or castle guard",
    gender: "male",
    tags: [
      "commanding",
      "gruff",
      "interactive media",
      "character",
      "narrative",
    ],
  },
  {
    id: "Hamish",
    name: "Hamish",
    languages: ["en-AU"],
    description:
      "Friendly and casual Australian male voice, ideal for character-driven roles and upbeat fitness.",
    gender: "male",
    tags: [
      "calm",
      "trustworthy",
      "comforting",
      "australian",
      "interactive media",
      "character",
      "companion",
      "fitness coach",
    ],
  },
  {
    id: "Hana",
    name: "Hana",
    languages: ["en-US"],
    description:
      "Bright, expressive young female voice, perfect for storytelling, gaming, and playful content",
    gender: "female",
    tags: ["bright", "playful", "interactive media", "character", "narrative"],
  },
  {
    id: "Hank",
    name: "Hank",
    languages: ["en-US"],
    description:
      "Warm, laid-back Southern male voice, ideal for travel documentaries, heritage storytelling, and down-to-earth podcast ads.",
    gender: "male",
    tags: [
      "warm",
      "laid-back",
      "authentic",
      "southern",
      "interactive media",
      "narrative",
      "character",
    ],
  },
  {
    id: "Harold",
    name: "Harold",
    languages: ["en-US"],
    description: "Crisp, seasoned older male voice with a trustworthy delivery",
    gender: "male",
    tags: [
      "crisp",
      "seasoned",
      "trustworthy",
      "advertisement",
      "narration",
      "storytelling",
    ],
  },
  {
    id: "Haruto",
    name: "Haruto",
    languages: ["ja-JP"],
    description:
      "A slow, deliberate, and gravelly old male voice speaking in a reminiscent tone.",
    gender: "male",
    tags: ["narrative", "character"],
  },
  {
    id: "Hazel",
    name: "Hazel",
    languages: ["en-US"],
    description: "Warm, upbeat female voice with a friendly, engaging tone",
    gender: "female",
    tags: [
      "upbeat",
      "warm",
      "friendly",
      "education & training",
      "tutoring",
      "customer support",
    ],
  },
  {
    id: "Heidi",
    name: "Heidi",
    languages: ["de-DE"],
    description:
      "Warm, engaging German female voice, ideal for business, e-learning, and narration.",
    gender: "female",
    tags: [
      "warm",
      "engaging",
      "clear",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Heike",
    name: "Heike",
    languages: ["de-DE"],
    description:
      "Bright, natural German female voice, ideal for business, e-learning, and narration.",
    gender: "female",
    tags: [
      "bright",
      "natural",
      "poised",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Heitor",
    name: "Heitor",
    languages: ["pt-BR"],
    description: "Composed Portuguese-speaking male voice with a neutral tone",
    gender: "male",
    tags: ["calm", "demanding"],
  },
  {
    id: "Hendrik",
    name: "Hendrik",
    languages: ["de-DE"],
    description:
      "Bright, approachable German male voice, ideal for business, e-learning, and narration.",
    gender: "male",
    tags: [
      "bright",
      "approachable",
      "articulate",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Hina",
    name: "Hina",
    languages: ["ja-JP"],
    description:
      "A young adult female with a smooth, clear voice speaking in a formal, narrative tone.",
    gender: "female",
    tags: ["clear", "articulate"],
  },
  {
    id: "Huiling",
    name: "Huiling",
    languages: ["en-SG"],
    description:
      "Bright, approachable Singaporean female voice, ideal for e-learning, customer service, and support.",
    gender: "female",
    tags: [
      "bright",
      "approachable",
      "warm",
      "singaporean",
      "education & training",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Hyunwoo",
    name: "Hyunwoo",
    languages: ["ko-KR"],
    description: "Young adult Korean male voice",
    gender: "male",
    tags: ["polite", "warm"],
  },
  {
    id: "Hélène",
    name: "Hélène",
    languages: ["fr-FR"],
    description:
      "Middle-aged French woman, with a smooth, musical, and graceful voice",
    gender: "female",
    tags: ["expressive", "soothing"],
  },
  {
    id: "Ignacio",
    name: "Ignacio",
    languages: ["es-ES"],
    description:
      "Calm, refined Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "calm",
      "refined",
      "steady",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Imogen",
    name: "Imogen",
    languages: ["en-GB"],
    description:
      "Refined British female voice with a professional, articulate delivery",
    gender: "female",
    tags: [
      "professional",
      "refined",
      "articulate",
      "british",
      "narration",
      "education & training",
    ],
  },
  {
    id: "Indi",
    name: "Indi",
    languages: ["en-AU"],
    description:
      "Bright, casual Australian female voice, ideal for lifestyle content, travel, and casual narration.",
    gender: "female",
    tags: [
      "bright",
      "casual",
      "relaxed",
      "australian",
      "lifestyle",
      "travel",
      "narration",
      "interactive media",
    ],
  },
  {
    id: "Inigo",
    name: "Inigo",
    languages: ["es-ES"],
    description:
      "Clear, composed Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "clear",
      "composed",
      "professional",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Inmaculada",
    name: "Inmaculada",
    languages: ["es-ES"],
    description:
      "Warm, articulate Castilian Spanish female voice, ideal for education, narration, and business.",
    gender: "female",
    tags: [
      "warm",
      "articulate",
      "engaging",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Ishaan",
    name: "Ishaan",
    languages: ["en-IN"],
    description:
      "Confident, natural Indian male voice, ideal for customer support, corporate, and education.",
    gender: "male",
    tags: [
      "confident",
      "natural",
      "approachable",
      "indian",
      "customer support",
      "corporate",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Itzel",
    name: "Itzel",
    languages: ["es-MX"],
    description:
      "Warm, conversational Mexican Spanish female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "warm",
      "conversational",
      "friendly",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Jake",
    name: "Jake",
    languages: ["en-US"],
    description:
      "Amiable, introspective male voice, ideal for motivational talks, personal growth content, and charming interviews.",
    gender: "male",
    tags: ["amiable", "introspective", "charming"],
  },
  {
    id: "James",
    name: "James",
    languages: ["en-US"],
    description:
      "Vibrant, expressive male voice, perfect for animated video content, lively event hosting, and captivating children's stories.",
    gender: "male",
    tags: [
      "vibrant",
      "expressive",
      "captivating",
      "interactive media",
      "character",
    ],
  },
  {
    id: "Jarrah",
    name: "Jarrah",
    languages: ["en-AU"],
    description:
      "Easygoing, grounded Australian male voice, ideal for lifestyle content, travel, and casual narration.",
    gender: "male",
    tags: [
      "easygoing",
      "grounded",
      "friendly",
      "australian",
      "lifestyle",
      "travel",
      "narration",
      "interactive media",
    ],
  },
  {
    id: "Jason",
    name: "Jason",
    languages: [
      "en-US",
      "ar-SA",
      "de-DE",
      "es-MX",
      "ja-JP",
      "ko-KR",
      "pt-BR",
      "ru-RU",
      "zh-CN",
    ],
    description:
      "Lucid, engrossing male voice, ideal for tech tips, creative productivity hacks, and supportive user interface tutorials.",
    gender: "male",
    tags: [
      "lucid",
      "engrossing",
      "supportive",
      "companion",
      "general purpose assistant",
      "developer assistant",
      "education & training",
      "tutoring",
    ],
  },
  {
    id: "Jessica",
    name: "Jessica",
    languages: ["en-US"],
    description:
      "Encouraging, articulate American female voice, perfect for self-help audiobooks, warm customer service messages, and clear e-learning modules.",
    gender: "female",
    tags: [
      "encouraging",
      "articulate",
      "warm",
      "customer support",
      "companion",
      "personal growth",
    ],
  },
  {
    id: "Jing",
    name: "Jing",
    languages: ["zh-CN"],
    description: "An energetic, fast-paced young Chinese female",
    gender: "female",
    tags: ["soft", "clear"],
  },
  {
    id: "Joaquin",
    name: "Joaquin",
    languages: ["es-ES"],
    description:
      "Warm, articulate Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "warm",
      "articulate",
      "engaging",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Johanna",
    name: "Johanna",
    languages: ["de-DE"],
    description: "A calm older German female with a low, smoky voice",
    gender: "female",
    tags: ["rich", "deep"],
  },
  {
    id: "Jonah",
    name: "Jonah",
    languages: ["en-US"],
    description:
      "Soothing, calm male voice, great for tutorial guidance, reassuring support flows, and gentle instructional narration with steady pacing.",
    gender: "male",
    tags: [
      "soothing",
      "breathy",
      "calm",
      "customer support",
      "tutoring",
      "general purpose assistant",
    ],
  },
  {
    id: "Josef",
    name: "Josef",
    languages: ["de-DE"],
    description:
      "An articulate German male voice with an announcer-like quality",
    gender: "male",
    tags: ["resonant", "clear"],
  },
  {
    id: "Joy",
    name: "Joy",
    languages: ["en-US"],
    description:
      "Gentle, steady female voice, ideal for customer support, sensitive contexts, and help lines.",
    gender: "female",
    tags: [
      "gentle",
      "steady",
      "reassuring",
      "customer support",
      "sensitive support",
      "enterprise",
      "healthcare",
    ],
  },
  {
    id: "Julia",
    name: "Julia",
    languages: ["en-US"],
    description:
      "Quirky, high-pitched female voice that delivers lines with playful energy",
    gender: "female",
    tags: ["childish", "quirky"],
  },
  {
    id: "Junhao",
    name: "Junhao",
    languages: ["en-SG"],
    description:
      "Bright, easygoing Singaporean male voice, ideal for e-learning, customer service, and support.",
    gender: "male",
    tags: [
      "bright",
      "easygoing",
      "warm",
      "singaporean",
      "education & training",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Kabir",
    name: "Kabir",
    languages: ["en-IN"],
    description:
      "Bright, helpful Indian male voice, ideal for customer support, corporate, and education.",
    gender: "male",
    tags: [
      "bright",
      "helpful",
      "poised",
      "indian",
      "customer support",
      "corporate",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Katrien",
    name: "Katrien",
    languages: ["nl-NL"],
    description: "Dutch woman with an expressive voice",
    gender: "female",
    tags: ["bright", "melodic"],
  },
  {
    id: "Kayla",
    name: "Kayla",
    languages: ["en-US"],
    description:
      "Enthusiastic, youthful female voice, ideal for reaction videos, trendy product reviews, and energetic lifestyle vlogs.",
    gender: "female",
    tags: ["enthusiastic", "youthful", "energetic"],
  },
  {
    id: "Kelsey",
    name: "Kelsey",
    languages: ["en-US"],
    description:
      "Warm, empathetic, reassuring female voice, ideal for phone support, appointment confirmations, and customer success calls.",
    gender: "female",
    tags: [
      "warm",
      "empathetic",
      "reassuring",
      "customer support",
      "companion",
      "general purpose assistant",
      "education & training",
      "professional training",
      "enterprise",
    ],
  },
  {
    id: "Kenji",
    name: "Kenji",
    languages: ["en-US"],
    description:
      "Stylized, low-key male voice, ideal for anime content, gaming, and dubbing.",
    gender: "male",
    tags: [
      "stylized",
      "low-key",
      "composed",
      "gaming",
      "anime",
      "character",
      "interactive media",
      "companion",
    ],
  },
  {
    id: "Kilian",
    name: "Kilian",
    languages: ["de-DE"],
    description:
      "Warm, natural German male voice, ideal for business, e-learning, and narration.",
    gender: "male",
    tags: [
      "warm",
      "natural",
      "engaging",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Larissa",
    name: "Larissa",
    languages: ["pt-BR"],
    description:
      "Bright, friendly Brazilian Portuguese female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "bright",
      "friendly",
      "expressive",
      "brazilian",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Lauren",
    name: "Lauren",
    languages: ["en-US"],
    description:
      "Confident, friendly American female voice, ideal for corporate presentations, upbeat commercials, and engaging podcasts.",
    gender: "female",
    tags: [
      "confident",
      "friendly",
      "engaging",
      "education & training",
      "tutoring",
      "professional training",
      "enterprise",
      "customer support",
    ],
  },
  {
    id: "Lennart",
    name: "Lennart",
    languages: ["nl-NL"],
    description: "A confident Dutch male voice. Calm and relaxed",
    gender: "male",
    tags: ["authoritative", "robust"],
  },
  {
    id: "Leonor",
    name: "Leonor",
    languages: ["pt-PT"],
    description:
      "Clear, composed European Portuguese female voice, ideal for education, narration, and business.",
    gender: "female",
    tags: [
      "clear",
      "composed",
      "refined",
      "european portuguese",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Lev",
    name: "Lev",
    languages: ["ru-RU"],
    description:
      "Confident, approachable Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "confident",
      "approachable",
      "steady",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Levi",
    name: "Levi",
    languages: ["en-US"],
    description:
      "Measured, ominous male voice, ideal for suspense narration, dark fantasy storytelling, and composed dramatic monologues.",
    gender: "male",
    tags: [
      "ominous",
      "deliberate",
      "measured",
      "meditation",
      "narrative",
      "spiritual support",
    ],
  },
  {
    id: "Liam",
    name: "Liam",
    languages: ["en-AU"],
    description:
      "Upbeat, motivating Australian male voice, perfect for energizing workout sessions, lively event promotions, and informal lifestyle content.",
    gender: "male",
    tags: [
      "upbeat",
      "motivating",
      "informal",
      "australian",
      "companion",
      "fitness coach",
      "personal growth",
    ],
  },
  {
    id: "Liwa",
    name: "Liwa",
    languages: ["en-PH"],
    description:
      "Gentle, patient Filipino female voice, ideal for customer service, e-learning, and support.",
    gender: "female",
    tags: [
      "gentle",
      "patient",
      "clear",
      "filipino",
      "customer support",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Lore",
    name: "Lore",
    languages: ["nl-NL"],
    description:
      "Clear, calm Dutch female voice, great for narrations and professional use cases",
    gender: "female",
    tags: ["strong", "clear"],
  },
  {
    id: "Loretta",
    name: "Loretta",
    languages: ["en-US"],
    description:
      "Inviting, folksy Southern female voice, perfect for cooking shows, heartwarming family tales, and cozy radio ads.",
    gender: "female",
    tags: [
      "inviting",
      "folksy",
      "charming",
      "southern",
      "interactive media",
      "character",
      "narrative",
    ],
  },
  {
    id: "Lucian",
    name: "Lucian",
    languages: ["en-US"],
    description:
      "Brooding, foreboding male voice, suited for villainous character arcs, gothic drama scenes, and dark narrative worldbuilding.",
    gender: "male",
    tags: ["brooding", "intense", "foreboding", "character", "narrative"],
  },
  {
    id: "Luna",
    name: "Luna",
    languages: ["en-US"],
    description:
      "Calm, relaxing female voice, perfect for meditations, sleep stories, and mindfulness exercises",
    gender: "female",
    tags: [
      "calm",
      "relaxed",
      "companion app",
      "social",
      "healthcare",
      "spiritual support",
    ],
  },
  {
    id: "Lupita",
    name: "Lupita",
    languages: ["es-ES"],
    description: "Vibrant, energetic young Spanish-speaking female voice",
    gender: "female",
    tags: ["lively", "bright"],
  },
  {
    id: "Madalena",
    name: "Madalena",
    languages: ["pt-PT"],
    description:
      "Bright, natural European Portuguese female voice, ideal for education, narration, and business.",
    gender: "female",
    tags: [
      "bright",
      "natural",
      "poised",
      "european portuguese",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Maisie",
    name: "Maisie",
    languages: ["en-GB"],
    description:
      "Engaging young British female voice, perfect for interactive media and casual narration.",
    gender: "female",
    tags: [
      "approachable",
      "clear",
      "conversational",
      "engaging",
      "expressive",
      "natural",
    ],
  },
  {
    id: "Maitê",
    name: "Maitê",
    languages: ["pt-BR"],
    description: "Middle-aged Portuguese-speaking female voice",
    gender: "female",
    tags: ["reassuring", "clear", "customer support"],
  },
  {
    id: "Malcolm",
    name: "Malcolm",
    languages: ["en-US"],
    description:
      "Authoritative, manipulative male voice, perfect for cunning leaders, intense negotiation scenes, and persuasive villain speeches.",
    gender: "male",
    tags: [
      "authoritative",
      "manipulative",
      "persuasive",
      "interactive media",
      "character",
      "companion",
      "social",
    ],
  },
  {
    id: "Manoj",
    name: "Manoj",
    languages: ["hi-IN"],
    description:
      "Clear, professional Hindi male voice. Great for narrations, news anchors, and customer service.",
    gender: "male",
    tags: ["professional", "clean", "customer support"],
  },
  {
    id: "Marcus",
    name: "Marcus",
    languages: ["en-US"],
    description:
      "Authoritative, empathetic male voice, great for civic campaigns, community outreach explainers, and trustworthy commercial reads with emotional credibility.",
    gender: "male",
    tags: [
      "authoritative",
      "empathetic",
      "believable",
      "ads",
      "customer support",
      "general purpose assistant",
    ],
  },
  {
    id: "Mariana",
    name: "Mariana",
    languages: ["pt-BR"],
    description:
      "A young, enthusiastic female speaker with a clear, smooth voice and a Brazilian Portuguese accent, speaking at a moderate pace in a high-quality recording environment.",
    gender: "female",
    tags: ["upbeat", "motivational"],
  },
  {
    id: "Maricel",
    name: "Maricel",
    languages: ["en-PH"],
    description:
      "Friendly, warm Filipino female voice, ideal for customer service, e-learning, and support.",
    gender: "female",
    tags: [
      "friendly",
      "warm",
      "helpful",
      "filipino",
      "customer support",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Mark",
    name: "Mark",
    languages: ["en-US"],
    description: "Energetic, expressive man with a rapid-fire delivery",
    gender: "male",
    tags: [
      "articulate",
      "engaging",
      "enterprise",
      "customer support",
      "education & training",
      "professional training",
    ],
  },
  {
    id: "Marlene",
    name: "Marlene",
    languages: ["en-US"],
    description:
      "Friendly, relaxed Southern female voice, ideal for home-style cooking tutorials, community event promotions, and downhome commercials.",
    gender: "female",
    tags: [
      "friendly",
      "relaxed",
      "down-to-earth",
      "southern",
      "interactive media",
      "character",
      "narrative",
      "education & training",
      "tutorials",
    ],
  },
  {
    id: "Marta",
    name: "Marta",
    languages: ["es-ES"],
    description:
      "Friendly, expressive Castilian Spanish female voice, ideal for education, narration, and business.",
    gender: "female",
    tags: [
      "friendly",
      "expressive",
      "approachable",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Mateo",
    name: "Mateo",
    languages: ["es-MX"],
    description:
      "A young adult male with a smooth, clear voice speaking thoughtfully in a quiet studio setting.",
    gender: "male",
    tags: ["friendly", "conversational"],
  },
  {
    id: "Mathieu",
    name: "Mathieu",
    languages: ["fr-FR"],
    description: "A French male voice carrying a nasal quality",
    gender: "male",
    tags: ["robust", "strong"],
  },
  {
    id: "Matilda",
    name: "Matilda",
    languages: ["en-AU"],
    description:
      "Friendly, upbeat Australian female voice, ideal for lifestyle content, travel, and casual narration.",
    gender: "female",
    tags: [
      "friendly",
      "upbeat",
      "warm",
      "australian",
      "lifestyle",
      "travel",
      "narration",
      "interactive media",
    ],
  },
  {
    id: "Matilde",
    name: "Matilde",
    languages: ["pt-PT"],
    description:
      "Warm, melodic European Portuguese female voice, ideal for education, narration, and business.",
    gender: "female",
    tags: [
      "warm",
      "melodic",
      "measured",
      "european portuguese",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Matthias",
    name: "Matthias",
    languages: ["de-DE"],
    description:
      "Resonant, authoritative German male voice, ideal for business, e-learning, and narration.",
    gender: "male",
    tags: [
      "resonant",
      "authoritative",
      "steady",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Mauricio",
    name: "Mauricio",
    languages: ["es-MX"],
    description:
      "A serious adult male with a smooth, clear voice speaking slowly and deliberately in a quiet studio environment.",
    gender: "male",
    tags: ["narrative", "spiritual"],
  },
  {
    id: "Maximiliano",
    name: "Maximiliano",
    languages: ["es-MX"],
    description:
      "Bright, natural Mexican Spanish male voice, ideal for education, narration, and customer service.",
    gender: "male",
    tags: [
      "bright",
      "natural",
      "engaging",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Mayte",
    name: "Mayte",
    languages: ["es-MX"],
    description:
      "Clear, approachable Mexican Spanish female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "clear",
      "approachable",
      "cheerful",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Meher",
    name: "Meher",
    languages: ["hi-IN"],
    description:
      "A warm, friendly young adult female with a North Indian urban accent, speaking naturally and conversationally.",
    gender: "female",
    tags: [
      "warm",
      "friendly",
      "conversational",
      "natural",
      "customer support",
      "assistant",
    ],
  },
  {
    id: "Mei",
    name: "Mei",
    languages: ["zh-CN"],
    description:
      "A young female with a smooth, clear voice and standard Mandarin accent, speaking at a moderate pace in a quiet studio environment.",
    gender: "female",
    tags: ["clear", "warm"],
  },
  {
    id: "Mercedes",
    name: "Mercedes",
    languages: ["es-ES"],
    description:
      "Bright, natural Castilian Spanish female voice, ideal for education, narration, and business.",
    gender: "female",
    tags: [
      "bright",
      "natural",
      "poised",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Mia",
    name: "Mia",
    languages: ["en-US"],
    description:
      "Youthful, expressive female voice, ideal for adolescent characters, school-age animation dialogue, and bright coming-of-age narrative scenes.",
    gender: "female",
    tags: ["youthful", "expressive", "natural", "character", "kids media"],
  },
  {
    id: "Miguel",
    name: "Miguel",
    languages: ["es-ES"],
    description:
      "A calm adult Spanish-speaking male voice, perfect for storytelling",
    gender: "male",
    tags: ["warm", "bright"],
  },
  {
    id: "Ming",
    name: "Ming",
    languages: ["zh-CN"],
    description:
      "A young adult male with a smooth, clear voice speaking slowly and deliberately in a quiet environment.",
    gender: "male",
    tags: ["clear", "professional"],
  },
  {
    id: "Minji",
    name: "Minji",
    languages: ["ko-KR"],
    description: "Energetic, friendly young Korean female voice",
    gender: "female",
    tags: ["light", "bright"],
  },
  {
    id: "Miranda",
    name: "Miranda",
    languages: ["en-US"],
    description:
      "Menacing, cold-hearted female voice, perfect for strategic villains, mysterious narratives",
    gender: "female",
    tags: ["menacing", "dominant", "interactive media", "character"],
  },
  {
    id: "Morgana",
    name: "Morgana",
    languages: ["en-US"],
    description:
      "Cold, calculated female voice, ideal for gaming, audiobook villains, and horror.",
    gender: "female",
    tags: [
      "cold",
      "calculated",
      "theatrical",
      "gaming",
      "villain",
      "character",
      "interactive media",
      "companion",
    ],
  },
  {
    id: "Mortimer",
    name: "Mortimer",
    languages: ["en-US"],
    description:
      "Gravelly, aggressive male character voice, ideal for fantasy villains and high-intensity game dialogue.",
    gender: "male",
    tags: [
      "gravelly",
      "menacing",
      "whimsical",
      "interactive media",
      "character",
    ],
  },
  {
    id: "Murilo",
    name: "Murilo",
    languages: ["pt-BR"],
    description:
      "A calm and analytical adult male with a clear, standard Brazilian Portuguese accent, speaking at a moderate pace in a quiet environment.",
    gender: "male",
    tags: ["professional", "articulate"],
  },
  {
    id: "Nacho",
    name: "Nacho",
    languages: ["es-ES"],
    description:
      "Confident, grounded Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "confident",
      "grounded",
      "measured",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Nadia",
    name: "Nadia",
    languages: ["en-US"],
    description:
      "Personable, lively female voice, perfect for tutorial walkthroughs, friendly support messaging, and engaging narration for creator-led product content.",
    gender: "female",
    tags: [
      "breathy",
      "personable",
      "lively",
      "customer support",
      "tutoring",
      "narrative",
    ],
  },
  {
    id: "Naomi",
    name: "Naomi",
    languages: ["en-US"],
    description:
      "Warm, grounded female voice, perfect for narrative podcasting, people-first customer guidance, and emotionally real brand storytelling.",
    gender: "female",
    tags: [
      "warm",
      "grounded",
      "versatile",
      "narrative",
      "customer support",
      "general purpose assistant",
    ],
  },
  {
    id: "Nate",
    name: "Nate",
    languages: ["en-US"],
    description:
      "Conversational, sociable male voice, great for customer support and friendly guidance",
    gender: "male",
    tags: [
      "laid-back",
      "engaging",
      "sociable",
      "enterprise",
      "customer support",
      "healthcare",
      "patient support",
      "companion",
      "general purpose assistant",
    ],
  },
  {
    id: "Nigel",
    name: "Nigel",
    languages: ["en-GB"],
    description: "Formal British male voice with a precise, measured delivery",
    gender: "male",
    tags: [
      "formal",
      "precise",
      "british",
      "education & training",
      "professional training",
      "enterprise",
    ],
  },
  {
    id: "Nikhil",
    name: "Nikhil",
    languages: ["en-IN"],
    description:
      "Articulate, warm Indian male voice, ideal for customer support, corporate, and education.",
    gender: "male",
    tags: [
      "articulate",
      "warm",
      "engaging",
      "indian",
      "customer support",
      "corporate",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Nikolai",
    name: "Nikolai",
    languages: ["ru-RU"],
    description:
      "Deep, resonant male voice, delivered at a measured pace with a clear, theatrical, and narrative quality.",
    gender: "male",
    tags: ["deep", "dramatic"],
  },
  {
    id: "Nour",
    name: "Nour",
    languages: ["ar-SA"],
    description:
      "Polished female Arabic voice with a friendly tone, great for voice over or support.",
    gender: "female",
    tags: ["polished", "friendly", "customer support"],
  },
  {
    id: "Oksana",
    name: "Oksana",
    languages: ["ru-RU"],
    description:
      "Composed, poised Russian female voice, ideal for narration, education, and customer service.",
    gender: "female",
    tags: [
      "composed",
      "poised",
      "approachable",
      "russian",
      "narration",
      "education & training",
      "customer support",
      "interactive media",
    ],
  },
  {
    id: "Oliver",
    name: "Oliver",
    languages: ["en-US"],
    description:
      "Neutral and clear male voice, ideal for public announcements and educational information.",
    gender: "male",
    tags: [
      "neutral",
      "informative",
      "clear",
      "companion",
      "general purpose assistant",
      "education & training",
      "language learning",
    ],
  },
  {
    id: "Olivia",
    name: "Olivia",
    languages: [
      "en-GB",
      "ar-SA",
      "de-DE",
      "es-MX",
      "ja-JP",
      "ko-KR",
      "pt-BR",
      "ru-RU",
      "zh-CN",
    ],
    description:
      "Young, British female with a friendly and helpful tone, conveying confidence and efficiency.",
    gender: "female",
    tags: [
      "cute",
      "british",
      "customer support",
      "healthcare",
      "patient support",
      "education & training",
      "tutoring",
    ],
  },
  {
    id: "Omar",
    name: "Omar",
    languages: ["ar-SA"],
    description:
      "Bright, confident Arabic male voice, great for announcements, broadcasts, and voice overs.",
    gender: "male",
    tags: ["bright", "confident"],
  },
  {
    id: "Oren",
    name: "Oren",
    languages: ["he-IL"],
    description:
      "Steady male Hebrew voice, great for podcasts, voice overs, or announcers.",
    gender: "male",
    tags: ["steady", "professional"],
  },
  {
    id: "Orietta",
    name: "Orietta",
    languages: ["it-IT"],
    description: "Calm adult female Italian voice, with a soothing cadence",
    gender: "female",
    tags: ["warm", "smooth"],
  },
  {
    id: "Paloma",
    name: "Paloma",
    languages: ["es-MX"],
    description:
      "Warm, conversational Mexican Spanish female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "warm",
      "conversational",
      "friendly",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Patricia",
    name: "Patricia",
    languages: ["pt-BR"],
    description:
      "Bright, friendly Brazilian Portuguese female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "bright",
      "friendly",
      "expressive",
      "brazilian",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Penelope",
    name: "Penelope",
    languages: ["en-GB"],
    description:
      "A clear, refined British female voice suited for health and lifestyle assistance.",
    gender: "female",
    tags: [
      "articulate",
      "clear",
      "polite",
      "refined",
      "helpful",
      "informative",
    ],
  },
  {
    id: "Pilar",
    name: "Pilar",
    languages: ["es-ES"],
    description:
      "Clear, composed Castilian Spanish female voice, ideal for education, narration, and business.",
    gender: "female",
    tags: [
      "clear",
      "composed",
      "professional",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Piper",
    name: "Piper",
    languages: ["en-US"],
    description:
      "Bright, playful young female voice with an upbeat conversational energy",
    gender: "female",
    tags: [
      "cute",
      "bright",
      "playful",
      "conversational",
      "companion",
      "social companion",
      "interactive media",
    ],
  },
  {
    id: "Pippa",
    name: "Pippa",
    languages: ["en-AU"],
    description:
      "Friendly and casual Australian female voice, ideal for relaxed instructional content.",
    gender: "female",
    tags: [
      "friendly",
      "casual",
      "australian",
      "education & training",
      "professional training",
      "tutoring",
    ],
  },
  {
    id: "Pixie",
    name: "Pixie",
    languages: ["en-US"],
    description:
      "High-pitched, childlike female voice with a squeaky quality - great for a cartoon character",
    gender: "female",
    tags: [
      "cartoonish",
      "high-pitched",
      "interactive media",
      "character",
      "education & training",
      "children",
    ],
  },
  {
    id: "Polina",
    name: "Polina",
    languages: ["ru-RU"],
    description:
      "Calm, warm Russian female voice, ideal for narration, education, and customer service.",
    gender: "female",
    tags: [
      "calm",
      "warm",
      "soothing",
      "russian",
      "narration",
      "education & training",
      "customer support",
      "interactive media",
    ],
  },
  {
    id: "Priya",
    name: "Priya",
    languages: ["en-IN"],
    description: "Even-toned female voice with an Indian accent",
    gender: "female",
    tags: ["friendly", "gentle"],
  },
  {
    id: "Rafael",
    name: "Rafael",
    languages: ["es-ES"],
    description:
      "Middle-aged Spanish-speaking male with a deep, composed voice. Great for narrations",
    gender: "male",
    tags: ["warm", "bright"],
  },
  {
    id: "Reed",
    name: "Reed",
    languages: ["en-US"],
    description:
      "Clear, professional American male voice, well-suited for support and training.",
    gender: "male",
    tags: [
      "clear",
      "professional",
      "customer support",
      "education & training",
      "tutoring",
      "general purpose assistant",
    ],
  },
  {
    id: "Reinhard",
    name: "Reinhard",
    languages: ["de-DE"],
    description:
      "Calm, refined German male voice, ideal for business, e-learning, and narration.",
    gender: "male",
    tags: [
      "calm",
      "refined",
      "poised",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Ren",
    name: "Ren",
    languages: ["en-US"],
    description:
      "Cool, aloof male voice, ideal for anime content, gaming, and dubbing.",
    gender: "male",
    tags: [
      "cool",
      "aloof",
      "controlled",
      "gaming",
      "anime",
      "character",
      "interactive media",
      "companion",
    ],
  },
  {
    id: "Renata",
    name: "Renata",
    languages: ["pt-BR"],
    description:
      "Calm, clear Brazilian Portuguese female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "calm",
      "clear",
      "approachable",
      "brazilian",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Riley",
    name: "Riley",
    languages: ["en-US"],
    description:
      "Playful, youthful female voice, perfect for animated storytelling, upbeat game characters, and high-energy kid-focused digital content.",
    gender: "female",
    tags: [
      "playful",
      "youthful",
      "energetic",
      "character",
      "kids media",
      "tutoring",
    ],
  },
  {
    id: "Riya",
    name: "Riya",
    languages: ["hi-IN"],
    description:
      "Professional and clean female voice, with a clear and articulate tone, moderate pace, and a polished, approachable quality.",
    gender: "female",
    tags: ["professional", "clean", "customer support"],
  },
  {
    id: "Rocio",
    name: "Rocio",
    languages: ["es-ES"],
    description:
      "Calm, refined Castilian Spanish female voice, ideal for education, narration, and business.",
    gender: "female",
    tags: [
      "calm",
      "refined",
      "measured",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Rodion",
    name: "Rodion",
    languages: ["ru-RU"],
    description:
      "Calm, articulate Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "calm",
      "articulate",
      "poised",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Ronald",
    name: "Ronald",
    languages: ["en-GB"],
    description: "Confident, British man with a deep, gravelly voice",
    gender: "male",
    tags: [
      "confident",
      "expressive",
      "british",
      "interactive media",
      "character",
      "narrative",
    ],
  },
  {
    id: "Rosalind",
    name: "Rosalind",
    languages: ["en-GB"],
    description:
      "Mature, warm British female voice, ideal for audiobooks, documentary, and narration.",
    gender: "female",
    tags: [
      "mature",
      "warm",
      "measured",
      "british",
      "audiobook",
      "narration",
      "documentary",
      "interactive media",
    ],
  },
  {
    id: "Ruben",
    name: "Ruben",
    languages: ["es-ES"],
    description:
      "Natural, poised Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "natural",
      "poised",
      "approachable",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Rupert",
    name: "Rupert",
    languages: [
      "en-GB",
      "ar-SA",
      "de-DE",
      "es-ES",
      "ja-JP",
      "pt-BR",
      "ru-RU",
      "zh-CN",
    ],
    description:
      "Resonant, commanding British male voice, ideal for motivational speeches, epic film trailers, and dynamic corporate presentations.",
    gender: "male",
    tags: [
      "resonant",
      "commanding",
      "motivational",
      "british",
      "interactive media",
      "character",
      "narrative",
    ],
  },
  {
    id: "Ruslan",
    name: "Ruslan",
    languages: ["ru-RU"],
    description:
      "Bright, engaging Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "bright",
      "engaging",
      "relaxed",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Saanvi",
    name: "Saanvi",
    languages: ["en-IN"],
    description:
      "Crisp, articulate Indian female voice, ideal for dynamic e-learning modules, articulate documentary narrations, and vibrant travel vlogs.",
    gender: "female",
    tags: [
      "crisp",
      "articulate",
      "dynamic",
      "indian",
      "education & training",
      "tutoring",
      "professional training",
      "enterprise",
    ],
  },
  {
    id: "Sabine",
    name: "Sabine",
    languages: ["de-DE"],
    description:
      "Calm, refined German female voice, ideal for business, e-learning, and narration.",
    gender: "female",
    tags: [
      "calm",
      "refined",
      "steady",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Salvador",
    name: "Salvador",
    languages: ["es-MX"],
    description:
      "Confident, expressive Mexican Spanish male voice, ideal for education, narration, and customer service.",
    gender: "male",
    tags: [
      "confident",
      "expressive",
      "poised",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Sarah",
    name: "Sarah",
    languages: [
      "en-US",
      "ar-SA",
      "de-DE",
      "es-MX",
      "ja-JP",
      "ko-KR",
      "pt-BR",
      "ru-RU",
      "zh-CN",
    ],
    description:
      "Fast-talking young adult woman, with a questioning and curious tone",
    gender: "female",
    tags: [
      "upbeat",
      "excited",
      "enterprise",
      "customer support",
      "sales automation",
      "companion",
      "general purpose assistant",
    ],
  },
  {
    id: "Satoshi",
    name: "Satoshi",
    languages: ["ja-JP"],
    description: "Dramatic, expressive male Japanese voice filled with energy",
    gender: "male",
    tags: ["nervous", "curious"],
  },
  {
    id: "Sebastian",
    name: "Sebastian",
    languages: ["en-US"],
    description:
      "Intimidating, steely male voice, perfect for ruthless antagonists, strategic power struggles, and chilling monologues.",
    gender: "male",
    tags: [
      "intimidating",
      "steely",
      "calculating",
      "interactive media",
      "character",
    ],
  },
  {
    id: "Seema",
    name: "Seema",
    languages: ["hi-IN"],
    description:
      "Clear, bright young female Hindi voice with a friendly, engaging tone and moderate pace, great for education and interactive media.",
    gender: "female",
    tags: ["clear", "friendly", "engaging", "conversational", "informative"],
  },
  {
    id: "Selene",
    name: "Selene",
    languages: ["en-US"],
    description:
      "Soft, flirtatious female voice, ideal for companion-style interactions, charming game dialogue, and emotionally playful character-driven story scenes.",
    gender: "female",
    tags: ["soft", "breathy", "flirtatious", "social companion", "character"],
  },
  {
    id: "Seojun",
    name: "Seojun",
    languages: ["ko-KR"],
    description: "Clear, deep mature Korean male voice",
    gender: "male",
    tags: ["deep", "authoritative"],
  },
  {
    id: "Serena",
    name: "Serena",
    languages: ["en-US"],
    description:
      "Soft, nurturing female voice, perfect for mindfulness sessions, nature-inspired visualizations, and gentle wellness podcasts.",
    gender: "female",
    tags: [
      "soft",
      "nurturing",
      "gentle",
      "healthcare",
      "mental health",
      "spiritual",
      "companion",
      "social",
    ],
  },
  {
    id: "Serene",
    name: "Serene",
    languages: ["en-SG"],
    description:
      "Natural, poised Singaporean female voice, ideal for e-learning, customer service, and support.",
    gender: "female",
    tags: [
      "natural",
      "poised",
      "cheerful",
      "singaporean",
      "education & training",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Sergio",
    name: "Sergio",
    languages: ["es-ES"],
    description:
      "Confident, grounded Castilian Spanish male voice, ideal for education, narration, and business.",
    gender: "male",
    tags: [
      "confident",
      "grounded",
      "measured",
      "castilian",
      "education & training",
      "narration",
      "business",
      "enterprise",
    ],
  },
  {
    id: "Shaun",
    name: "Shaun",
    languages: ["en-US"],
    description: "Friendly, dynamic male voice great for conversations",
    gender: "male",
    tags: ["calm", "casual"],
  },
  {
    id: "Shreya",
    name: "Shreya",
    languages: ["hi-IN"],
    description:
      "Clear, bright young female Hindi voice with a friendly, helpful tone, ideal for virtual assistants and customer support.",
    gender: "female",
    tags: ["friendly", "conversational", "assistant", "customer support"],
  },
  {
    id: "Shu",
    name: "Shu",
    languages: ["en-SG"],
    description:
      "Confident, friendly Singaporean female voice, ideal for e-learning, customer service, and support.",
    gender: "female",
    tags: [
      "confident",
      "friendly",
      "clear",
      "singaporean",
      "education & training",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Simon",
    name: "Simon",
    languages: ["en-US"],
    description:
      "Articulate, insightful male voice, perfect for corporate presentations, technical tutorials, and steady news reporting.",
    gender: "male",
    tags: [
      "articulate",
      "insightful",
      "steady",
      "companion",
      "general purpose assistant",
      "interactive media",
      "narrative",
      "enterprise",
    ],
  },
  {
    id: "Snezhana",
    name: "Snezhana",
    languages: ["ru-RU"],
    description:
      "Calm, warm Russian female voice, ideal for narration, education, and customer service.",
    gender: "female",
    tags: [
      "calm",
      "warm",
      "soothing",
      "russian",
      "narration",
      "education & training",
      "customer support",
      "interactive media",
    ],
  },
  {
    id: "Snik",
    name: "Snik",
    languages: ["en-US"],
    description:
      "Hoarse, cunning male voice, perfect for devious goblin roles, fantasy heist scenarios, and trickster-themed animations.",
    gender: "male",
    tags: ["hoarse", "cunning", "avaricious", "interactive media", "character"],
  },
  {
    id: "Sofia",
    name: "Sofia",
    languages: ["es-MX"],
    description:
      "A fast-paced, clear, and engaging adult female voice with a neutral Latin American Spanish accent, recorded in a high-quality studio environment.",
    gender: "female",
    tags: ["warm", "conversational"],
  },
  {
    id: "Sophie",
    name: "Sophie",
    languages: ["en-GB"],
    description:
      "Friendly British female voice, great for assistance and knowledge sharing.",
    gender: "female",
    tags: [
      "friendly",
      "warm",
      "customer support",
      "education & training",
      "general purpose assistant",
      "knowledge sharing",
    ],
  },
  {
    id: "Steffi",
    name: "Steffi",
    languages: ["de-DE"],
    description:
      "Composed, professional German female voice, ideal for business, e-learning, and narration.",
    gender: "female",
    tags: [
      "composed",
      "professional",
      "measured",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Stepan",
    name: "Stepan",
    languages: ["ru-RU"],
    description:
      "Clear, grounded Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "clear",
      "grounded",
      "measured",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Svetlana",
    name: "Svetlana",
    languages: ["ru-RU"],
    description:
      "Soft, high-pitched female voice, with a moderate pace and slightly breathy quality.",
    gender: "female",
    tags: ["high-pitched", "soft"],
  },
  {
    id: "Szymon",
    name: "Szymon",
    languages: ["pl-PL"],
    description: "Polish adult male voice with a warm, friendly quality",
    gender: "male",
    tags: ["fast", "soft"],
  },
  {
    id: "Tahlia",
    name: "Tahlia",
    languages: ["en-AU"],
    description:
      "Sunny, easygoing Australian female voice, ideal for lifestyle content, travel, and casual narration.",
    gender: "female",
    tags: [
      "sunny",
      "easygoing",
      "natural",
      "australian",
      "lifestyle",
      "travel",
      "narration",
      "interactive media",
    ],
  },
  {
    id: "Tala",
    name: "Tala",
    languages: ["en-PH"],
    description:
      "Friendly, warm Filipino female voice, ideal for customer service, e-learning, and support.",
    gender: "female",
    tags: [
      "friendly",
      "warm",
      "helpful",
      "filipino",
      "customer support",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Tamara",
    name: "Tamara",
    languages: ["ru-RU"],
    description:
      "Gentle, natural Russian female voice, ideal for narration, education, and customer service.",
    gender: "female",
    tags: [
      "gentle",
      "natural",
      "measured",
      "russian",
      "narration",
      "education & training",
      "customer support",
      "interactive media",
    ],
  },
  {
    id: "Tatiana",
    name: "Tatiana",
    languages: ["pt-BR"],
    description:
      "Lively, natural Brazilian Portuguese female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "lively",
      "natural",
      "welcoming",
      "brazilian",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Tessa",
    name: "Tessa",
    languages: ["en-AU"],
    description:
      "Upbeat, conversational Australian female voice, perfect for lifestyle vlogs, playful advertisements, and engaging social media content.",
    gender: "female",
    tags: [
      "upbeat",
      "conversational",
      "lighthearted",
      "australian",
      "interactive media",
      "narrative",
    ],
  },
  {
    id: "Theodore",
    name: "Theodore",
    languages: ["en-US"],
    description: "Gravelly male voice, with a time-worn quality",
    gender: "male",
    tags: ["elderly", "wise", "interactive media", "character", "narrative"],
  },
  {
    id: "Timofey",
    name: "Timofey",
    languages: ["ru-RU"],
    description:
      "Natural, conversational Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "natural",
      "conversational",
      "warm",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Timothy",
    name: "Timothy",
    languages: ["en-US"],
    description: "Lively, upbeat American male voice",
    gender: "male",
    tags: ["hyped", "upbeat", "education & training", "tutoring"],
  },
  {
    id: "Tobias",
    name: "Tobias",
    languages: ["de-DE"],
    description:
      "Confident, grounded German male voice, ideal for business, e-learning, and narration.",
    gender: "male",
    tags: [
      "confident",
      "grounded",
      "measured",
      "german",
      "business",
      "education & training",
      "narration",
      "enterprise",
    ],
  },
  {
    id: "Trevor",
    name: "Trevor",
    languages: ["en-US"],
    description:
      "Punchy, expressive male voice, perfect for energetic promos, announcer-driven reveals, and fast-moving scripted event intros.",
    gender: "male",
    tags: ["punchy", "expressive", "upbeat", "news", "ads", "sports"],
  },
  {
    id: "Tristan",
    name: "Tristan",
    languages: ["en-US"],
    description:
      "Deliberate, controlled male voice, ideal for documentary narration, polished voiceover campaigns, and clear long-form infomercial storytelling.",
    gender: "male",
    tags: [
      "soothing",
      "deliberate",
      "controlled",
      "narrative",
      "ads",
      "customer support",
    ],
  },
  {
    id: "Tunde",
    name: "Tunde",
    languages: ["en-NG"],
    description:
      "Grounded, friendly Nigerian male voice, ideal for customer service, narration, and support.",
    gender: "male",
    tags: [
      "grounded",
      "friendly",
      "clear",
      "nigerian",
      "customer support",
      "narration",
      "enterprise",
      "interactive media",
    ],
  },
  {
    id: "Tyler",
    name: "Tyler",
    languages: ["en-US"],
    description:
      "Authoritative, insightful male voice, ideal for tech explainer videos, in-depth software reviews, and dynamic coding guides.",
    gender: "male",
    tags: [
      "authoritative",
      "insightful",
      "dynamic",
      "interactive media",
      "news",
      "education & training",
      "professional training",
    ],
  },
  {
    id: "Vadim",
    name: "Vadim",
    languages: ["ru-RU"],
    description:
      "Confident, approachable Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "confident",
      "approachable",
      "steady",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Vanessa",
    name: "Vanessa",
    languages: ["pt-BR"],
    description:
      "Warm, conversational Brazilian Portuguese female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "warm",
      "conversational",
      "engaging",
      "brazilian",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Veronica",
    name: "Veronica",
    languages: ["en-US"],
    description:
      "Intimidating, commanding female voice, perfect for ruthless antagonists, high-stakes negotiations, and chilling monologues.",
    gender: "female",
    tags: [
      "intimidating",
      "commanding",
      "icy",
      "companion",
      "social",
      "interactive media",
      "character",
    ],
  },
  {
    id: "Victor",
    name: "Victor",
    languages: ["en-US"],
    description:
      "Ominous, sinister male voice, ideal for dark conspiracies, eerie suspense scenes, and enigmatic villain roles.",
    gender: "male",
    tags: [
      "ominous",
      "sinister",
      "controlled",
      "interactive media",
      "narrative",
      "character",
    ],
  },
  {
    id: "Victoria",
    name: "Victoria",
    languages: ["en-GB"],
    description:
      "Silky, cunning British female voice, ideal for narrating intricate plots",
    gender: "female",
    tags: [
      "silky",
      "cunning",
      "elegant",
      "interactive media",
      "narrative",
      "british",
    ],
  },
  {
    id: "Vikram",
    name: "Vikram",
    languages: ["en-IN"],
    description:
      "Professional, measured Indian male voice, ideal for customer support, corporate, and education.",
    gender: "male",
    tags: [
      "professional",
      "measured",
      "clear",
      "indian",
      "customer support",
      "corporate",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Vincent",
    name: "Vincent",
    languages: ["en-US"],
    description: "Polished, classy male voice with a smooth, measured delivery",
    gender: "male",
    tags: [
      "classy",
      "polished",
      "smooth",
      "narration",
      "general purpose assistant",
      "enterprise",
    ],
  },
  {
    id: "Vinny",
    name: "Vinny",
    languages: ["en-US"],
    description:
      "Gritty, assertive New York male voice, perfect for crime dramas, urban documentaries, and no-nonsense character roles.",
    gender: "male",
    tags: [
      "gritty",
      "assertive",
      "authentic",
      "new york",
      "interactive media",
      "narrative",
      "character",
    ],
  },
  {
    id: "Wade",
    name: "Wade",
    languages: ["en-US"],
    description:
      "Casual, natural male voice with an easygoing conversational style",
    gender: "male",
    tags: [
      "casual",
      "relaxed",
      "natural",
      "conversational",
      "companion",
      "social companion",
    ],
  },
  {
    id: "Warren",
    name: "Warren",
    languages: ["en-US"],
    description: "Mature, resonant male voice with a classic announcer quality",
    gender: "male",
    tags: [
      "classy",
      "mature",
      "resonant",
      "narration",
      "advertisement",
      "enterprise",
    ],
  },
  {
    id: "Wei",
    name: "Wei",
    languages: ["en-SG"],
    description:
      "Confident, conversational Singaporean male voice, ideal for e-learning, customer service, and support.",
    gender: "male",
    tags: [
      "confident",
      "conversational",
      "clear",
      "singaporean",
      "education & training",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Wendy",
    name: "Wendy",
    languages: ["en-GB"],
    description: "Posh, middle-aged British female voice",
    gender: "female",
    tags: [
      "pleasant",
      "casual",
      "british",
      "healthcare",
      "mental health",
      "spiritual support",
    ],
  },
  {
    id: "Winifred",
    name: "Winifred",
    languages: ["en-GB"],
    description:
      "Mature, warm British female voice, ideal for audiobooks, documentary, and narration.",
    gender: "female",
    tags: [
      "mature",
      "warm",
      "measured",
      "british",
      "audiobook",
      "narration",
      "documentary",
      "interactive media",
    ],
  },
  {
    id: "Winston",
    name: "Winston",
    languages: ["en-GB"],
    description: "Mature British male voice with a warm storytelling quality",
    gender: "male",
    tags: [
      "mature",
      "warm",
      "british",
      "narrative",
      "storytelling",
      "narration",
    ],
  },
  {
    id: "Wojciech",
    name: "Wojciech",
    languages: ["pl-PL"],
    description: "A middle-aged Polish male voice",
    gender: "male",
    tags: ["confident", "strong"],
  },
  {
    id: "Xiaoyin",
    name: "Xiaoyin",
    languages: ["zh-CN"],
    description: "A youthful Chinese female voice with a gentle, sweet voice",
    gender: "female",
    tags: ["polite", "kind", "customer support"],
  },
  {
    id: "Ximena",
    name: "Ximena",
    languages: ["es-MX"],
    description:
      "Bright, natural Mexican Spanish female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "bright",
      "natural",
      "expressive",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Xinyi",
    name: "Xinyi",
    languages: ["zh-CN"],
    description: "A Chinese woman with a neutral tone, perfect for narrations",
    gender: "female",
    tags: ["professional", "warm"],
  },
  {
    id: "Xochitl",
    name: "Xochitl",
    languages: ["es-MX"],
    description:
      "Bright, natural Mexican Spanish female voice, ideal for education, narration, and customer service.",
    gender: "female",
    tags: [
      "bright",
      "natural",
      "expressive",
      "mexican",
      "education & training",
      "narration",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Yael",
    name: "Yael",
    languages: ["he-IL"],
    description:
      "Mid-range female Hebrew voice, suitable for narrations, storytelling, and more.",
    gender: "female",
    tags: ["neutral", "articulate"],
  },
  {
    id: "Yash",
    name: "Yash",
    languages: ["en-IN"],
    description:
      "Articulate, warm Indian male voice, ideal for customer support, corporate, and education.",
    gender: "male",
    tags: [
      "articulate",
      "warm",
      "engaging",
      "indian",
      "customer support",
      "corporate",
      "education & training",
      "enterprise",
    ],
  },
  {
    id: "Yegor",
    name: "Yegor",
    languages: ["ru-RU"],
    description:
      "Calm, articulate Russian male voice, ideal for narration, customer support, and business.",
    gender: "male",
    tags: [
      "calm",
      "articulate",
      "poised",
      "russian",
      "narration",
      "customer support",
      "business",
      "interactive media",
      "enterprise",
    ],
  },
  {
    id: "Yichen",
    name: "Yichen",
    languages: ["zh-CN"],
    description: "A calm, flat young adult male Chinese voice",
    gender: "male",
    tags: ["clear", "friendly"],
  },
  {
    id: "Yoona",
    name: "Yoona",
    languages: ["ko-KR"],
    description: "Korean woman with a gentle, soothing voice",
    gender: "female",
    tags: ["sad", "clear"],
  },
  {
    id: "Yulia",
    name: "Yulia",
    languages: ["ru-RU"],
    description:
      "Gentle, natural Russian female voice, ideal for narration, education, and customer service.",
    gender: "female",
    tags: [
      "gentle",
      "natural",
      "measured",
      "russian",
      "narration",
      "education & training",
      "customer support",
      "interactive media",
    ],
  },
  {
    id: "Zadie",
    name: "Zadie",
    languages: ["en-US"],
    description:
      "Punchy, expressive female voice, ideal for short-form social, UGC, and viral content.",
    gender: "female",
    tags: [
      "punchy",
      "expressive",
      "gen-z",
      "social",
      "viral",
      "ugc",
      "interactive media",
      "companion",
    ],
  },
  {
    id: "Zherong",
    name: "Zherong",
    languages: ["en-SG"],
    description:
      "Natural, helpful Singaporean male voice, ideal for e-learning, customer service, and support.",
    gender: "male",
    tags: [
      "natural",
      "helpful",
      "relaxed",
      "singaporean",
      "education & training",
      "customer support",
      "enterprise",
    ],
  },
  {
    id: "Zoe",
    name: "Zoe",
    languages: ["en-US"],
    description:
      "Upbeat, expressive young female voice with a clear, friendly delivery",
    gender: "female",
    tags: [
      "upbeat",
      "expressive",
      "clear",
      "friendly",
      "interactive media",
      "companion",
    ],
  },
  {
    id: "Étienne",
    name: "Étienne",
    languages: ["fr-FR"],
    description: "Calm young adult French male",
    gender: "male",
    tags: ["robust", "strong"],
  },
]
