export const mistralVoices = [
  {
    id: "en_paul_angry",
    name: "Paul - Angry",
    languages: ["en-US"],
    description: "Paul - Angry: raw, gruff, angry tone",
    gender: "male",
    tags: ["raw", "gruff", "angry"],
  },
  {
    id: "en_paul_cheerful",
    name: "Paul - Cheerful",
    languages: ["en-US"],
    description: "Paul - Cheerful: upbeat, breezy, cheerful tone",
    gender: "male",
    tags: ["upbeat", "breezy", "cheerful"],
  },
  {
    id: "en_paul_confident",
    name: "Paul - Confident",
    languages: ["en-US"],
    description: "Paul - Confident: bold, punchy, confident tone",
    gender: "male",
    tags: ["bold", "punchy", "confident"],
  },
  {
    id: "en_paul_excited",
    name: "Paul - Excited",
    languages: ["en-US"],
    description: "Paul - Excited: bouncy, spirited, excited tone",
    gender: "male",
    tags: ["bouncy", "spirited", "excited"],
  },
  {
    id: "en_paul_frustrated",
    name: "Paul - Frustrated",
    languages: ["en-US"],
    description: "Paul - Frustrated: edgy, snappy, frustrated tone",
    gender: "male",
    tags: ["edgy", "snappy", "frustrated"],
  },
  {
    id: "en_paul_happy",
    name: "Paul - Happy",
    languages: ["en-US"],
    description: "Paul - Happy: sunny, easygoing, happy tone",
    gender: "male",
    tags: ["sunny", "easygoing", "happy"],
  },
  {
    id: "en_paul_neutral",
    name: "Paul - Neutral",
    languages: ["en-US"],
    description: "Paul - Neutral: relaxed, balanced, neutral tone",
    gender: "male",
    tags: ["relaxed", "balanced", "neutral"],
  },
  {
    id: "en_paul_sad",
    name: "Paul - Sad",
    languages: ["en-US"],
    description: "Paul - Sad: heavy, hushed, sad tone",
    gender: "male",
    tags: ["heavy", "hushed", "sad"],
  },
  {
    id: "fr_marie_angry",
    name: "Marie - Angry",
    languages: ["fr-FR"],
    description: "Marie - Angry: fierce, sharp, angry tone",
    gender: "female",
    tags: ["fierce", "sharp", "angry"],
  },
  {
    id: "fr_marie_curious",
    name: "Marie - Curious",
    languages: ["fr-FR"],
    description: "Marie - Curious: bright, probing, curious tone",
    gender: "female",
    tags: ["bright", "probing", "curious"],
  },
  {
    id: "fr_marie_excited",
    name: "Marie - Excited",
    languages: ["fr-FR"],
    description: "Marie - Excited: vibrant, bubbly, excited tone",
    gender: "female",
    tags: ["vibrant", "bubbly", "excited"],
  },
  {
    id: "fr_marie_happy",
    name: "Marie - Happy",
    languages: ["fr-FR"],
    description: "Marie - Happy: warm, radiant, happy tone",
    gender: "female",
    tags: ["warm", "radiant", "happy"],
  },
  {
    id: "fr_marie_neutral",
    name: "Marie - Neutral",
    languages: ["fr-FR"],
    description: "Marie - Neutral: composed, steady, neutral tone",
    gender: "female",
    tags: ["composed", "steady", "neutral"],
  },
  {
    id: "fr_marie_sad",
    name: "Marie - Sad",
    languages: ["fr-FR"],
    description: "Marie - Sad: muted, heavy, sad tone",
    gender: "female",
    tags: ["muted", "heavy", "sad"],
  },
  {
    id: "gb_jane_confident",
    name: "Jane - Confident",
    languages: ["en-GB"],
    description: "Jane - Confident: assured, poised, confident tone",
    gender: "female",
    tags: ["assured", "poised", "confident"],
  },
  {
    id: "gb_jane_confused",
    name: "Jane - Confused",
    languages: ["en-GB"],
    description: "Jane - Confused: hesitant, uncertain, confused tone",
    gender: "female",
    tags: ["hesitant", "uncertain", "confused"],
  },
  {
    id: "gb_jane_curious",
    name: "Jane - Curious",
    languages: ["en-GB"],
    description: "Jane - Curious: inquisitive, open, curious tone",
    gender: "female",
    tags: ["inquisitive", "open", "curious"],
  },
  {
    id: "gb_jane_frustrated",
    name: "Jane - Frustrated",
    languages: ["en-GB"],
    description: "Jane - Frustrated: tense, clipped, frustrated tone",
    gender: "female",
    tags: ["tense", "clipped", "frustrated"],
  },
  {
    id: "gb_jane_jealousy",
    name: "Jane - Jealousy",
    languages: ["en-GB"],
    description: "Jane - Jealousy: bitter, strained, jealous tone",
    gender: "female",
    tags: ["bitter", "strained", "jealous"],
  },
  {
    id: "gb_jane_neutral",
    name: "Jane - Neutral",
    languages: ["en-GB"],
    description: "Jane - Neutral: clear, measured, neutral tone",
    gender: "female",
    tags: ["clear", "measured", "neutral"],
  },
  {
    id: "gb_jane_sad",
    name: "Jane - Sad",
    languages: ["en-GB"],
    description: "Jane - Sad: soft, subdued, sad tone",
    gender: "female",
    tags: ["soft", "subdued", "sad"],
  },
  {
    id: "gb_jane_sarcasm",
    name: "Jane - Sarcasm",
    languages: ["en-GB"],
    description: "Jane - Sarcasm: dry, wry, sarcastic tone",
    gender: "female",
    tags: ["dry", "wry", "sarcastic"],
  },
  {
    id: "gb_jane_shameful",
    name: "Jane - Shameful",
    languages: ["en-GB"],
    description: "Jane - Shameful: quiet, remorseful, ashamed tone",
    gender: "female",
    tags: ["quiet", "remorseful", "ashamed"],
  },
  {
    id: "gb_oliver_angry",
    name: "Oliver - Angry",
    languages: ["en-GB"],
    description: "Oliver - Angry: intense, forceful, angry tone",
    gender: "male",
    tags: ["intense", "forceful", "angry"],
  },
  {
    id: "gb_oliver_cheerful",
    name: "Oliver - Cheerful",
    languages: ["en-GB"],
    description: "Oliver - Cheerful: bright, lively, cheerful tone",
    gender: "male",
    tags: ["bright", "lively", "cheerful"],
  },
  {
    id: "gb_oliver_confident",
    name: "Oliver - Confident",
    languages: ["en-GB"],
    description: "Oliver - Confident: firm, decisive, confident tone",
    gender: "male",
    tags: ["firm", "decisive", "confident"],
  },
  {
    id: "gb_oliver_curious",
    name: "Oliver - Curious",
    languages: ["en-GB"],
    description: "Oliver - Curious: thoughtful, engaged, curious tone",
    gender: "male",
    tags: ["thoughtful", "engaged", "curious"],
  },
  {
    id: "gb_oliver_excited",
    name: "Oliver - Excited",
    languages: ["en-GB"],
    description: "Oliver - Excited: energetic, crisp, excited tone",
    gender: "male",
    tags: ["energetic", "crisp", "excited"],
  },
  {
    id: "gb_oliver_neutral",
    name: "Oliver - Neutral",
    languages: ["en-GB"],
    description: "Oliver - Neutral: calm, even, neutral tone",
    gender: "male",
    tags: ["calm", "even", "neutral"],
  },
  {
    id: "gb_oliver_sad",
    name: "Oliver - Sad",
    languages: ["en-GB"],
    description: "Oliver - Sad: low, hollow, sad tone",
    gender: "male",
    tags: ["low", "hollow", "sad"],
  },
]
