export const openaiVoices = [
  {
    id: "alloy",
    name: "Alloy",
    languages: ["en-US"],
    description: "Neutral, balanced",
    gender: "female",
    tags: ["neutral", "balanced"],
  },
  {
    id: "ash",
    name: "Ash",
    languages: ["en-US"],
    description: "Clear, steady male",
    gender: "male",
    tags: ["clear", "steady"],
  },
  {
    id: "coral",
    name: "Coral",
    languages: ["en-US"],
    description: "Warm, engaging female",
    gender: "female",
    tags: ["warm", "engaging"],
  },
  {
    id: "echo",
    name: "Echo",
    languages: ["en-US"],
    description: "Smooth, resonant male",
    gender: "male",
    tags: ["smooth", "resonant"],
  },
  {
    id: "fable",
    name: "Fable",
    languages: ["en-GB"],
    description: "Expressive British narrator",
    gender: "male",
    tags: ["expressive", "british", "narrator"],
  },
  {
    id: "nova",
    name: "Nova",
    languages: ["en-US"],
    description: "Bright, energetic female",
    gender: "female",
    tags: ["bright", "energetic"],
  },
  {
    id: "onyx",
    name: "Onyx",
    languages: ["en-US"],
    description: "Deep, authoritative male",
    gender: "male",
    tags: ["deep", "authoritative"],
  },
  {
    id: "sage",
    name: "Sage",
    languages: ["en-US"],
    description: "Calm, thoughtful female",
    gender: "female",
    tags: ["calm", "thoughtful"],
  },
  {
    id: "shimmer",
    name: "Shimmer",
    languages: ["en-US"],
    description: "Soft, upbeat female",
    gender: "female",
    tags: ["soft", "upbeat"],
  },
]

export const openaiGpt4oMiniTtsVoices = [
  {
    id: "alloy",
    name: "Alloy",
    languages: ["en-US"],
    description: "Neutral, balanced",
    gender: "female",
    tags: ["neutral", "balanced"],
  },
  {
    id: "ash",
    name: "Ash",
    languages: ["en-US"],
    description: "Clear, steady male",
    gender: "male",
    tags: ["clear", "steady"],
  },
  {
    id: "ballad",
    name: "Ballad",
    languages: ["en-US"],
    description: "Smooth, melodic male with slight British tint",
    gender: "male",
    tags: ["smooth", "melodic", "expressive", "gpt-4o-mini-tts-only"],
  },
  {
    id: "coral",
    name: "Coral",
    languages: ["en-US"],
    description: "Warm, engaging female",
    gender: "female",
    tags: ["warm", "engaging"],
  },
  {
    id: "echo",
    name: "Echo",
    languages: ["en-US"],
    description: "Smooth, resonant male",
    gender: "male",
    tags: ["smooth", "resonant"],
  },
  {
    id: "fable",
    name: "Fable",
    languages: ["en-GB"],
    description: "Expressive British narrator",
    gender: "male",
    tags: ["expressive", "british", "narrator"],
  },
  {
    id: "nova",
    name: "Nova",
    languages: ["en-US"],
    description: "Bright, energetic female",
    gender: "female",
    tags: ["bright", "energetic"],
  },
  {
    id: "onyx",
    name: "Onyx",
    languages: ["en-US"],
    description: "Deep, authoritative male",
    gender: "male",
    tags: ["deep", "authoritative"],
  },
  {
    id: "sage",
    name: "Sage",
    languages: ["en-US"],
    description: "Calm, thoughtful female",
    gender: "female",
    tags: ["calm", "thoughtful"],
  },
  {
    id: "shimmer",
    name: "Shimmer",
    languages: ["en-US"],
    description: "Soft, upbeat female",
    gender: "female",
    tags: ["soft", "upbeat"],
  },
  {
    id: "verse",
    name: "Verse",
    languages: ["en-US"],
    description: "Poetic, highly steerable male",
    gender: "male",
    tags: ["poetic", "expressive", "steerable", "gpt-4o-mini-tts-only"],
  },
  {
    id: "marin",
    name: "Marin",
    languages: ["en-US"],
    description: "Clear, professional female — recommended for best quality",
    gender: "female",
    tags: ["clear", "professional", "recommended", "gpt-4o-mini-tts-only"],
  },
  {
    id: "cedar",
    name: "Cedar",
    languages: ["en-US"],
    description: "Natural, warm male — recommended for best quality",
    gender: "male",
    tags: ["natural", "warm", "recommended", "gpt-4o-mini-tts-only"],
  },
]
