export const xaiVoices = [
  {
    id: "altair",
    name: "Altair",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Elegant, refined, and effortlessly premium",
    gender: "male",
    tags: ["elegant", "refined", "effortlessly", "premium", "multilingual"],
  },
  {
    id: "ara",
    name: "Ara",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Warm, friendly, balanced and conversational",
    gender: "female",
    tags: ["warm", "friendly", "balanced", "conversational", "multilingual"],
  },
  {
    id: "atlas",
    name: "Atlas",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Confident, commanding, and reassuring",
    gender: "male",
    tags: ["confident", "commanding", "reassuring", "multilingual"],
  },
  {
    id: "aurora",
    name: "Aurora",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Serene, steady, and radiant",
    gender: "female",
    tags: ["serene", "steady", "radiant", "multilingual"],
  },
  {
    id: "carina",
    name: "Carina",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Soft, empathetic, and soothing",
    gender: "female",
    tags: ["soft", "empathetic", "soothing", "multilingual"],
  },
  {
    id: "castor",
    name: "Castor",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Charismatic, down-to-earth, and easygoing",
    gender: "male",
    tags: ["charismatic", "down-to-earth", "easygoing", "multilingual"],
  },
  {
    id: "celeste",
    name: "Celeste",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Compassionate, confident, and reassuring",
    gender: "female",
    tags: ["compassionate", "confident", "reassuring", "multilingual"],
  },
  {
    id: "cosmo",
    name: "Cosmo",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Bright, curious, and easy to follow",
    gender: "male",
    tags: ["bright", "curious", "easy", "follow", "multilingual"],
  },
  {
    id: "eve",
    name: "Eve",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Energetic, upbeat; default engaging voice",
    gender: "female",
    tags: ["energetic", "upbeat", "default", "engaging", "multilingual"],
  },
  {
    id: "helios",
    name: "Helios",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Upbeat, energetic, and endlessly versatile",
    gender: "male",
    tags: ["upbeat", "energetic", "endlessly", "versatile", "multilingual"],
  },
  {
    id: "helix",
    name: "Helix",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Bold, dynamic, and adrenaline-fueled",
    gender: "male",
    tags: ["bold", "dynamic", "adrenaline-fueled", "multilingual"],
  },
  {
    id: "iris",
    name: "Iris",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Friendly, upbeat, and naturally charming",
    gender: "female",
    tags: ["friendly", "upbeat", "naturally", "charming", "multilingual"],
  },
  {
    id: "kepler",
    name: "Kepler",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Inventive, forward-thinking, and charismatic",
    gender: "male",
    tags: ["inventive", "forward-thinking", "charismatic", "multilingual"],
  },
  {
    id: "leo",
    name: "Leo",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Authoritative, strong; decisive for instructional content",
    gender: "male",
    tags: [
      "authoritative",
      "strong",
      "decisive",
      "instructional",
      "content",
      "multilingual",
    ],
  },
  {
    id: "liora",
    name: "Liora",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Calm, grounded, and luminous",
    gender: "female",
    tags: ["calm", "grounded", "luminous", "multilingual"],
  },
  {
    id: "lumen",
    name: "Lumen",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Warm, articulate, and engaging",
    gender: "male",
    tags: ["warm", "articulate", "engaging", "multilingual"],
  },
  {
    id: "luna",
    name: "Luna",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Gentle, patient, and deeply nurturing",
    gender: "female",
    tags: ["gentle", "patient", "deeply", "nurturing", "multilingual"],
  },
  {
    id: "lux",
    name: "Lux",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Grounded, calm, and quietly wise",
    gender: "male",
    tags: ["grounded", "calm", "quietly", "wise", "multilingual"],
  },
  {
    id: "naksh",
    name: "Naksh",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Warm, thoughtful, and wise",
    gender: "male",
    tags: ["warm", "thoughtful", "wise", "multilingual"],
  },
  {
    id: "orion",
    name: "Orion",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Rich, cinematic, and resonant",
    gender: "male",
    tags: ["rich", "cinematic", "resonant", "multilingual"],
  },
  {
    id: "perseus",
    name: "Perseus",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Strong, confident, and trustworthy",
    gender: "male",
    tags: ["strong", "confident", "trustworthy", "multilingual"],
  },
  {
    id: "rex",
    name: "Rex",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Confident, clear; professional and articulate for business",
    gender: "male",
    tags: [
      "confident",
      "clear",
      "professional",
      "articulate",
      "business",
      "multilingual",
    ],
  },
  {
    id: "rigel",
    name: "Rigel",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Precise, professional, and calmly confident",
    gender: "male",
    tags: ["precise", "professional", "calmly", "confident", "multilingual"],
  },
  {
    id: "sal",
    name: "Sal",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Smooth, balanced; versatile across contexts",
    gender: "male",
    tags: ["smooth", "balanced", "versatile", "contexts", "multilingual"],
  },
  {
    id: "sirius",
    name: "Sirius",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Quick-witted, clever, and playful",
    gender: "male",
    tags: ["quick-witted", "clever", "playful", "multilingual"],
  },
  {
    id: "ursa",
    name: "Ursa",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Friendly, warm, and steadfast",
    gender: "female",
    tags: ["friendly", "warm", "steadfast", "multilingual"],
  },
  {
    id: "zagan",
    name: "Zagan",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Powerful, dramatic, and unmistakable",
    gender: "male",
    tags: ["powerful", "dramatic", "unmistakable", "multilingual"],
  },
  {
    id: "zenith",
    name: "Zenith",
    languages: [
      "en",
      "ar-EG",
      "ar-SA",
      "ar-AE",
      "bn",
      "zh",
      "fr",
      "de",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "pt-BR",
      "pt-PT",
      "ru",
      "es-MX",
      "es-ES",
      "tr",
      "vi",
    ],
    description: "Sharp, focused, and driven",
    gender: "male",
    tags: ["sharp", "focused", "driven", "multilingual"],
  },
]
