/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authorizedLayoutRouteImport } from './routes/(authorized)/layout'
import { Route as unauthorizedLayoutRouteImport } from './routes/(unauthorized)/layout'
import { Route as authorizedorganizationLayoutRouteImport } from './routes/(authorized)/(organization)/layout'
import { Route as authorizedorganizationsidebarLayoutRouteImport } from './routes/(authorized)/(organization)/(sidebar)/layout'
import { Route as authorizedCreateOrganizationPageRouteImport } from './routes/(authorized)/create-organization/page'
import { Route as authorizedJoinOrganizationPageRouteImport } from './routes/(authorized)/join-organization/page'
import { Route as authorizedSelectOrganizationPageRouteImport } from './routes/(authorized)/select-organization/page'
import { Route as unauthorizedEmailVerificationPageRouteImport } from './routes/(unauthorized)/email-verification/page'
import { Route as unauthorizedResetPasswordPageRouteImport } from './routes/(unauthorized)/reset-password/page'
import { Route as unauthorizedSetNewPasswordPageRouteImport } from './routes/(unauthorized)/set-new-password/page'
import { Route as unauthorizedSigninPageRouteImport } from './routes/(unauthorized)/signin/page'
import { Route as unauthorizedSignupPageRouteImport } from './routes/(unauthorized)/signup/page'
import { Route as authorizedorganizationsidebarPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/page'
import { Route as authorizedorganizationsidebarSettingsLayoutRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/layout'
import { Route as authorizedorganizationInviteMembersPageRouteImport } from './routes/(authorized)/(organization)/invite-members/page'
import { Route as authorizedorganizationsidebarSplatPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/$/page'
import { Route as authorizedorganizationsidebarAgentsPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/agents/page'
import { Route as authorizedorganizationsidebarBatchCallsPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/batch-calls/page'
import { Route as authorizedorganizationsidebarCallsPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/calls/page'
import { Route as authorizedorganizationsidebarPhoneNumbersPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/phone-numbers/page'
import { Route as authorizedorganizationsidebarSettingsPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/page'
import { Route as authorizedorganizationsidebarAgentsAgentIdPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/agents/$agentId/page'
import { Route as authorizedorganizationsidebarBatchCallsCreatePageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/batch-calls/create/page'
import { Route as authorizedorganizationsidebarSettingsAccountPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/account/page'
import { Route as authorizedorganizationsidebarSettingsBillingPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/billing/page'
import { Route as authorizedorganizationsidebarSettingsMembersPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/members/page'
import { Route as authorizedorganizationsidebarSettingsOrganizationPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/organization/page'
import { Route as authorizedorganizationsidebarSettingsRolesPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/roles/page'

const authorizedLayoutRoute = authorizedLayoutRouteImport.update({
  id: '/(authorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const unauthorizedLayoutRoute = unauthorizedLayoutRouteImport.update({
  id: '/(unauthorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedorganizationLayoutRoute =
  authorizedorganizationLayoutRouteImport.update({
    id: '/(organization)',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedorganizationsidebarLayoutRoute =
  authorizedorganizationsidebarLayoutRouteImport.update({
    id: '/(sidebar)',
    getParentRoute: () => authorizedorganizationLayoutRoute,
  } as any)
const authorizedCreateOrganizationPageRoute =
  authorizedCreateOrganizationPageRouteImport.update({
    id: '/create-organization/',
    path: '/create-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedJoinOrganizationPageRoute =
  authorizedJoinOrganizationPageRouteImport.update({
    id: '/join-organization/',
    path: '/join-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedSelectOrganizationPageRoute =
  authorizedSelectOrganizationPageRouteImport.update({
    id: '/select-organization/',
    path: '/select-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const unauthorizedEmailVerificationPageRoute =
  unauthorizedEmailVerificationPageRouteImport.update({
    id: '/email-verification/',
    path: '/email-verification/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const unauthorizedResetPasswordPageRoute =
  unauthorizedResetPasswordPageRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const unauthorizedSetNewPasswordPageRoute =
  unauthorizedSetNewPasswordPageRouteImport.update({
    id: '/set-new-password/',
    path: '/set-new-password/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const unauthorizedSigninPageRoute = unauthorizedSigninPageRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => unauthorizedLayoutRoute,
} as any)
const unauthorizedSignupPageRoute = unauthorizedSignupPageRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => unauthorizedLayoutRoute,
} as any)
const authorizedorganizationsidebarPageRoute =
  authorizedorganizationsidebarPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsLayoutRoute =
  authorizedorganizationsidebarSettingsLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationInviteMembersPageRoute =
  authorizedorganizationInviteMembersPageRouteImport.update({
    id: '/invite-members/',
    path: '/invite-members/',
    getParentRoute: () => authorizedorganizationLayoutRoute,
  } as any)
const authorizedorganizationsidebarSplatPageRoute =
  authorizedorganizationsidebarSplatPageRouteImport.update({
    id: '/$/',
    path: '/$/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarAgentsPageRoute =
  authorizedorganizationsidebarAgentsPageRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarBatchCallsPageRoute =
  authorizedorganizationsidebarBatchCallsPageRouteImport.update({
    id: '/batch-calls/',
    path: '/batch-calls/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarCallsPageRoute =
  authorizedorganizationsidebarCallsPageRouteImport.update({
    id: '/calls/',
    path: '/calls/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarPhoneNumbersPageRoute =
  authorizedorganizationsidebarPhoneNumbersPageRouteImport.update({
    id: '/phone-numbers/',
    path: '/phone-numbers/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsPageRoute =
  authorizedorganizationsidebarSettingsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarAgentsAgentIdPageRoute =
  authorizedorganizationsidebarAgentsAgentIdPageRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarBatchCallsCreatePageRoute =
  authorizedorganizationsidebarBatchCallsCreatePageRouteImport.update({
    id: '/batch-calls/create/',
    path: '/batch-calls/create/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsAccountPageRoute =
  authorizedorganizationsidebarSettingsAccountPageRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsBillingPageRoute =
  authorizedorganizationsidebarSettingsBillingPageRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsMembersPageRoute =
  authorizedorganizationsidebarSettingsMembersPageRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsOrganizationPageRoute =
  authorizedorganizationsidebarSettingsOrganizationPageRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsRolesPageRoute =
  authorizedorganizationsidebarSettingsRolesPageRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/create-organization/': typeof authorizedCreateOrganizationPageRoute
  '/join-organization/': typeof authorizedJoinOrganizationPageRoute
  '/select-organization/': typeof authorizedSelectOrganizationPageRoute
  '/email-verification/': typeof unauthorizedEmailVerificationPageRoute
  '/reset-password/': typeof unauthorizedResetPasswordPageRoute
  '/set-new-password/': typeof unauthorizedSetNewPasswordPageRoute
  '/signin/': typeof unauthorizedSigninPageRoute
  '/signup/': typeof unauthorizedSignupPageRoute
  '/settings': typeof authorizedorganizationsidebarSettingsLayoutRouteWithChildren
  '/': typeof authorizedorganizationsidebarPageRoute
  '/invite-members/': typeof authorizedorganizationInviteMembersPageRoute
  '/$/': typeof authorizedorganizationsidebarSplatPageRoute
  '/agents/': typeof authorizedorganizationsidebarAgentsPageRoute
  '/batch-calls/': typeof authorizedorganizationsidebarBatchCallsPageRoute
  '/calls/': typeof authorizedorganizationsidebarCallsPageRoute
  '/phone-numbers/': typeof authorizedorganizationsidebarPhoneNumbersPageRoute
  '/settings/': typeof authorizedorganizationsidebarSettingsPageRoute
  '/agents/$agentId/': typeof authorizedorganizationsidebarAgentsAgentIdPageRoute
  '/batch-calls/create/': typeof authorizedorganizationsidebarBatchCallsCreatePageRoute
  '/settings/account/': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/settings/billing/': typeof authorizedorganizationsidebarSettingsBillingPageRoute
  '/settings/members/': typeof authorizedorganizationsidebarSettingsMembersPageRoute
  '/settings/organization/': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
  '/settings/roles/': typeof authorizedorganizationsidebarSettingsRolesPageRoute
}
export interface FileRoutesByTo {
  '/create-organization': typeof authorizedCreateOrganizationPageRoute
  '/join-organization': typeof authorizedJoinOrganizationPageRoute
  '/select-organization': typeof authorizedSelectOrganizationPageRoute
  '/email-verification': typeof unauthorizedEmailVerificationPageRoute
  '/reset-password': typeof unauthorizedResetPasswordPageRoute
  '/set-new-password': typeof unauthorizedSetNewPasswordPageRoute
  '/signin': typeof unauthorizedSigninPageRoute
  '/signup': typeof unauthorizedSignupPageRoute
  '/': typeof authorizedorganizationsidebarPageRoute
  '/invite-members': typeof authorizedorganizationInviteMembersPageRoute
  '/$': typeof authorizedorganizationsidebarSplatPageRoute
  '/agents': typeof authorizedorganizationsidebarAgentsPageRoute
  '/batch-calls': typeof authorizedorganizationsidebarBatchCallsPageRoute
  '/calls': typeof authorizedorganizationsidebarCallsPageRoute
  '/phone-numbers': typeof authorizedorganizationsidebarPhoneNumbersPageRoute
  '/settings': typeof authorizedorganizationsidebarSettingsPageRoute
  '/agents/$agentId': typeof authorizedorganizationsidebarAgentsAgentIdPageRoute
  '/batch-calls/create': typeof authorizedorganizationsidebarBatchCallsCreatePageRoute
  '/settings/account': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/settings/billing': typeof authorizedorganizationsidebarSettingsBillingPageRoute
  '/settings/members': typeof authorizedorganizationsidebarSettingsMembersPageRoute
  '/settings/organization': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
  '/settings/roles': typeof authorizedorganizationsidebarSettingsRolesPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authorized)': typeof authorizedLayoutRouteWithChildren
  '/(unauthorized)': typeof unauthorizedLayoutRouteWithChildren
  '/(authorized)/(organization)': typeof authorizedorganizationLayoutRouteWithChildren
  '/(authorized)/(organization)/(sidebar)': typeof authorizedorganizationsidebarLayoutRouteWithChildren
  '/(authorized)/create-organization/': typeof authorizedCreateOrganizationPageRoute
  '/(authorized)/join-organization/': typeof authorizedJoinOrganizationPageRoute
  '/(authorized)/select-organization/': typeof authorizedSelectOrganizationPageRoute
  '/(unauthorized)/email-verification/': typeof unauthorizedEmailVerificationPageRoute
  '/(unauthorized)/reset-password/': typeof unauthorizedResetPasswordPageRoute
  '/(unauthorized)/set-new-password/': typeof unauthorizedSetNewPasswordPageRoute
  '/(unauthorized)/signin/': typeof unauthorizedSigninPageRoute
  '/(unauthorized)/signup/': typeof unauthorizedSignupPageRoute
  '/(authorized)/(organization)/(sidebar)/settings': typeof authorizedorganizationsidebarSettingsLayoutRouteWithChildren
  '/(authorized)/(organization)/(sidebar)/': typeof authorizedorganizationsidebarPageRoute
  '/(authorized)/(organization)/invite-members/': typeof authorizedorganizationInviteMembersPageRoute
  '/(authorized)/(organization)/(sidebar)/$/': typeof authorizedorganizationsidebarSplatPageRoute
  '/(authorized)/(organization)/(sidebar)/agents/': typeof authorizedorganizationsidebarAgentsPageRoute
  '/(authorized)/(organization)/(sidebar)/batch-calls/': typeof authorizedorganizationsidebarBatchCallsPageRoute
  '/(authorized)/(organization)/(sidebar)/calls/': typeof authorizedorganizationsidebarCallsPageRoute
  '/(authorized)/(organization)/(sidebar)/phone-numbers/': typeof authorizedorganizationsidebarPhoneNumbersPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/': typeof authorizedorganizationsidebarSettingsPageRoute
  '/(authorized)/(organization)/(sidebar)/agents/$agentId/': typeof authorizedorganizationsidebarAgentsAgentIdPageRoute
  '/(authorized)/(organization)/(sidebar)/batch-calls/create/': typeof authorizedorganizationsidebarBatchCallsCreatePageRoute
  '/(authorized)/(organization)/(sidebar)/settings/account/': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/billing/': typeof authorizedorganizationsidebarSettingsBillingPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/members/': typeof authorizedorganizationsidebarSettingsMembersPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/organization/': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/roles/': typeof authorizedorganizationsidebarSettingsRolesPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-organization/'
    | '/join-organization/'
    | '/select-organization/'
    | '/email-verification/'
    | '/reset-password/'
    | '/set-new-password/'
    | '/signin/'
    | '/signup/'
    | '/settings'
    | '/'
    | '/invite-members/'
    | '/$/'
    | '/agents/'
    | '/batch-calls/'
    | '/calls/'
    | '/phone-numbers/'
    | '/settings/'
    | '/agents/$agentId/'
    | '/batch-calls/create/'
    | '/settings/account/'
    | '/settings/billing/'
    | '/settings/members/'
    | '/settings/organization/'
    | '/settings/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-organization'
    | '/join-organization'
    | '/select-organization'
    | '/email-verification'
    | '/reset-password'
    | '/set-new-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/invite-members'
    | '/$'
    | '/agents'
    | '/batch-calls'
    | '/calls'
    | '/phone-numbers'
    | '/settings'
    | '/agents/$agentId'
    | '/batch-calls/create'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/roles'
  id:
    | '__root__'
    | '/(authorized)'
    | '/(unauthorized)'
    | '/(authorized)/(organization)'
    | '/(authorized)/(organization)/(sidebar)'
    | '/(authorized)/create-organization/'
    | '/(authorized)/join-organization/'
    | '/(authorized)/select-organization/'
    | '/(unauthorized)/email-verification/'
    | '/(unauthorized)/reset-password/'
    | '/(unauthorized)/set-new-password/'
    | '/(unauthorized)/signin/'
    | '/(unauthorized)/signup/'
    | '/(authorized)/(organization)/(sidebar)/settings'
    | '/(authorized)/(organization)/(sidebar)/'
    | '/(authorized)/(organization)/invite-members/'
    | '/(authorized)/(organization)/(sidebar)/$/'
    | '/(authorized)/(organization)/(sidebar)/agents/'
    | '/(authorized)/(organization)/(sidebar)/batch-calls/'
    | '/(authorized)/(organization)/(sidebar)/calls/'
    | '/(authorized)/(organization)/(sidebar)/phone-numbers/'
    | '/(authorized)/(organization)/(sidebar)/settings/'
    | '/(authorized)/(organization)/(sidebar)/agents/$agentId/'
    | '/(authorized)/(organization)/(sidebar)/batch-calls/create/'
    | '/(authorized)/(organization)/(sidebar)/settings/account/'
    | '/(authorized)/(organization)/(sidebar)/settings/billing/'
    | '/(authorized)/(organization)/(sidebar)/settings/members/'
    | '/(authorized)/(organization)/(sidebar)/settings/organization/'
    | '/(authorized)/(organization)/(sidebar)/settings/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authorizedLayoutRoute: typeof authorizedLayoutRouteWithChildren
  unauthorizedLayoutRoute: typeof unauthorizedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authorized)': {
      id: '/(authorized)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unauthorized)': {
      id: '/(unauthorized)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)/(organization)': {
      id: '/(authorized)/(organization)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedorganizationLayoutRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)': {
      id: '/(authorized)/(organization)/(sidebar)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedorganizationsidebarLayoutRouteImport
      parentRoute: typeof authorizedorganizationLayoutRoute
    }
    '/(authorized)/create-organization/': {
      id: '/(authorized)/create-organization/'
      path: '/create-organization'
      fullPath: '/create-organization/'
      preLoaderRoute: typeof authorizedCreateOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/join-organization/': {
      id: '/(authorized)/join-organization/'
      path: '/join-organization'
      fullPath: '/join-organization/'
      preLoaderRoute: typeof authorizedJoinOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/select-organization/': {
      id: '/(authorized)/select-organization/'
      path: '/select-organization'
      fullPath: '/select-organization/'
      preLoaderRoute: typeof authorizedSelectOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(unauthorized)/email-verification/': {
      id: '/(unauthorized)/email-verification/'
      path: '/email-verification'
      fullPath: '/email-verification/'
      preLoaderRoute: typeof unauthorizedEmailVerificationPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/reset-password/': {
      id: '/(unauthorized)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof unauthorizedResetPasswordPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/set-new-password/': {
      id: '/(unauthorized)/set-new-password/'
      path: '/set-new-password'
      fullPath: '/set-new-password/'
      preLoaderRoute: typeof unauthorizedSetNewPasswordPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/signin/': {
      id: '/(unauthorized)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof unauthorizedSigninPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/signup/': {
      id: '/(unauthorized)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof unauthorizedSignupPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/': {
      id: '/(authorized)/(organization)/(sidebar)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authorizedorganizationsidebarPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings': {
      id: '/(authorized)/(organization)/(sidebar)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsLayoutRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/invite-members/': {
      id: '/(authorized)/(organization)/invite-members/'
      path: '/invite-members'
      fullPath: '/invite-members/'
      preLoaderRoute: typeof authorizedorganizationInviteMembersPageRouteImport
      parentRoute: typeof authorizedorganizationLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/$/': {
      id: '/(authorized)/(organization)/(sidebar)/$/'
      path: '/$'
      fullPath: '/$/'
      preLoaderRoute: typeof authorizedorganizationsidebarSplatPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/agents/': {
      id: '/(authorized)/(organization)/(sidebar)/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof authorizedorganizationsidebarAgentsPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/batch-calls/': {
      id: '/(authorized)/(organization)/(sidebar)/batch-calls/'
      path: '/batch-calls'
      fullPath: '/batch-calls/'
      preLoaderRoute: typeof authorizedorganizationsidebarBatchCallsPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/calls/': {
      id: '/(authorized)/(organization)/(sidebar)/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof authorizedorganizationsidebarCallsPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/phone-numbers/': {
      id: '/(authorized)/(organization)/(sidebar)/phone-numbers/'
      path: '/phone-numbers'
      fullPath: '/phone-numbers/'
      preLoaderRoute: typeof authorizedorganizationsidebarPhoneNumbersPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/agents/$agentId/': {
      id: '/(authorized)/(organization)/(sidebar)/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof authorizedorganizationsidebarAgentsAgentIdPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/batch-calls/create/': {
      id: '/(authorized)/(organization)/(sidebar)/batch-calls/create/'
      path: '/batch-calls/create'
      fullPath: '/batch-calls/create/'
      preLoaderRoute: typeof authorizedorganizationsidebarBatchCallsCreatePageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/account/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/account/'
      path: '/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsAccountPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/billing/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/billing/'
      path: '/billing'
      fullPath: '/settings/billing/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsBillingPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/members/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/members/'
      path: '/members'
      fullPath: '/settings/members/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsMembersPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/organization/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/organization/'
      path: '/organization'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsOrganizationPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/roles/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/roles/'
      path: '/roles'
      fullPath: '/settings/roles/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsRolesPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
  }
}

interface authorizedorganizationsidebarSettingsLayoutRouteChildren {
  authorizedorganizationsidebarSettingsPageRoute: typeof authorizedorganizationsidebarSettingsPageRoute
  authorizedorganizationsidebarSettingsAccountPageRoute: typeof authorizedorganizationsidebarSettingsAccountPageRoute
  authorizedorganizationsidebarSettingsBillingPageRoute: typeof authorizedorganizationsidebarSettingsBillingPageRoute
  authorizedorganizationsidebarSettingsMembersPageRoute: typeof authorizedorganizationsidebarSettingsMembersPageRoute
  authorizedorganizationsidebarSettingsOrganizationPageRoute: typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
  authorizedorganizationsidebarSettingsRolesPageRoute: typeof authorizedorganizationsidebarSettingsRolesPageRoute
}

const authorizedorganizationsidebarSettingsLayoutRouteChildren: authorizedorganizationsidebarSettingsLayoutRouteChildren =
  {
    authorizedorganizationsidebarSettingsPageRoute:
      authorizedorganizationsidebarSettingsPageRoute,
    authorizedorganizationsidebarSettingsAccountPageRoute:
      authorizedorganizationsidebarSettingsAccountPageRoute,
    authorizedorganizationsidebarSettingsBillingPageRoute:
      authorizedorganizationsidebarSettingsBillingPageRoute,
    authorizedorganizationsidebarSettingsMembersPageRoute:
      authorizedorganizationsidebarSettingsMembersPageRoute,
    authorizedorganizationsidebarSettingsOrganizationPageRoute:
      authorizedorganizationsidebarSettingsOrganizationPageRoute,
    authorizedorganizationsidebarSettingsRolesPageRoute:
      authorizedorganizationsidebarSettingsRolesPageRoute,
  }

const authorizedorganizationsidebarSettingsLayoutRouteWithChildren =
  authorizedorganizationsidebarSettingsLayoutRoute._addFileChildren(
    authorizedorganizationsidebarSettingsLayoutRouteChildren,
  )

interface authorizedorganizationsidebarLayoutRouteChildren {
  authorizedorganizationsidebarSettingsLayoutRoute: typeof authorizedorganizationsidebarSettingsLayoutRouteWithChildren
  authorizedorganizationsidebarPageRoute: typeof authorizedorganizationsidebarPageRoute
  authorizedorganizationsidebarSplatPageRoute: typeof authorizedorganizationsidebarSplatPageRoute
  authorizedorganizationsidebarAgentsPageRoute: typeof authorizedorganizationsidebarAgentsPageRoute
  authorizedorganizationsidebarBatchCallsPageRoute: typeof authorizedorganizationsidebarBatchCallsPageRoute
  authorizedorganizationsidebarCallsPageRoute: typeof authorizedorganizationsidebarCallsPageRoute
  authorizedorganizationsidebarPhoneNumbersPageRoute: typeof authorizedorganizationsidebarPhoneNumbersPageRoute
  authorizedorganizationsidebarAgentsAgentIdPageRoute: typeof authorizedorganizationsidebarAgentsAgentIdPageRoute
  authorizedorganizationsidebarBatchCallsCreatePageRoute: typeof authorizedorganizationsidebarBatchCallsCreatePageRoute
}

const authorizedorganizationsidebarLayoutRouteChildren: authorizedorganizationsidebarLayoutRouteChildren =
  {
    authorizedorganizationsidebarSettingsLayoutRoute:
      authorizedorganizationsidebarSettingsLayoutRouteWithChildren,
    authorizedorganizationsidebarPageRoute:
      authorizedorganizationsidebarPageRoute,
    authorizedorganizationsidebarSplatPageRoute:
      authorizedorganizationsidebarSplatPageRoute,
    authorizedorganizationsidebarAgentsPageRoute:
      authorizedorganizationsidebarAgentsPageRoute,
    authorizedorganizationsidebarBatchCallsPageRoute:
      authorizedorganizationsidebarBatchCallsPageRoute,
    authorizedorganizationsidebarCallsPageRoute:
      authorizedorganizationsidebarCallsPageRoute,
    authorizedorganizationsidebarPhoneNumbersPageRoute:
      authorizedorganizationsidebarPhoneNumbersPageRoute,
    authorizedorganizationsidebarAgentsAgentIdPageRoute:
      authorizedorganizationsidebarAgentsAgentIdPageRoute,
    authorizedorganizationsidebarBatchCallsCreatePageRoute:
      authorizedorganizationsidebarBatchCallsCreatePageRoute,
  }

const authorizedorganizationsidebarLayoutRouteWithChildren =
  authorizedorganizationsidebarLayoutRoute._addFileChildren(
    authorizedorganizationsidebarLayoutRouteChildren,
  )

interface authorizedorganizationLayoutRouteChildren {
  authorizedorganizationsidebarLayoutRoute: typeof authorizedorganizationsidebarLayoutRouteWithChildren
  authorizedorganizationInviteMembersPageRoute: typeof authorizedorganizationInviteMembersPageRoute
}

const authorizedorganizationLayoutRouteChildren: authorizedorganizationLayoutRouteChildren =
  {
    authorizedorganizationsidebarLayoutRoute:
      authorizedorganizationsidebarLayoutRouteWithChildren,
    authorizedorganizationInviteMembersPageRoute:
      authorizedorganizationInviteMembersPageRoute,
  }

const authorizedorganizationLayoutRouteWithChildren =
  authorizedorganizationLayoutRoute._addFileChildren(
    authorizedorganizationLayoutRouteChildren,
  )

interface authorizedLayoutRouteChildren {
  authorizedorganizationLayoutRoute: typeof authorizedorganizationLayoutRouteWithChildren
  authorizedCreateOrganizationPageRoute: typeof authorizedCreateOrganizationPageRoute
  authorizedJoinOrganizationPageRoute: typeof authorizedJoinOrganizationPageRoute
  authorizedSelectOrganizationPageRoute: typeof authorizedSelectOrganizationPageRoute
}

const authorizedLayoutRouteChildren: authorizedLayoutRouteChildren = {
  authorizedorganizationLayoutRoute:
    authorizedorganizationLayoutRouteWithChildren,
  authorizedCreateOrganizationPageRoute: authorizedCreateOrganizationPageRoute,
  authorizedJoinOrganizationPageRoute: authorizedJoinOrganizationPageRoute,
  authorizedSelectOrganizationPageRoute: authorizedSelectOrganizationPageRoute,
}

const authorizedLayoutRouteWithChildren =
  authorizedLayoutRoute._addFileChildren(authorizedLayoutRouteChildren)

interface unauthorizedLayoutRouteChildren {
  unauthorizedEmailVerificationPageRoute: typeof unauthorizedEmailVerificationPageRoute
  unauthorizedResetPasswordPageRoute: typeof unauthorizedResetPasswordPageRoute
  unauthorizedSetNewPasswordPageRoute: typeof unauthorizedSetNewPasswordPageRoute
  unauthorizedSigninPageRoute: typeof unauthorizedSigninPageRoute
  unauthorizedSignupPageRoute: typeof unauthorizedSignupPageRoute
}

const unauthorizedLayoutRouteChildren: unauthorizedLayoutRouteChildren = {
  unauthorizedEmailVerificationPageRoute:
    unauthorizedEmailVerificationPageRoute,
  unauthorizedResetPasswordPageRoute: unauthorizedResetPasswordPageRoute,
  unauthorizedSetNewPasswordPageRoute: unauthorizedSetNewPasswordPageRoute,
  unauthorizedSigninPageRoute: unauthorizedSigninPageRoute,
  unauthorizedSignupPageRoute: unauthorizedSignupPageRoute,
}

const unauthorizedLayoutRouteWithChildren =
  unauthorizedLayoutRoute._addFileChildren(unauthorizedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authorizedLayoutRoute: authorizedLayoutRouteWithChildren,
  unauthorizedLayoutRoute: unauthorizedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
